### ISSUE TITLE
Samsung 850  Pro not recognized ?

### ISSUE THREAD

**Issue by scav666** [Drive-Trust-Alliance/sedutil#10]
Hi!
First thanks for this software. 
I would like to test it but I can't. I dont know why my Samsung 850 Pro (connected through sata3 controller (on Marvell  88se9230 chipset)) is not recognized on my setup (windows 7).

sedutil-cli --scan

Scanning for Opal compliant disks
\\.\PhysicalDrive0 No
\\.\PhysicalDrive1 No
\\.\PhysicalDrive2 No
\\.\PhysicalDrive3 No
No more disks present ending scan

sedutil-cli --query \\.\PHYSICALDRIVE1
- 23:34:46.000 ERR : Invalid or unsupported disk \\.\PHYSICALDRIVE1

\\.\PHYSICALDRIVE1	- is my samsung 

info from wmic diskdrive list 

Volume0	 \\.\PHYSICALDRIVE0	 IDE\DISKVOLUME01.0.00__\4&19FEAA6C&0&0.0.0

Samsung SSD 850 PRO 256G SCSI Disk Device	 \\.\PHYSICALDRIVE1	 SCSI\DISK&VEN_SAMSUNG&PROD_SSD_850_PRO_256G\5&E93270A&2&000000

SanDisk Cruzer Micro USB Device	 \\.\PHYSICALDRIVE3	 USBSTOR\DISK&VEN_SANDISK&PROD_CRUZER_MICRO&REV_8.01\2243300C54E2CCFF&0

USB Flash DISK USB Device	 \\.\PHYSICALDRIVE2	 USBSTOR\DISK&VEN_USB&PROD_FLASH_DISK&REV_1100\1412045090058834&0

![850pro](https://cloud.githubusercontent.com/assets/16419187/11986158/b6aad570-a9cc-11e5-80ce-5038e55968dd.jpg)

**Comment by scav666** [comment]
I checked if I connect my Samsung directly to Sata2 ports on my motherboard( asus p6t se) instead of marvell sata 3 ports detection is working ok

Scanning for Opal compliant disks
\\.\PhysicalDrive0 12  Samsung SSD 850 PRO 256GB                EXM01B6Q
\\.\PhysicalDrive1 No
\\.\PhysicalDrive2 No
No more disks present ending scan

Samsung SSD 850 PRO 256G         \\.\PHYSICALDRIVE0                                         1           IDE\DISKSAMSUNG_SSD_850_PRO_256GB_______________EXM01B6Q\4&19FEAA6C&0&0.0.0 
Volume0                          \\.\PHYSICALDRIVE1                                         1           IDE\DISKVOLUME01.0.00__\4&19FEAA6C&0&0.1.0  
SanDisk Cruzer Micro USB Device  \\.\PHYSICALDRIVE2                                         1           USBSTOR\DISK&VEN_SANDISK&PROD_CRUZER_MICRO&REV_8.01\2243300C54E2CCFF&0



So it looks like there is problem with my Marvell 88se9230 controller not allowing to detect opal disks ??

**Comment by scav666** [comment]
Ok!
I managed to turn on opal and upload pba image(LINUXPBARelease-1.10.bin) to my samsung 850 pro using sata 2 controler(build on my asus p6t se board). Next, I switched disk to my marvel 88se9230 controler to sata 3 port and it boots and giving PBA prompt and I am able to boot.

So using Marvell marvel 88se9230 controler I cant use sedutil software, but I am able to do PBA and work on that drive. 

There is also one error I cant explain after I enter password and put enter PBA linux prompt is giving me error: ERR: Identify failed Invalid argument. Next the PC reboots and is booting normaly to OS using encrypted disk. So it works but I dont know why these error is showed.

**Comment by r0m30** [comment]
It looks like the Driver for your Marvell controller is blocking the OPAL commands.  Did you try using the Rescue Disk to configure/query the drive while it is attached to the Marvell controller?  The LinuxPBA* and Rescue systems are Linux based and should use the standard Linux kernel driver for the Marvell controller.

**Comment by scav666** [comment]
Hi
1) Linux Rescue Disk is detecting my Samsung 850 Pro on marvel 88se9230 controler. So it looks like it is  marvell windows driver related bug.

2) ERR: Identify failed Invalid argument. - is related to USB pendrives when I put sedutil-cli --scan on linux rescue disk/or during LinuxPBA auth.

**Comment by r0m30** [comment]
There is currently no support for USB attached drives.  It's on the list of things we'd like to do.
