### ISSUE TITLE
Error to compile syslinux-msedpba!!!

### ISSUE THREAD

**Issue by liuligang** [Drive-Trust-Alliance/sedutil#100]
OS: Ubuntu15.04

when I build the syslinux-msedpba,there are some errors.
As shown below ：

**/home/liuligang/syslinux-msedpba/dos/syslinux.c: In function ‘ main ’：
/home/liuligang/syslinux-msedpba/dos/syslinux.c:652:24: error: ' syslinux_adv ’undeclared (first use in this function)
     syslinux_reset_adv(syslinux_adv);
                        ^
/home/liuligang/syslinux-msedpba/dos/syslinux.c:652:24: note: each undeclared identifier is reported only once for each function it appears in
/home/liuligang/syslinux-msedpba/mk/embedded.mk:67: recipe for target 'syslinux.o' failed
make[3]: *** [syslinux.o] Error 1
make[3]: Leaving directory '/home/liuligang/syslinux-msedpba/bios/dos'
/home/liuligang/syslinux-msedpba/Makefile:286: recipe for target 'dos' failed
make[2]: *** [dos] Error 2
make[2]: Leaving directory '/home/liuligang/syslinux-msedpba/bios'
/home/liuligang/syslinux-msedpba/Makefile:255: recipe for target 'bios' failed
make[1]: *** [bios] Error 2
make[1]: Leaving directory '/home/liuligang/syslinux-msedpba'
Makefile:103: recipe for target 'bios' failed
make: *** [bios] Error 2
root@liuligang:~/syslinux-msedpba#** 

My steps is  below:
first, cd  syslinux-msedpba
second, make clean
third, make bios

Is my operation error or where there is no configuration ?
I need some help.thank you !

**Comment by r0m30** [comment]
Sorry, I have no idea why this is failing to compile.  The syslinux based pba is pretty much a historical artifact at this point, most of the legacy bios machines are approaching 10 years old and the only way I have of testing this type of environment is in a virtual machine but I can't issue trusted commands in a virtual machine.
