### ISSUE TITLE
PBA permanently changes UEFI boot order

### ISSUE THREAD

**Issue by anoother** [Drive-Trust-Alliance/sedutil#103]
I have a system with 2 drives. One (sda) houses Windows, the other Linux (sdb). Each has its own EFI system partition.

I've followed the instructions -- https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive -- to enable locking on sdb, and installed the PBA to sdb also. This all works a treat.

In machine's UEFI setup utility, I set the UEFI boot order as follows:
1. PBA (named `UEFI OS`)
2. Linux
3. Windows

The system successfully boots into the PBA, unlocks sdb and then reboots into boot option 2.

However, it seems to do this by actually *changing the configured boot order*. So, every subsequent boot/reboot, I have to re-enter the setup utility and reset the boot order as above.

Is there any way to avoid this? Eg. have the PBA chainload instead of rebooting, or set the boot order only for the next boot as opposed to permanently?

**Comment by dtasupport** [comment]
Amad,
 We are in constant need of people who will help us streamline things,
etc.  This is a hint :-).
  We would love to work with people who see the issues and can contribute a
fix (even if a partial fix).
  There are always a million issues.  These things never disappear.  But
everybody who helps will be a part of our permanent record of contributors!

  regards, Bob

(P.S. thanks for the competent email in any case).

regards,

Bob Thibadeau
412 370 1245

**Comment by r0m30** [comment]
This is usually caused by your bios, the pba does not alter any bios settings.  Some bios's re-enumerate the drives and remove boot options that are no longer present.  There may be a bios option to turn off this re-enumeration but it is vendor specific.

**Comment by gomoku** [comment]
Hey @anoother, you should take a look at this one:
 [https://ubuntuforums.org/showthread.php?t=2329948&page=3&p=13515355#post13515355](https://ubuntuforums.org/showthread.php?t=2329948&page=3&p=13515355#post13515355) 
which also refers to this one: https://github.com/Drive-Trust-Alliance/sedutil/issues/27

**Comment by drephaponu** [comment]
There's a partial solution to this problem but this is highly bios/uefi dependent. Basically whether your UEFI retains the result of the following commands or not.

After enabling OPAL on your SSD, power down, power up, unlock the drives and boot into linux. Then using efibootmgr manually create a entry to the bootloader you want to load. For example on my triple boot hackintosh, I run 

sudo efibootmgr -c -L "Clover UEFI" -l "\EFI\CLOVER\CLOVERX64.EFI"

followed by

sudo efibootmgr -o 4
Change the argument to -o based on output from efibootmgr (assumes "Clover UEFI" entry was added as Boot0004):

My ASUS UEFI retains the manually created entry as the first one and places all automatically renumerated items after this one.

If efibootmgr does not work for you (especially if you've got firmware on a device purchased around 2012-2013 - the main transition period from bios to UEFI and a lot of systems had just bios and partial EFI support) then try bcfg as a last resort as shown on this arch linux wiki - https://wiki.archlinux.org/index.php/Unified_Extensible_Firmware_Interface#UEFI_Shell

Your final last resort is to mod the BIOS/UEFI of your system to retain the entries.

**Comment by anoother** [comment]
Thanks all for the helpful replies. I have been doing some reading and think I understand things a bit better.

@r0m30, you mentioned in #27:

> The BIOS should find /boot/efi/EFI/antergos/grubx64.efi no matter if the drive is unlocked or shadowed and shouldn't delete the boot entry.

How does UEFI support work -- Is the EFI System Partition also replicated into the Shadow MBR? Or, does the locking range specifically exclude the ESP on UEFI systems, allowing UEFI boot to function normally?

**Comment by anoother** [comment]
OK, you can all blame me for this one ;)

I'd somehow managed to install GRUB onto my first (unencrypted) disk's ESP as well as my actual Linux boot disk.

To answer my own question...

> How does UEFI support work -- Is the EFI System Partition also replicated into the Shadow MBR? Or, does the locking range specifically exclude the ESP on UEFI systems, allowing UEFI boot to function normally?

... It looks like the UEFI image gets installed into the shadow MBR as an ESP.
