### ISSUE TITLE
Unable to change the password: ( ERR : Invalid command line argument --setSIDPwd )

### ISSUE THREAD

**Issue by gomoku** [Drive-Trust-Alliance/sedutil#105]
As described on [https://github.com/Drive-Trust-Alliance/sedutil/wiki/Command-Syntax](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Command-Syntax):

`setSIDPwd <password> <newpassword> <device>`

When I try sedutil-cli.exe x64 on Windows 7 UEFI SP1 64bit cmd:

`sedutil-cli --setSIDPwd oldPassword newPassword \\.\PhysicalDrive0`  it returns:

> - 19:56:47.000 ERR : Invalid command line argument --setSIDPwd

`sedutil-cli -v --setSIDPwd oldPassword newPassword \\.\PhysicalDrive0` it returns:

> - 19:56:55.000 DBG : Log level set to DBG
> - 19:56:55.000 DBG : sedutil version : 1.12
> - 19:56:55.000 ERR : Invalid command line argument --setSIDPwd

What the... ?

**Comment by Jm3LZeT** [comment]
Run sedutil-cli --help
The documentation appears to be wrong.  The correct parameter is --setSIDPassword.

**Comment by gomoku** [comment]
Thanks, worked, and yes I knew about --setSIDPassword and was considering it too as an alternative, but I did not want to risk that I change the wrong password or screw something up. And yes it seems the documentation is like 1 year behind sedutil, and this is not the first such case when the wrong documentation is misleading.
