### ISSUE TITLE
Alternative script-based LinuxPBA with support for NVMe and faster boot

### ISSUE THREAD

**Issue by gebart** [Drive-Trust-Alliance/sedutil#106]
I had some trouble getting the C++ PBA loader to work with my NVMe drive, so I replaced it with a shell script instead. I have posted the code and some very brief documentation on the process in my repo below:
https://github.com/gebart/opal-kexec-pba

Additionally, instead of rebooting to get back to the normal boot loader, it uses kexec to launch the real kernel after unlocking the drive, which saves some time since we don't have to go through UEFI firmware initialization another time.

I have attempted to document the process in the README as best I could.
I figured it might be useful to others so I'm posting it here for visibility, but I don't have any time to support it further. It is released under GPLv3, feel free to reuse the scripts and ideas if you want to make an alternative PBA image.

**Comment by r0m30** [comment]
I just went with C because it's my default.  I like the idea of a script based PBA but it may be more difficult to do that when multi-user functionality is added.
