### ISSUE TITLE
Crucial SED new installation, NOT_AUTHORIZED code received

### ISSUE THREAD

**Issue by denigmus** [Drive-Trust-Alliance/sedutil#112]
I am trying to configure on Windows 10. I want to preserve installation I have.
I run cmd.exe as Administrator.
Secure boot is disabled.
MB GIGABYTE GA-Z170X-Designare.

C:\>sedutil-cli.exe --scan
Scanning for Opal compliant disks
\\.\PhysicalDrive0  2  Crucial_CT1050MX300SSD1                   M0CR040
No more disks present ending scan

C:\>sedutil-cli.exe --loadPBAimage ***** UEFI64_Release-1.12.img \\.\PhysicalDrive0
- 19:30:36.000 ERR : method status code NOT_AUTHORIZED
- 19:30:36.000 ERR : Session start failed
- 19:30:36.031 ERR : One or more header fields have 0 length
- 19:30:36.031 ERR : EndSession Failed

I read that NOT_AUTHORIZED is related with wrong password. But what can be wrong for fresh install? Previously I tried USB with UEFI64 PBA without success - the output was similar to https://github.com/Drive-Trust-Alliance/sedutil/issues/11

Could you help?

**Comment by mintegral** [comment]
I have the same problem with a Crucial_CT1050MX300SSD1.

I didn't set a password at all, but I am locked out. A reboot doesn't change that.

`
$ sudo sedutil-cli --revertnoerase a /dev/sda
[sudo] Passwort für mci: 
- 20:50:05.501 ERR : method status code AUTHORITY_LOCKED_OUT
- 20:50:05.501 ERR : Session start failed
- 20:50:05.527 ERR : One or more header fields have 0 length
- 20:50:05.527 ERR : EndSession Failed
`

**Comment by denigmus** [comment]
Use PSID Revert in Crucial Storage Executive software.  **That's the only way to be unlocked now.** You will lose all data and you can only do this by connecting drive to another PC where Crucial Storage Executive is installed. Don't install any OS right after that, lock the drive with sedutil and your own password first. PSID Revert with sedutil will not work. 

It's a short version. I'll be writing post on my blog with all details in the future.

**Comment by mintegral** [comment]
Yes, thank you. I also downloaded the _Crucial Storage Executive_ software and reset the drive with the PSID.
After that I booted the drive with a Live USB Arch Linux system and set up the security system with **hdparm**. (Now I could finally see the _Security_ option in `hdparm -I /dev/sdX`)

**Comment by r0m30** [comment]
You can't load the pba until you set up the drive using initialsetup.  sedutil psidrevert works on Crucial drives, msed was born because Storage executive wasn't available when I purchased my first OPAL SSD.

**Comment by r0m30** [comment]
@vogelfreiheit in a word Windows.........
Any Windows that supports bitlocker automatically take ownership of all OPAL drives during the install unless you set a registry key at the VERY beginning of the install
