### ISSUE TITLE
Rescue image not starting

### ISSUE THREAD

**Issue by daincredibleholg** [Drive-Trust-Alliance/sedutil#118]
I am about to install my new Samsung 850 EVO and currently playing around with sedutil. It detects my current drive - a Samsung 850 Pro - successfully when I run it in my normal Ubuntu installation.
But when I try to boot from my USB stick with the Rescue image on it, it does exactly nothing. This means, I enter the boot device menu in my UEFI/BIOS, select the USB drive and hit enter. This brings me back to the same screen.
The same stick, the same procedure, but the UEFI64_Release or UEFI64_Debug image on it works just fine.

I do use the images from the exec repository.

Any ideas how to get around this?

**Comment by kylemanna** [comment]
Maybe that you're booting it wrong.  The Rescue image I had played with was a BIOS / legacy image.  If you're in UEFI mode (which it sounds like since the UEFI images work as expected), it's probably failing and giving up.  Check your UEFI settings for a BIOS or legacy boot mode enable.

**Comment by r0m30** [comment]
There is a new RESCUE64 that is UEFI, this may solve your issue.  There is also the possibility that the Rescue kernel doesn't have the proper device support for your machine.
