### ISSUE TITLE
Testing PBA shows warnings

### ISSUE THREAD

**Issue by daincredibleholg** [Drive-Trust-Alliance/sedutil#119]
I am currently playing around with sedutil. Part of this is obviously testing the PBA.

Doing this produces a couple of Warnings I'd like to verify are valid, as there is a OPAL capable disk in my machine, but it the password isn't enabled yet. Here is the screenshot:

![uefi64_debug screenshot](https://cloud.githubusercontent.com/assets/281551/21900111/873b5c1c-d8ea-11e6-8cbf-768b13f8a7c7.jpg)

Especially the `INVALID_PARAMETER` makes me a bit nervous.

I do run this on a T460 and I do have a Samsung 850 Pro installed at the moment, which I am going to replace with a Samsung 850 Evo.

**Comment by gomoku** [comment]
Have you ever used the search function? Please close it as a dupe of: [37](https://github.com/Drive-Trust-Alliance/sedutil/issues/37), [43](https://github.com/Drive-Trust-Alliance/sedutil/issues/43), [44](https://github.com/Drive-Trust-Alliance/sedutil/issues/44), [45](https://github.com/Drive-Trust-Alliance/sedutil/issues/45).
By the way of writing I just might add from myself, that I can not look anymore at that terrible formatting scattered all over the screen., please fix it sedutil team.

**Comment by daincredibleholg** [comment]
Not this time, sorry for that.
