### ISSUE TITLE
Apps and Command-line freeze PC

### ISSUE THREAD

**Issue by DrEmpiricism** [Drive-Trust-Alliance/sedutil#121]
For some reason the sedutil-cli --scan command, as well as the SED Util apps on the main site, freeze my PC.  It does not happen immediately; rather, it happens after the program appears to try to scan for TGC/Opal drives.

I have 2 Crucial MX300 SSDs and 2 Seagate Secure Enterprise drives (FIPS certified), all of which are TGC/Opal compliant, but the software applications, and command-line utilizing the --scan command, seem to freeze my PC only when scanning/detecting the Crucial SSDs.  I was hoping the GUI would at least give me the ability to control passwords on my non-boot Seagate drives but it will not.

I even did a PSID revert via Crucial's Storage Executive and re-installed my desktop OS (Windows 10 Enterprise x64) but that did not help, either.

Any input/advice/help would be greatly appreciated.

**Comment by gomoku** [comment]
If you are able to generate and attach any debug log, that would be also greatly appreciated: 
`sedutil-cli -vvvvv --scan` or
`sedutil-cli -vvvvv --scan > debug.txt 2>&1`

**Comment by DrEmpiricism** [comment]
Sorry for the late response.  Was out of the country for work.

Anyways, I ran it with the command, and I can see the debug .txt create immediately after entering the command; however, upon a cold-boot (only way to "unfreeze" the system), the debug.txt is gone so I have no log of it.

I am wondering if it has to do with this Crucial MX300?  It's a SED/Opal 2.0 but it's very picky with software, even software like hdparm, or really any software that works via command-line.

For the time being, I've set my desktop up as an endpoint by connecting it to my Enterprise server and using my Enterprise SED/data security software on the server to control the SED(s) on my desktop, but I'd rather have something simple and stand-alone.  No clue what the deal is here but I am going to try this tool on a spare SED to see if it works no problems, and use the --scan command on my Enterprise server to see if it picks up the SEDs on that without a problem.

**Comment by gomoku** [comment]
Yes, in that case a method of deduction will be most appropriate, by this method you probably can distinguish SSD(s) with which there is a problem.

**Comment by DrEmpiricism** [comment]
It picks up all my Opal 2.0 SEDs on my Enterprise server, and works flawlessly on a spare Seagate Secure Drive (Opal 2.0, as well), so it's the Crucial MX300 that is causing the hang-up.

Really with how picky this drive is with everything - from BitLocker eDrive to SED-specific software - I'm about to get rid of it and get another brand.

**Comment by DrEmpiricism** [comment]
Commands with the Crucial SSD work other than --scan, though --scan works in PBA  and even when I run my custom WinPE_10 bootup where I have the GUI SED tools, Crucial's software and other SED/management software.  Using these tools with a nice custom WinPE build is great.

**Comment by DrEmpiricism** [comment]
As an update, this ended up being a hardware issue, which I'm assuming results from the combination I initially tested this on.  It would only work in a Linux environment and would not even work on my custom Win10PE with the disk offline.

However, I updated the actual OPROM hardware drivers flashing my new custom BIOS and went from Microsoft's default AHCI drivers in Windows to AMD SATA drivers and it worked properly.
