### ISSUE TITLE
Please document the boot process for both BIOS and UEFI mode

### ISSUE THREAD

**Issue by yacoob** [Drive-Trust-Alliance/sedutil#122]
The instructions on the wiki are very pragmatic: "run those commands to get this result". It'd be good if some documentation would be added about the innards of the setup - how and when PBA is invoked in the boot process, and how the booting process is handed over to existing bootloaders. Right now, despite there being an UEFI PBA, I can't quite imagine how does the boot process look like with UEFI - do I need to have CSM enabled in UEFI and boot in legacy mode, have PBA unlock the disk, and then magically do something to come back to UEFI boot manager? :) 

Encrypting an disk with existing data is already a stressful experience - please make it easier for the users by documenting the boot process and setting their expectations.

Thanks in advance!

**Comment by DrEmpiricism** [comment]
The only requirement, as stated, is Secure Boot must be turned off.  I did this on a UEFI system yesterday without any problems and I had everything set to "UEFI Only" with Secure Boot off.  No CSM.

Also, how a SED PBA works is pretty universal: Boot into the PBA using your F12 key, or whatever key temporarily changes your boot sequence, and voila.

You can also look at the directory hierarchy in the PBA after flashing it to a USB stick and you'll notice the .efi files are about identical to the ones found in the EFI partition on a GPT volume.

**Comment by yacoob** [comment]
Your last sentence has a key phrase: "pretty common across SED key management programs". I've never used anything like that, so I don't really know what to expect. The purpose of this bug is to document in detail how things should look like in a correct deployment. For example, it's unclear to me what happens after disk is unlocked in PBA - does it try to load another UEFI application after that? Or load a local kernel that gets bundled onto the PBA?

Instructions along the lines of "this is what will happen" are less useful from "this is how it is build" when things break :)

**Comment by r0m30** [comment]
I've updated the doc but this level of detail isn't in the current doc and probably won't be for a long time.

**Comment by mallikarjunasai995** [comment]
@r0m30  Where can i find the doc details ? (are we referring the same content which is there in wiki )
