### ISSUE TITLE
not seeing the error of "AUTHORITY_LOCKED_OUT"

### ISSUE THREAD

**Issue by igenyar** [Drive-Trust-Alliance/sedutil#124]
I am using:
```
Samsung SSD 850 PRO
Ubuntu 16.04
sedutil version : 1.12
```

After a number of failed authentications, I expect to see "AUTHORITY_LOCKED_OUT" as documented. However, I never see this error, only "NOT_AUTHORIZED". Is there a way to derive this error output? Thank you.

**Comment by kylemanna** [comment]
Per the [wiki FAQ](https://github.com/Drive-Trust-Alliance/sedutil/wiki/FAQ), `AUTHORITY_LOCKED_OUT` means you've typed your password wrong too many times and need to power cycle the drive.

> **AUTHORITY_LOCKED_OUT**
> You have exceeded the maximum number of tries to enter your password correctly, the drive must be powered down before you can continue.

**Comment by kylemanna** [comment]
I mis-read your original question, what command were you running?

**Comment by r0m30** [comment]
The number of attempts to lock out a user is "Vendor Unique" so it's up to the manufacture to set this value.  How many is "a number" and is there a power cycle in between attempts?  A power cycle resets the counter.  I don't have a 850 pro but the 850 evo does have this set.
