### ISSUE TITLE
PBA still showing after disabling locking range

### ISSUE THREAD

**Issue by snow3461** [Drive-Trust-Alliance/sedutil#125]
Trying to disable locking on my Crucial MX200, i followed the instructions in wiki
    sedutil-cli -–disableLockingRange 0 <password> <drive>  
    sedutil-cli –-setMBREnable off <password> <drive>

First command returns:

    DBG : Log level set to DBG
    DBG : sedutil version : 1.12
    DBG : Disabling Locking Range 0
    INFO: LockingRange0 disabled

Second one returns:

    DBG : Log level set to DBG
    DBG : sedutil version : 1.12
    DBG : Disabling Locking Range 0
    INFO: LockingRange0 disabled
So, if I understood correctly, the PBA should be disabled and the drive should be no longer locked.

But after a power cycle, PBA still shows up.
Did I understand wrong ? What is the actual way to disable locking and PBA.

**Comment by r0m30** [comment]
Those are the correct commands.  Is this a MX200?  This is one of the bugs I've encountered in the MX200 firmware.

**Comment by snow3461** [comment]
Indeed, that was with a Crucial MX200. I totally disabled OPAL because I have no use of it right now, but in the future I might need it again. Is it something corrected on newer firmware?

**Comment by r0m30** [comment]
I've tried several firmware revs on the MX200 and disabling the MBR hasn't worked on any of them.  There have also been issues with removing OPAL without erasing the global range.  The drive does work as far as the lock/unlock goes.

**Comment by snow3461** [comment]
And yet its advertised as beeing TGC Opal 2.0 compliant...
