### ISSUE TITLE
Does sedutil rescue usb content my keys?

### ISSUE THREAD

**Issue by denigmus** [Drive-Trust-Alliance/sedutil#127]
I don't remember how I have created rescue USB, so I wonder whether it stores a  copy of my keys or not? I want to understand if I can keep it close to PC or need to hide it like in case of Bitlocker's USB stick.

**Comment by Lutwick** [comment]
The rescue USB I know only includes a bootable Linux with sedutil.
(https://github.com/Drive-Trust-Alliance/exec/blob/master/Rescue.img.gz?raw=true).

After booting from the stick you can execute all sedutil commands in the console.
So there is nothing user specific on it and you do not need to keep it secret.

**Comment by denigmus** [comment]
Thanks, true, now I recalled that it was done from there :)
