### ISSUE TITLE
USB3 to SATA3 chipset issues?

### ISSUE THREAD

**Issue by msackman** [Drive-Trust-Alliance/sedutil#128]
I'm hoping to get a Samsung 850 Pro set up with SED and as a boot disk for Linux. But, externally over a USB3 to SATA bridge.

Currently, I have one based on the ASMedia ASM1053 chipset. This doesn't seem to work - whilst I have installed linux on the drive via this adaptor, with UEFI only, secure boot off, CSM off, sedutil will not detect the drive as supporting OPAL. After a lot more reading, I've learnt that ASM1053 is SATA1 only, not SATA3, so I have some other adaptors coming, based on ASM1153E which is definitely SATA3, and also JMicron JMS567 chipset which is also SATA3. Does anyone know if these will work?

Or, is it just impossible to get OPAL set up on a drive over USB - is it something that's part of the SATA spec that simply doesn't ever get exposed when you're going over USB?

**Comment by msackman** [comment]
Update: neither of these chipsets work either for OPAL. Is there any chipset which allows USB-connected drives to use OPAL? It seems quite odd that there's not given the risk of portable external drives going walkies...

**Comment by kylemanna** [comment]
Looks like you may need to find a USB chipset that has support for the following [according to this](https://www.flashmemorysummit.com/English/Collaterals/Proceedings/2012/20120821_S103A_Chen.pdf):

* `SECURITY PROTOCOL OUT (B5h)`
* `SECURITY PROTOCOL IN (A2h)`

The [TCG Storage Interface Interactions Specification (SIIS)](https://www.trustedcomputinggroup.org/wp-content/uploads/TCG_SWG_SIIS_Version_1_05_Revision_1_00.pdf) mentions those security protocols also.

As for `sedutil` detecting the drive, you may have to dig in to the code and it may just be an issue with not scanning all the devices.  Checkout pull request https://github.com/Drive-Trust-Alliance/sedutil/pull/108 which adds support for NVMe.  I also have some [prebuilt images on my fork as I needed NVMe support](https://github.com/kylemanna/sedutil/releases).

**Comment by r0m30** [comment]
USB chipsets are a nightmare, I have a half dozen that don't work.  They need to support UASP to work with sedutill, but even those that claim support fail, often randomly, which can be really frustrating.  If you buying on the A word avoid anything under $5.00, these are usually clones and they almost always fail.
