### ISSUE TITLE
failing to build linuxpba images

### ISSUE THREAD

**Issue by etfeet** [Drive-Trust-Alliance/sedutil#129]
I've succsessfuly built sedutil and linuxpba. However, when I try to build the images its failing during the buildpbaroot step.

Here's the fork im building off (to address nvme issues)

https://github.com/etfeet/sedutil

patched with the following:
https://github.com/bcarmo-caio/sedutil/commit/5ca6100917a025f6e11ae20838e1e37e7db2d587

https://github.com/Drive-Trust-Alliance/sedutil/pull/108/commits/91ed062b86a0df0f8c2664cfb50500692d4e089d

https://github.com/Drive-Trust-Alliance/sedutil/pull/108/commits/c6f122cd90fda404f095de89bb583b775e62afa3

make O=PBA64 ultimately fails with the following errors:
```
cfns.gperf: In function ‘const char* libc_name_p(const char*, unsigned int)’:
cfns.gperf:101:1: error: ‘const char* libc_name_p(const char*, unsigned int)’ redeclared inline with ‘gnu_inline’ attribute
cfns.gperf:26:14: note: ‘const char* libc_name_p(const char*, unsigned int)’ previously declared here
cfns.gperf: At global scope:
cfns.gperf:26:14: warning: inline function ‘const char* libc_name_p(const char*, unsigned int)’ used but never defined
make[3]: *** [Makefile:1058: cp/except.o] Error 1
make[3]: *** Waiting for unfinished jobs....
rm gcc.pod
make[3]: Leaving directory '/home/rory/sedutil-2/images/scratch/buildroot/PBA64/build/host-gcc-final-4.9.3/build/gcc'
make[2]: *** [Makefile:3975: all-gcc] Error 2
make[2]: Leaving directory '/home/rory/sedutil-2/images/scratch/buildroot/PBA64/build/host-gcc-final-4.9.3/build'
make[1]: *** [Makefile:862: all] Error 2
make[1]: Leaving directory '/home/rory/sedutil-2/images/scratch/buildroot/PBA64/build/host-gcc-final-4.9.3/build'
make: *** [package/pkg-generic.mk:199: /home/rory/sedutil-2/images/scratch/buildroot/PBA64/build/host-gcc-final-4.9.3/.stamp_built] Error 2
```

full build output:
[pba64.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/786737/pba64.txt)

**Comment by kylemanna** [comment]
The current build system is *very* dependent on the host system having specific versions of things installed that match the buildroot or tiny core linux install.

To start to work around this I setup a Docker container to build the UEFI64 and Rescue images I care about.  Take a peek at my fork to see if it can help you at all: https://github.com/kylemanna/sedutil/tree/docker/images

**Comment by r0m30** [comment]
If you are still having problems with the new (1.15) version please reopen this issue.
