### ISSUE TITLE
hardware (disk, CPU, mainboard) compatibility questions

### ISSUE THREAD

**Issue by lutel** [Drive-Trust-Alliance/sedutil#132]
First of all - thank you for the great software you have developed. This is exactly what I was looking for. I plan to make new build with hardware disk encryption, I know drive must be OPAL compatible, but I don't know about mainboard / CPU requirements. Could you please help me with following questions?

- Could you tell me if I have to have Q270 (together with TPM) chipset or Z270 is fine to enable password before boot?
- What about CPU - does it have to be non-K (like 7700, but not 7700K)? 
- Do you know if Samsung 960 PRO has OPAL and works with sedutil? I saw it might not be supported by current firmware.
- Will the sedutil work for dual-boot (Linux+Windows) configurations?

**Comment by kylemanna** [comment]
I don't think there are any dependencies on the hardware other then having a TPM.  I have this working on a Skylake Z170 laptop, a Dell Precision 5510, with a Samsung 960 EVO.  I never updated the firmware on my NVMe drive.

My laptop dual boots to Arch Linux or Win10 after the PBA unlocks the drive.

**Comment by r0m30** [comment]
There aren't any known hardware dependencies, a TPM is NOT required to run sedutil.
