### ISSUE TITLE
Can the BIOS PBA boot to FreeBSD?

### ISSUE THREAD

**Issue by epon** [Drive-Trust-Alliance/sedutil#134]
I couldn't find the answer to this looking through the docs/issues list.

I'm planning on setting up a FreeBSD install on my Segate SED and was wondering if the BIOS PBA can chainload it? Do I need to do anything special?

Thanks!

**Comment by kylemanna** [comment]
Should work.

The system works by installing a basic shadow Linux image that BIOS or UEFI boots and unlocks the drive.  After the drive is unlocked and the shadow image is disabled, the system reboots again and the BIOS/UEFI sees the protected partition table and corresponding file systems.  At this point the system doesn't even know the underlying storage system was once encrypted and boots normally.

**Comment by kylemanna** [comment]
Also this is related: https://github.com/Drive-Trust-Alliance/sedutil/pull/87/commits

**Comment by kylemanna** [comment]
See Related https://github.com/Drive-Trust-Alliance/sedutil/pull/87
