### ISSUE TITLE
what is USER ID ?

### ISSUE THREAD

**Issue by jackiea5106** [Drive-Trust-Alliance/sedutil#135]
Dear Sirs:
   When I try the function "Enableuser" with "Sedutil-cli" , there always show the error message==>" incorrect number of parameters. "
I know may be I input the error user id. But i do not what is USER ID ?

**Comment by r0m30** [comment]
What is the exact command you are entering?
OPAL has multiuser support but that is not currently implemented.

**Comment by jackiea5106** [comment]
Dear r0m30:
  I enter the exact command==>”enableuser” but always get the error response.

**Comment by r0m30** [comment]
I think I understand now....
A userid is one of the defined users in the TCG spec.  They are Admin1-n and User1-n, the query tells you how many of each you have
OPAL 2.0 function (0x0203)
    Base comID = 0x1000, Initial PIN = 0x0 , Reverted PIN = 0x0 , comIDs = 1
    **Locking Admins = 4, Locking Users = 16,** Range Crossing = N

So the command would be sedutil-cli --enableuser User1 {password} {drive}

You can enable any Admin or User up to the numbers shown in the query.  There is nothing else you can do with them after that until sedutil is updated with multiuser support.

**Comment by jackiea5106** [comment]
Dear Sir:
   Thank you for your answer. I have another question about TCG Opal password type.
As I know the password have 4 Type==> MSID ,PSID ,Admin ,User password.
Do you know the other type “SID” Password for TCG Opal ?  Does the “Sedutil Tool” can support test SID Password ?
