### ISSUE TITLE
Crucial MX300 SSD + Linux Mint 18.1 + sedutil

### ISSUE THREAD

**Issue by Shekelme** [Drive-Trust-Alliance/sedutil#140]
Hello!
 
I'm trying to set up a password protection for Crucial MX300 SSD (750 Gb, bootable, fw: M0CR040). The SSD is installed in Samsung R780 notebook with Linux Mint 18.1 x64 installed.
 
First of all, I was not able to start the notebook with UEFI PBA (using correct BIOS setting). When I flash a LINUXPBARelease-1.12.img to USB drive via dd, it's booting with this image, it's asking for passphrase, but when I input some random passphrase (should I just skip this step? What should I input there?) then some screen is flashing and the notebook rebooting. I have no time to read the messages on that screen.
  
Furthermore, I have unpacked the sedutil_LINUX.tgz with "tar -zxvf sedutil_LINUX.tgz" command, I've navigated to /home/user/sedutil/Release_x86_64/GNU-Linux, but then when I try to perform "sedutil initialsetup ..." in terminal I see the message "sedutil-cli: command not found".
 
What am I doing wrong in both cases described above?
 
p.s. please sorry for my English...

**Comment by DrEmpiricism** [comment]
The screen flash for the PBA test is normal.

As far as why the command isn't working for you: I can't answer that.  I just tried it on Debian after moving everything from GNU-Linux to the root sedutil directory and sedutil-cli --query /dev/sda worked fine.  I did not try to initialize a drive, however.  Do any other commands work or no?

**Comment by Shekelme** [comment]
If the screen flash for the PBA test is normal, then how can I ensure that PBA is able to detect my OPAL SSD?..

Sure other commands are working. sudo apt update, for example. ) Could you please explain what does this mean: "after moving everything from GNU-Linux to the root sedutil directory"? I'm a little dumb in English and in Linux...

**Comment by kuro68k** [comment]
The MX300 firmware is very buggy. Mine increases the "unexpected shutdown" count every time my computer sleeps or hibernates or is turned off. It may be an issue with the SSD.

**Comment by kylemanna** [comment]
You might look at preforming the initial setup from [Rescue System](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Test-the-Rescue-system) if you can't get the sources to build and compile on your native distribution.

Ideally you'd be able to flash the rescue system to a USB flash drive, boot of of that, configure you drive per the directions, and then figure out what's wrong with your PBA.

**Comment by r0m30** [comment]
The PBA and doc have been updated.  The new Rescue disk has the PBA images preloaded in /usr/sedutil
