### ISSUE TITLE
Debug PBA fails to recognize supported drive (Drive /dev/sda not supported)

### ISSUE THREAD

**Issue by kforner** [Drive-Trust-Alliance/sedutil#143]
Background: sedutil perfectly recognizes my disk when booting on a ubuntu live usb key. 
`sedutil-cli --query` accurately reflects all the applied operations.

But if I boot on the Debug PBA on a usb key, it prompts a password. 
After typing the password, it prints:
```
Scanning....
Drive /dev/sda not supported
```
I then login on the Debug system (root/"").
Then 
```
#sedutil-cli --scan
Scanning for Opal compliant disks
/dev/sda No Disk 3.20
No more disks present ending scan
```
and
```
sedutil-cli --query /dev/sda
ERR: Invalid or unsupported disk /dev/sda
```

Once again, the sedutil-cli command works perfectly from my ubuntu live usb key.
Caveat: the disk is not locked, i.e I followed the instructions:

> If you want to turn off Locking and the PBA:
> sedutil-cli -–disableLockingRange 0 <password> <drive>  
> sedutil-cli –-setMBREnable off <password> <drive>

**Comment by kylemanna** [comment]
Is it possible that the PBA is missing support for your hardware in the kernel or something similar.  Can you provide details on your hardware and what software versions do and don't work?

**Comment by r0m30** [comment]
It is most likely a kernel device support issue.  Can you try the new release?
