### ISSUE TITLE
EFI PBA does not show in BIOS (I figured out why)

### ISSUE THREAD

**Issue by syja** [Drive-Trust-Alliance/sedutil#144]
I have a MSI GL62-6QD laptop with Win 10 on one hard disk and a Samsung SSD 850 EVO 250GB with Linux Mint.  Installation of the PBA on the Samsung 850 went without a hitch but there is a problem.

The UEFI64_Release-1.12 PBA image is ok, it boots fine into the password prompt from a USB but not from the Samsung drive.  When I enable locking and reboot, it  boots into grub shell.  Whether the password prompt appears prior to that at all, I can't tell.

I am not familiar with the grub shell so I don't know how I can use it to troubleshoot the problem.  Any help in solving this will be much appreciated.

**Comment by syja** [comment]
Well, I finally figured out the grub shell part of my problem, thanks to a hint from **anoother** (issue #103).  I have a similar setup: Win 10 on an unecrypted disk /div/sdb and Linux Mint on the Samsung 850 /div/sda and, I be darned, the grub was installed in the EFI partition of the Windows disk.  In the BIOS (Aptio Setup Utility) it was listed simply as **Hard Disk: ubuntu** with no drive specified so I didn't realize it.

This happened despite the fact that /dev/sda was selected in the Mint installer for grub installation.  Perhaps a bug in the installer.  

Anyway, with locking and the PBA enabled, grub on the Windows disk tried to boot but couldn't so opened the shell. 

That explains it.  I have now moved grub from the Windows EFI partition to /dev/sda so there is no more confusion.

However, I still have a problem.  With locking enabled, the Samsung disk disappears from my BIOS but the shadow MBR does not show at all.  I reloaded the PBA image twice, no indication of any errors.  The same image loaded on to a USB stick appears in my BIOS as **USB Hard Disk: UEFI: Generic Flash Disk...** and works fine.

The locking function flags get set as follows.

**Locking disabled:**
Locked = N, LockingEnabled = Y, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y

**Locking enabled and locked:**
Locked = Y, LockingEnabled = Y, LockingSupported = Y, MBRDone = Y, MBREnabled = Y, MediaEncrypt = Y

Am I doing anything wrong?

**Comment by syja** [comment]
I have locked the drive and examined it with GParted from a Live USB.  The shadow MBR reads as follows:

Partition: /dev/sda1
Name: EFI System
File System: fat16
Label: UEFI64_Rele
Size: 5.98 MiB
Flags: boot, esp

GParted warns that it is unable to read the contents of fat16 file system but I have no problem mounting and exploring /dev/sda1.  There is an EFI folder and I see the following files listed in /mnt/EFI/boot
**bootx64.efi,  bzImage,  ldlinux.e64,  rootfs.cpio.xz,  syslinux.cfg**

The same UEFI64 PBA image loaded to a USB stick looks exactly the same in GParted, including the fat16 warning.  However, in addition to the EFI folder it also contains a **System Volume Information** folder (containing IndexerVolumeGuid) which is missing in the shadow MBR.

Could the missing **System Volume Information** folder be the reason why the PBA doesn't appear in my BIOS?  If so, how can I fix it?  Can I just copy the folder to the shadow MBR PBA image from the image on my USB?

All EFI partitions on my other disks contain this folder.

**Comment by syja** [comment]
Tried it, didn't help.  The **System Volume Information** folder copied from the USB PBA image over to the shadow MBR didn't make it appear in my BIOS.

My BIOS is Aptio Setup Utility, Secure boot and Fast boot disabled.  I don't see any other boot relevant BIOS settings and, as I mentioned before, the PBA boots fine from USB.

Any suggestions what else to try?

**Comment by syja** [comment]
Ok, I think I figured out what's happening.  I wrongly assumed that UEFI BIOS automatically detects EFI boot loader on any hard drive but that's apparently not the case, at least not in my BIOS.  An entry for each loader needs to be created first in the BIOS NVRAM.

Here is my situation.  When I originally installed Linux Mint on my Samsung SSD, grub got installed in the EFI partition of my Windows disk, /dev/sdb1, and only two partitions were created on my Linux disk, sda1 as root and sda2 as swap.  I later added sda3 as the EFI partition and moved grub there.

As a result, my Linux boots normally from /dev/sda3 but when lock is enabled, the PBA is located on /dev/sda1 which isn't seen by my BIOS.

Using efibootmgr, I created a BIOS entry for the PBA.  It then appeared in the list and I was able to boot from it and unlock the drive.  This proved that PBA in the shadow MBR works but, sadly, after restart, my normal Linux boot didn't show in the list.  And, after a brief shutdown to lock the drive again, neither did my PBA boot.  So this is obviously not a solution.

In "typical" installations, the EFI system partition is usually /dev/sda1 and that's, I think, why the PBA works, because it's also on a /dev/sda1 partition.

Renumbering my /dev/sda partitions would probably solve the problem but I didn't find a way to do it easily short of deleting all partitions and reinstalling Mint.  Any advice will be most welcome.

**Comment by kylemanna** [comment]
I noticed that my UEFI on a Dell Precision 5510 will change the EFI boot order (as viewed from `efibootmgr`) and disable entries as my Samsung EVO 960 went in an out of shadow mode despite creating entries with `efibootmgr`.  This threw a wrench in the boot and required me to manually unlock and jump through similar hoops.

The solution was to manually enter two entries in the Dell UEFI (which later show-up in `efibootmgr` as expected, but my UEFI must treat them special):
1. Highest priority was /dev/nvme0n1p2 (avaiable after unlocked)  and point to `/EFI/systemd/systemd-bootx64.efi`.  The `systemd-boot` EFI bootloader could then boot Arch Linux or Windows 10 as previously worked without locking enabled.
2. Second priority was the `syslinux` bootloader on the shadow MBR at `/EFI/boot/bootx64.efi` as installed by the UEFI64_Release image.
3. The system would then add a partition boot, which I would push to the end.  If I didn't move the partition boot to the end of the boot chain the system would boot to Win10 everytime I unlocked the drive.

I spent hours trying to figure out why my `efibootmgr` options weren't sticking across power cycles, the Dell UEFI was to blame.

**Comment by syja** [comment]
Thanks kylemanna, your experience is similar to mine.  I have a similar setup except my Windows is on a separate disk.  BIOS entry for my Linux `/dev/sda3` was created during installation, the PBA boot entry I created manually using `efibootmgr`  The third BIOS hard disk entry is Windows.  I disabled it in BIOS since I can boot Windows from the Grub menu.  That leaves just two BIOS hard disk entries, Mint (sda3) and the PBA (sda1) but only one is seen depending whether the disk is locked or not..

Looks perfect, don't even have to worry about boot order but my BIOS seems to be too slow to update the list.  When I unlock the drive, no hard disk is listed and I can't boot.  Interestingly, it works when I unlock the drive from a USB stick.

I also noticed that `efibootmgr` changes don't survive a reboot.  The only way I could create a boot entry and make it last was to mount the EFI partition to `/boot/efi`.  Don't know how to make boot order changes stick.

**Comment by kylemanna** [comment]
> I also noticed that efibootmgr changes don't survive a reboot. The only way I could create a boot entry and make it last was to mount the EFI partition to /boot/efi. Don't know how to make boot order changes stick.

This sounds suspicious.  Perhaps your UEFI is modifying the boot table?  My system doesn't delete my entries, but it certainly appears to modify the boot order I see when i run `efibootmgr -v`.

I think something to consider is evolving the PBA to make it possible to do chain loading.  With chain loading (not possible with syslinux + EFI, so we'd need another bootloader) it would be possible to directly call another bootloader (`systemd-boot` in my case) that could then present an option to boot to Windows or Linux after unlocking the drive.  In this case, you depend on your UEFI only to boot the PBA.

I assume there are other more buggy and clumsy UEFI implementations. Mine was at least workable after I understood what was going on.

**Comment by syja** [comment]
I don't know what the deal is with `efibootmgr` and my UEFI.  I know that when I disconnect an HDD, it's gone from both UEFI and `efibootmgr` boot lists.  But it still should be saved in NVRAM, right?  Where does `efibootmgr` read the boot entries from?

When I first created a boot entry for the PBA and restarted, it didn't show in UEFI.  I googled and on some forum I found a detailed example on how to create a boot entry.  First thing they did was to mount the ESP to `/boot/efi`.  So I mounted the PBA EFI partition, created the boot entry again and this time it stayed!  I also noticed a slight hesitation after issuing the `efibootmgr` command as if it was really writing something into a NVRAM.  It wasn't there before.  When modifying boot order, the command also executes instantly, no hesitation, and although `efibootmgr` list reflects the change, it's gone after reboot.

Getting chain loading to work would be fantastic!  That would definitely make life easier for lots of people no matter how poor their UEFI implementation.  Not to mention a much quicker boot.  It was suggested in #18 early on.  I hope to see a new momentum in `sedutil` development.

**Comment by r0m30** [comment]
This seems to be a bios issue, sedutil currently does nothing to actively set/change the boot order.  I have two test systems and neither has this issue.  

Yes, the UEFI equivalent of chain loading would be great but will require a lot of time to research.
