### ISSUE TITLE
Please update/clarify license text in Common/Dta*Dump* files

### ISSUE THREAD

**Issue by cranderson** [Drive-Trust-Alliance/sedutil#145]
These files have a mix of BSD-style and GPLv3+ license text in them.  Can you please clarify which license applies and update the files to have the appropriate license text in them?

DtaAnnotatedDump.cpp
DtaAnnotatedDump.h
DtaHexDump.cpp
DtaHexDump.h

Thanks.

**Comment by r0m30** [comment]
The code is GPLv3+  I'll fix it.

**Comment by r0m30** [comment]
fixed in 1.15.1
