### ISSUE TITLE
PSID Reverts fails with error "method status code NOT_AUTHORIZED"

### ISSUE THREAD

**Issue by OumarThielo** [Drive-Trust-Alliance/sedutil#147]
Hi,

I get following error when trying to do "PSID Revert" with sedutil tool.
The PSID seems to be correct so I don`t understand why the command is returning with 
"NOT_AUTHORIZED" error status.

./sedutil-cli --yesIreallywanttoERASEALmydatausingthePSID 44TZKAN71MQUF4TMJ96973BJZT9U32G8 /dev/sds
------------------------------------------------------------------
01:36:19.214 DBG1: Entering DtaSession::methodStatus()
- 01:36:19.214 ERR : method status code NOT_AUTHORIZED
- 01:36:19.214 DBG1: Entering  DtaResponse::getTokenCount()

As result the drive (/dev/sds) is still locked
./sedutil-cli --query /dev/sds
---------------------------------------------------------------
Locking function (0x0002)
Locked = Y, LockingEnabled = Y, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y

Im using a TOSHIBA SED disk drive
---------------------------------------------------------------
endor:               TOSHIBA
Product:              PX04SMQ160
Revision:             0802
User Capacity:        1,600,321,314,816 bytes [1.60 TB]
Logical block size:   512 bytes
Physical block size:  4096 bytes

[revertlog3.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/1006316/revertlog3.txt)

Best Regards,

**Comment by kylemanna** [comment]
According to the [PSID Revert wiki](https://github.com/Drive-Trust-Alliance/sedutil/wiki/PSID-Revert) the `NOT_AUTHORIZED` status means PSID is likely entered incorrectly:

> If you get a message that says NOT_AUTHORIZED you entered the PSID incorrectly. If it doesn’t work please execute the command in step 3 with a -vvvvv (5 v’s) as the first option and redirect the output to a file and open an issue on GitHub.

Did you double check your PSID?  If it's correct, then perhaps it's a bug.

**Comment by r0m30** [comment]
@OumarThielo the response that @kylemanna gave is exactly what I would have given, did you get this to work?
