### ISSUE TITLE
Does not compile on Linux/ARM

### ISSUE THREAD

**Issue by thesourcerer8** [Drive-Trust-Alliance/sedutil#148]
The code does not want to compile on ARMv7 Processor rev 10 (v7l) on Debian 4.9.2
To make it compile, the -m32 has to be removed from the compiler flags in the Makefile, and the include/uapi/linux/nvme_ioctl.h needs to be #include'd from DtaDevLinuxNvme.cpp

**Comment by r0m30** [comment]
I've never even tried to compile this for ARM.  What platform are you using?  I've only looked at the RPi, there is no SATA or NVMe interface, and the USB drivers don't support UASP so there isn't a way to execute the ioctls.  That said, the newest release has an autotools build for sedutil-cli and linuxpba which doesn't assume an architecture and the NVMe include issue should be resolved too.

**Comment by thesourcerer8** [comment]
I am using Novena with a NXP iMX.6, which has a SATA interface. Thanks!

**Comment by r0m30** [comment]
I'd be interested in hearing if you get this working on ARM,

**Comment by thesourcerer8** [comment]
Yes, it would be working on ARM:

root@novena# head /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 10 (v7l)
BogoMIPS	: 3.00
Features	: half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0xc09
CPU revision	: 10

root@novena# sedutil-cli -v --scan
- 12:44:17.941 DBG : Log level set to DBG 
- 12:44:17.941 DBG : sedutil version : 1.12-12-gc98f768-dirty
- 12:44:17.941 DBG : Performing diskScan() 

Scanning for Opal compliant disks
/dev/sda 12  Samsung SSD 840 EVO 250GB                EXT0CB6Q
No more disks present ending scan
root@novena# sedutil-cli -v --query /dev/sda
- 12:44:21.460 DBG : Log level set to DBG 
- 12:44:21.460 DBG : sedutil version : 1.12-12-gc98f768-dirty
- 12:44:21.493 DBG : Performing diskquery() on /dev/sda

/dev/sda ATA Samsung SSD 840 EVO 250GB                EXT0CB6Q S1DFNEA*********A     
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = N, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = N, Alignment Granularity = 1 (512), Logical Block size = 512, Lowest Aligned LBA = 0
Opal V1.0 function (0x0200)
Base comID = 0x1004, comIDs = 1
DataStore function (0x0202)
    Max Tables = 9, Max Size Tables = 10485760, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x1004, Initial PIN = 0x0, Reverted PIN = 0x0, comIDs = 1
    Locking Admins = 4, Locking Users = 9, Range Crossing = N

TPer Properties: 
  MaxComPacketSize = 66048  MaxResponseComPacketSize = 66048
  MaxPacketSize = 66028  MaxIndTokenSize = 65992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxAuthentications = 5
  MaxSessions = 1  MaxTransactionLimit = 1  DefSessionTimeout = 0

Host Properties: 
  MaxComPacketSize = 2048  MaxResponseComPacketSize = 2048
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1
root@novena#

**Comment by r0m30** [comment]
Great! 12+ commits, what were the things that need to be accommodated?
