### ISSUE TITLE
Missing script and/or documentation

### ISSUE THREAD

**Issue by juliandroid** [Drive-Trust-Alliance/sedutil#15]
According to the wiki, there should be a file called **script-to-build-pba** inside images directory:

> cd /dir/containing/sedutil-cli cd images sudo ./script-to-build-pba

Unfortunately this file is missing, so I have to do a wild guess which script to build first, in order to match the "**-f**" exists checks.

Can you please (re)introduce the missing file - it will be a lot easier to build the sedutil (under Linux)?

On additional thing, regarding the documentation - I had to run multiple times the build process over and over again till I install all prerequisites that were missing on my PC.

Under Arch Linux, except for the mandatory **base-devel** package I had to install the following: 

> nasm asciidoc rsync cpio

It would be great if you list in the documentation, the pre-required builder tools - at least for one of the major distributions, like Ubuntu. I don't need to be Arch Linux.

**Comment by r0m30** [comment]
There are three scripts in the images that build different flavors of PBA images, they all start with build.
buildUEFI64 builds a linux based BPA for 64bit UEFI systems.
buildbiospba builds the syslinux based pba for BIOS machines.
buildbiosLinux builds a linux base PBA for bios machines.

I'll fo a clean build the next time there is a release to see what files are missing

**Comment by juliandroid** [comment]
Basically, the idea is to choose and call some of the **build*** scripts and that equals to "sudo ./script-to-build-pba" line in the documentation?

My confusion comes from the fact that this is not enough for successful build. For example I need to run first **getresources**. Now if I call **buildrescue** it will fail again because I didn't realized that I have to build sedutil/linux/CLI first.

**Comment by r0m30** [comment]
Yes, that's the gist of it.  I guess I assumed that you would have built the base program before you tried to build an image that includes it.  The same is true of the UEFI/linux PBA scripts, you have to build LinuxPBA before you build the disk image.

As I said in #16 I'll do a clean build the next time I build a release and do what I can to make to process clearer.

**Comment by r0m30** [comment]
Documentation updated in 1.11
