### ISSUE TITLE
Little help about configuring sedutil

### ISSUE THREAD

**Issue by igonni** [Drive-Trust-Alliance/sedutil#150]
Hi,i m trying to psid revert samsung m2 ssd,im new to this so i need just few tips how to execute cli commands,i did all necessary steps for install:

1. Visual Studio 2013 Community Edition (minimum).
2. Git command-line client for Windows. [ http://git-scm.com/download/win ]
3. To generate the version.h file correctly, you will need to adjust the PowerShell security setting for *external* script invocations. 
   The "least insecure" setting that'll allow it to work without setting up local script signing is 'remotesigned'.
   Run a standard command prompt (not powershell) as Administrator and execute the following command (adjusting path as necessary): 
     c:\windows\syswow64\WindowsPowerShell\v1.0\powershell.exe -command set-executionpolicy remotesigned

so basicly im stuck when i open git bash and executing 1st command  (sedutil-cli -–scan)
im getting bad command or no directory and sometimes just nothing happen,i have downloaded 2 repositories sedutil master and sedutil,unpack them and place them in root of the C disk

**Comment by kylemanna** [comment]
It's probably easier to use the recovery image on a USB flash drive if you can.  That way you can avoid having to compile the code, especially in Windows. :)

Take a peek at [Test the Rescue system wiki page](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Test-the-Rescue-system).  Once you have that booting from a flash drive you can follow the [PSID Revert wiki](https://github.com/Drive-Trust-Alliance/sedutil/wiki/PSID-Revert)

**Comment by igonni** [comment]
Cool will try,i just dont understand why i need to print out encrypting details page? 
And when boot from rescue image from flash,im restarting pc and then choosing rescue drive  right?

**Comment by igonni** [comment]
I got error : DtaDevOS::init ERROR -unknown drive type segmentation fault

**Comment by igonni** [comment]
1)Sedutil-cli --scan

/dev/sda No samsung MZNLN512HCJ
/dev/sdb


2) Sedutil-cli --query \\.\PhysicalDrìve?

error : DtaDevOS::init ERROR -unknown drive type segmentation fault

**Comment by kylemanna** [comment]
> i just dont understand why i need to print out encrypting details page?

I assume you're reading that on the [Test the Rescue system](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Test-the-Rescue-system) page?  If so, it's suggesting your print it so that you can use it as reference while your system is booted off the Rescue image and doesn't have access to the web.  If you have another computer (or cellphone) you can always reference the page on that device.

> error : DtaDevOS::init ERROR -unknown drive type segmentation fault

Assuming you ran this on the Rescue image, it appears to be a bug.  You specified the Windows convention for labeling drives (`\.\PhysicalDrìve?`) when you're running the Linux Rescue image.  Try running these:

    sedutil --query /dev/sda
    sedutil --query /dev/sdb

**Comment by igonni** [comment]
Yea im trying to execute from rescue disk
In adition to psid disk i need to run this commands? So im not sure what to execute now
Yes im trying to execute commands from psid revert wiki you send me in the link


sedutil-cli -–scan

sedutil-cli -–query \\.\PhysicalDrive?

sedutil-cli -–yesIreallywanttoERASEALLmydatausingthePSID <YOURPSID> \\.\PhysicalDrive?

**Comment by igonni** [comment]
"Once you have that booting from a flash drive you can follow the PSID Revert wiki"

I have boot from flash and i am follow the psid revert wiki

**Comment by kylemanna** [comment]
You are using the the wrong syntax to reference the drives.  In Linux (the Rescue image), SATA and SCSI drives appear as `/dev/sdX`, but in Windows the convention is `\.\PhysicalDrive?`.  The `sedutil-cli --scan` will tell you the names of the block devices it detects.

**Comment by igonni** [comment]
Ok so the second comand should be like this

sedutil-cli -–query \.\dev\sda?

**Comment by kylemanna** [comment]
Closer, try copying the paths given by `sedutil --scan`

Instead try:

    sedutil --query /dev/sda

**Comment by igonni** [comment]
This command
 sedutil --query /dev/sda
 I got now sedutil:not found

**Comment by kylemanna** [comment]
sedutil-cli --query /dev/sda

**Comment by igonni** [comment]
allready tried that command too : )
samo not found : (

**Comment by igonni** [comment]
This command
 sedutil --query /dev/sda
 I got now sedutil:not found

**Comment by cristim** [comment]
it's `sedutil-cli`, not just `sedutil` and it should work, but only assuming the file is in one of the directories listed in your PATH environment variable and has the executable bit set in its permissions.

**Comment by igonni** [comment]
im executing these commands under linux rescue disk,not sure why im getting sedutil:not found,im getting good response from sedutil-cli -–scan command its reading drives normaly

**Comment by cristim** [comment]
@igonni  Maybe because the `sedutil-cli` is the only binary.

There's no `sedutil` binary, that was just a mistake in the instructions above. But the tab completion should have filled the rest.

**Comment by igonni** [comment]
Ok so how commands should look like in my case,i want to psid revert drive under linux rescue disk,because under windows i cant do it,can you write down here how excatly i should execute second and third command for psid revert,drive i want to psid is labeled sda

**Comment by igonni** [comment]
When i execute sedutil-cli --scan
Im getting
/dev/sda No SAMSUNG (MODEL)
/dev/sdb

When i execute 
Sedutil-cli query/dev/sda
Im getting
ERR : invalid command line argument --query/dev/sda

**Comment by r0m30** [comment]
The segfault is a bug.

**Comment by r0m30** [comment]
The segfault should be fixed it 1.15.1.

**Comment by Defozo** [comment]
I have a similar problem. When will be the 1.15.1 released?

**Comment by sololin24** [comment]
Facing similar challenges with mine toi

**Comment by sololin24** [comment]
The /dev/ not showing sda but /dev/nvme0 what can I do please

**Comment by Blacklands** [comment]
> The /dev/ not showing sda but /dev/nvme0 what can I do please

That's just because you have an NVME drive instead of a SATA drive. `sd[x]` is used for SATA drives (among others, I think USB drives too?) in Linux. See e.g. [here on superuser.com](https://superuser.com/q/1449499/655770).

You can proceed with all the instructions in the wiki and other guides as normal, just replace `/dev/sda` with `/dev/nvme0` and so on.
