### ISSUE TITLE
Protocol for issuing a different password to a secondary drive with ability to unlock it?

### ISSUE THREAD

**Issue by DrEmpiricism** [Drive-Trust-Alliance/sedutil#151]
I tossed sedutil on a friend's laptop since he just got a new Samsung SSD with the Opal 2 SSC and it works fine (no surprises there); however, he also has a secondary drive he's using as a data drive which is also a SSD utilizing the Opal 2 SSC (it's a Seagate Secure, model #ST500LM024).

Though it seems secondary drives must have identical passwords as the primary boot drive in order for them to be able to be unlocked, as I'm unaware of sedutil having an unlock command right from its command-line.  I'm able to lock it like the boot drive, but cannot unlock it if I issue it a different password.  I've toyed around very minimally with it, though, so forgive me if this is a ridiculous question.

**Comment by kylemanna** [comment]
> I'm unaware of sedutil having an unlock command right from its command-line. I'm able to lock it like the boot drive, but cannot unlock it if I issue it a different password.
 
Have you tried the `setMBRDone` option for `sedutil` for the second drive after the system has booted?  I think it will switch the drive in and out of shadow mode.

See [command syntax](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Command-Syntax) and [Encrypting your drive](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive) for details.

**Comment by r0m30** [comment]
While there is no "unlock" command you can use the same primitives that the PBA uses.
--setMBRdone on {password} {drive}
--setLockingRange 0 RW {password} {drive}
will unlock the drive.
