### ISSUE TITLE
[NVMe Samsung PM961 or 960 EVO OEM]  is not detected and PBA does't find it.

### ISSUE THREAD

**Issue by alexis57** [Drive-Trust-Alliance/sedutil#155]
Hi guys,
I open a new issue for my case not to disturb current conversations.

I have a Thinkpad T470s with the Samsung PM961 (I read somewhere it is the 960 EVO in the OEM version), it is supposed to be OPAL2.0.

 - I used the repository of **Kylemanna** (forked from **jojolepirate**): https://github.com/kylemanna/sedutil/releases
 - `Secure boot` is disabled.
 - `Boot option` is set on `Both` (UEFI+ Legacy)
 - I have a trial-boot with 2 linux distributions and Win10 using UEFI (64bits? distr + win10 are 64b).

# **1. Using Rescue**
I flashed an usb drive with `Rescue-1.12-nvmepba-docker.img.gz` and I booted on it.
- `sedutil-cli --scan` shows only my usb `/dev/sda`.

- `sedutil-cli --query /dev/nvme0n1` gives:

```
/dev/nvme0n1 OTHER SAMSUNG MZVLW512HMJP-000L7               6L7QCX*7 S359NX0J312***      
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = N, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = Y, Alignment Granularity = 8 (4096), Logical Block size = 512, Lowest Aligned LBA = 0
DataStore function (0x0202)
    Max Tables = 9, Max Size Tables = 10485760, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x1004, Initial PIN = 0x0, Reverted PIN = 0x0, comIDs = 1
    Locking Admins = 4, Locking Users = 9, Range Crossing = N

TPer Properties: 
  MaxComPacketSize = 66048  MaxResponseComPacketSize = 66048
  MaxPacketSize = 66028  MaxIndTokenSize = 65540  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxAuthentications = 5
  MaxSessions = 1  MaxTransactionLimit = 1  DefSessionTimeout = 0

Host Properties: 
  MaxComPacketSize = 2048  MaxResponseComPacketSize = 2048
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1
```
I didn't want to go further since the scan is supposed to have found my NVMe drive.

# **2. Using PBA**
I flashed an usb drive with `UEFI64_Release-1.12-nvmepba-docker.img.gz` and I booted on it.
It asks me to enter a pass phrase, I enter random pass phrase and then the laptop reboots 2sec later.

**edit: I'll try with `UEFI64_Debug-1.12-nvmepba-docker.img.gz`**

Is it the expected behavior ?

For now, I don't really care about S3 sleep, I always turn off my laptop.

This `sedutil` tool is a really great program if I can make it working. Good job all of you !
Thanks !

**Comment by cristim** [comment]
If the locking/unlocking works the drive should be locked before entering the password in the PBA, and unlocked after the PBA reboots the computer.

If you had an OS installed before first locking it, it should just boot when unlocked, otherwise 
you can boot from an USB stick after the PBA reboot and install the OS on the unlocked drive.

**Comment by alexis57** [comment]
Hi cristim,
Thank you for your reply.
I didn't lock yet, I just want to know if my SSD is supported.
 - As said, I have 3 OSes already installed in my drive.
 - What is not really clear is the Locking SP (what means SP ?) and Locking Range. What is a Range ?
 - I read in a pdf of the TSG we need to take the ownership first. Why it's not written in the wiki ? `sedutil-cli takeownership password device`

The wiki is pretty unclear, what does `initialsetup` (take ownership by setting an Admin password ?)
What is the difference between enableMBR and locking a range ?

**Comment by DrEmpiricism** [comment]
https://www.snia.org/sites/default/orig/sdc_archives/2009_presentations/tuesday/JasonCox_Self-Encrypting_Hard_Drives.pdf

**Comment by alexis57** [comment]
Thank you DrEmpiricism, it's more clear now and I read a lot on the TCG website, the Opal specification provides many options for the drive. Quite complete ! Your explanation should be in the wiki.

Another question, is it possible to backup everything in software in case we want to use the drive again quickly but still being able to unlock it if we remember the password some weeks later ? I guess it's not possible since the main key (MEK?!) is stored and not accessible.

**Comment by alexis57** [comment]
I have installed and locked my drive with success but it doesn't boot to my UEFI grub2. I need to stop the boot, go to boot option and select windows or ubuntu.
Should I change something in the PBA in order to boot from the UEFI partition ? (I have trial boot)
Don't really know the bootflow used with the PBA.

**Comment by DrEmpiricism** [comment]
I don't understand entirely what your first post is asking.  Backups are no problems on SEDs, specifically using the Opal SSC for its security protocol.  Re-deploying your backups to a fresh drive, or to the same drive after it's just been formatted, will be no problems.  Likewise, unlocking the drive on another devise is also no problem.  Unlike ATA Enhanced Security passwords (HD passwords), Opal does not use any sort of keyboard scan-codes for the plaintext passwords, as these scan-codes often differ between machines.

MEK and DEK are synonymous with how SEDs function, as they both refer to the key used to do the actual encryption of that user data.  The DEK is likewise encrypted by the KEK which is generated by your password upon initialization of the Opal SSC.

I personally have not used Sedutil on a multi-boot system, so I can't offer much from personal experience, but if you are booting into Grub, you want to load the Linux PBA regardless if Windows is on there or not.

**Comment by alexis57** [comment]
I wasn't clear enough. The drive is locked, encrypted with a password. I don't remember the password, I might retrieve the password later, I don't want to loose my data then from a live usb I `dd if=/dev/nvme0n1 of=image.img` this will copy the encrypted drive to a binary format but there is no way to decrypt this image in software.
I am pretty sure it's not even possible to re-deploy this image into a new drive. (since there is no way to backup the DEK, I guess there is a way to get the KEK generated from my password)
Anyway, now it's more clear, I can go through the code and see what sedutil does.
Thank  you !

**Comment by DrEmpiricism** [comment]
Sorry for the delay in my reply.  It's been a busy few weeks.

If your drive is locked and you forget the password and are unable to access the drive then yes, your data is completely undecipherable and will remain that way.  Moreover, there are a few ways to dump the encrypted data.  I have a very pricey DFL-SRP All-in-One USB 3.0 full data recovery equipment, and I've had some luck actually dumping the DEK blob and gaining access to a locked self-encrypting drive; however, the data is useless more of the time.  On some drives, I have been able to dump the DEK blob and flash a tweaked firmware that will remove the locking range(s).  Then I have reloaded the original DEK blob and after a power-cycle, the drive is not only completely unlocked but the data is decrypted (the DEK continues to encrypt/decrypt as before).  Being able to do this depends on what security is being used to lock the device.  If someone is using the TCG Opal SSC with key management, it's just not happening on Opal 2.0.  Even business laptops that utilize true ATA security where TRUSTED_SEND and TRUSTED_RECEIVE commands are issued to the drive, as well as password salting that incorporates hash values and model numbers into it are extremely secure, and follow FIPS standards.  ThinkPads do this (I have a T470s, too), as well as UEFI Dell Latitudes (I also have an E7470).  With how these devices are specifically designed for encrypting hardware, their security is no joke.

**Comment by alexis57** [comment]
Wow ! I didnt come here for a while, I've just seen the bookmark, opened it and I seen your reply " DrEmpiricism commented 2 minutes ago " if that is not amazing... lol

Don't worry, I didn't have time either, thank you for your useful explanation !

I see... it's really secure, not like a simple software encryption. That's good even if I don't need that much of security. _(just want to be able to encrypt the whole drive in case of loss or theft)_

I don't know why but now the UEFI is working very well. I turn on, enter the password, it reboots and display the grub, as if it's not locked. I am very happy with that ! I can get my dual/triple boot without any problem with only one password. I am gonna remove the PSID sticker, they even couldn't reuse the disk. (I'll keep a copy almost everywhere just in case and set a second password)

Just if you have time, when I enter the pass phrase, it takes time to reboot. Is it because of sedutil/PBA/software or because of the OPAL hardware specification ? I read somewhere it's because of the OPAL implementation and it's more secure because it makes the brute force very slow since we need to wait some seconds between each try.

I am very happy that sedutil works in my T470s !
Don't know how it behaves when I'll get a dead sector or something like that tho. Recover may be more complicated or impossible.

**Comment by r0m30** [comment]
The reboot is done by the PBA.  UEFI doesn't have am MBR that you can load and jump into so "chain loading" in UEFI is much more complicated.

Im going to close this since you say you have it working.

**Comment by maenpaa24** [comment]
Hi! I have almost the same problem that @alexis57 stated at the title of this thread but I can not see the answer here. Sedutil does see my samsung SAMSUNG MZVLW1T0HMLH-000L2 but it says that it is not opal compliant. However, as far as I know it is opal compliant, does anyone know how to fix this? Otherwise, how did you solve the problem stated in this thread? It may help me to solve mine.

Thank you.

**Comment by r0m30** [comment]
I'm assuming you're using Windows.  The simple answer is that the only NVMe ioctl that I have been able to get working so far is Identify so when the scan runs the basic drive info is all I can get.  NVMe is fully supported in Linux so if you are a windows user you will need to set up the drive from the rescue system.  See [this wiki entry](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive) for instructions.

**Comment by maenpaa24** [comment]
Oh!  Sorry I forgot to tell you that I am using ubuntu 16.04. I have also boot the rescue image for 64bits from a pendrive and in both cases it says that it does not support opal, I mean the drive is detected in both cases (ubuntu and rescue img) but they always say that is not opal compliant. It is a lenovo miix 720. I think it must be that exactly this model of samsung pm961 mzvlw... is not opal compliant, but as far as I read on the internet it should be.

**Comment by r0m30** [comment]
OEM drives can be tricky, the manufacture will drop features to shave a few dollars off the BOM.  Looking at the Samsung site I don't see that they say OPAL, TCG or encryption on the page for your drive.  They also don't list what the numbers after the dash mean.  The only thing I can suggest is that if the laptop is easy to open you might have a look at the drive, if it's OPAL then it should have a 32 character PSID printed on the label.

**Comment by maenpaa24** [comment]
Thank you very much for your support! I think I will return it and buy one which is guaranteed to be opal compliant by the manufacturer.

**Comment by maenpaa24** [comment]
Hi @r0m30 ! I would like to ask you a question. If an ssd has a PSID number on its label, does it mean that it is OPAL compliant? And if it is it will be OPAL 2, won't it? Because OPAL 1 does not support erasing the drive with the PSID number, does it? Thanks.

**Comment by r0m30** [comment]
@maenpaa24 Unfortunatly the answer is not as simple as it should be.  Some vendors added PSID support before it was finalized and they also backported the functionality to OPAL 1 drives and extended it to Enterprise drives as well.

**Comment by oom-is** [comment]
In case anyone comes to this (old, closed) issue report later and has similar questions to @maenpaa24 - I know of at least one drive (Seagate [ST1000LM035](https://www.seagate.com/www-content/datasheets/pdfs/mobile-hddDS1861-2-1603-en_AS.pdf)) that has a PSID on the label but does not claim or contain TCG support for Opal/SED functions.  This is apparently intentional - the drive *DOES* support "Seagate Secure Erase" and will allow the PSID to erase all data, but the drive does not actually provide TCG Opal functions to allow drive encryption, management/PBA, etc.

If you think you can buy a drive that has a PSID on the label and get TCG {Opal 2, Enterprise} support the answer is "definitely maybe".

**Comment by brendanhoar** [comment]
On the flip: if it doesn't have a PSID on the label, it's definitely not going to support TCG OPAL...and if appears to, run far far away.

[Also: <grumbles about the firmware running on the MSATA boards Samsung T3 and T5 USB 3.0 portable drives, in particular, the 2TB ones.>]
