### ISSUE TITLE
Can the OPAL PBA locked drive be unlocked on another PC?

### ISSUE THREAD

**Issue by JaBoMa** [Drive-Trust-Alliance/sedutil#156]
Let's assume that my PC gets damaged. Can I move out its locked PBA Win7 bootable Samsung 840 EVO to another PC, e.g. of different architecture, attach it via the eSATA or USB enclosure, and use the USB stick with the Rescue System to unlock it and/or to turn the locking off, not loosing its contents?
 Since the password is stored within the locked disk, it seems to be possible. The question is: does the sedutil-cli hash the password just depending on the drive Serial Number, or also depending on some of the original PC architecture details (i.e. on its Master Board SN or BIOS)?

I apologize, if that question was already answered, but I did not notify the issue.

**Comment by gomoku** [comment]
Hello, I've just replaced my MOBO + CPU, and I've had no problems unlocking my ssd, so the answer is: yes, it's possible to move the locked ssd among other computers.

**Comment by JaBoMa** [comment]
Thanks a lot, Gomoku, for your comment.

I'll keep this issue open for some time yet. Maybe someone else has different experience or knowledge. Or, maybe, I will try myself to unlock the SED that I will remove from my laptop and then will attach to another one.

**Comment by JaBoMa** [comment]
zikann in thread #114 wrote:

> "Finally I made a last try and attached the drive by a USB adapter to another Windows 10 64bit and tried to change the password to the old one password and it worked!."

This proves that " yes, it's possible to move a locked SSD among other computers."
