### ISSUE TITLE
PBA image not loading in USB nor in SSD

### ISSUE THREAD

**Issue by delsi-OC** [Drive-Trust-Alliance/sedutil#158]
I cannot insert the unlocking password on my drive because the PBA stucks right after loading bzImage and rootfs.cpio.xz...

MY RIG:
Lenovo ThinkPad T420 (BIOS updated to latest version)
Samsung 850 EVO 250GB

Output at boot:
Loading bzImage... ok
Loading rootfs.cpio.xz... ok
[NOT BLINKING CURSOR]

**Comment by cristim** [comment]
Is the system perhaps hanging or in a kernel panic?

On my Dell e7270 laptop I consistently get kernel panic apparently due to the Intel graphics card driver when the laptop is docked into my docking station.

**Comment by delsi-OC** [comment]
It just stays frozen without any other output until I hard shutdown (5 sec power button).
Anyway I don't use the docking station so i don't think the issue is related.

**Comment by cristim** [comment]
Are any of the keyboard LEDs blinking continuously?

**Comment by delsi-OC** [comment]
Nope. It just freezes, the only way out is to forcefully power down the laptop.

**Comment by r0m30** [comment]
Give the new version a try, if that doesn't work edit the syslinx.cfg (in EFI/boot/) or extlinux.cfg (in boot/extlinux) and change the loglevel to 9, this will spew out messages until the kernel panics.
