### ISSUE TITLE
conf file not up-to-date; redundant option for fdisk in buildbiospba

### ISSUE THREAD

**Issue by juliandroid** [Drive-Trust-Alliance/sedutil#16]
In the **conf** file I had to fix the TINYCORE to **Core-current.iso** because http://distro.ibiblio.org/tinycorelinux/6.x/x86/ doesn't contain the hard-coded version anymore (maybe you can take the old one from the "archive" directory or use the current.iso).

The other problem I have is maybe due to different versions of the fdisk. On my machine 
> fdisk -v
> fdisk from util-linux 2.27.1

skips one of the steps (might be harmless):

> ~/msed/sedutil/images/biospba$ sudo fdisk -C 10 biospba-1.10-dirty.img
> 
> Welcome to fdisk (util-linux 2.27.1).
> Changes will remain in memory only, until you decide to write them.
> Be careful before using the write command.
> 
> Device does not contain a recognized partition table.
> Created a new DOS disklabel with disk identifier 0xa072777f.
> 
> Command (m for help): h
> 
> Command (m for help): o
> 
> Created a new DOS disklabel with disk identifier 0x389aeee2.
> 
> Command (m for help): n
> Partition type
>    p   primary (0 primary, 0 extended, 4 free)
>    e   extended (container for logical partitions)
> Select (default p): p
> Partition number (1-4, default 1): 1
> First sector (1-2047, default 1): 63
> Last sector, +sectors or +size{K,M,G,T,P} (63-2047, default 2047): 
> 
> Created a new partition 1 of type 'Linux' and of size 992.5 KiB.
> 
> Command (m for help): a
> Selected partition 1
> The bootable flag on partition 1 is enabled now.
> 
> **Command (m for help): 1**
> **1: unknown command**
> 
> Command (m for help): t
> 
> Selected partition 1
> Partition type (type L to list all types): b
> Changed type of partition 'Linux' to 'W95 FAT32'.
> 
> Command (m for help): w
> The partition table has been altered.
> Syncing disks.

Obviously the "1" command is not recognized in that context!

Edit: I see the **same** issue with **buildrescue** - it seems after setting the active partition ("a") you don't need to pass "1"?

**Comment by r0m30** [comment]
The system is set up to use any existing resources if they already exist on your machine, so when tinycore updates their distro I don't see it until I start fresh, and as I said in the other report I'll do that when I build the next release.  I'll also take a look at the doc to see if I can make it clearer.  I sometimes assume that the reader knows more than they can be reasonably expected to know when they are new to the project.  

I'm using Ubuntu 14.x to build on and I have fdisk v 2.20.1 from their standard package system.  I don't know if they changed the command sequence in 2.27 but it looks like it :-(

That said I know that there are a couple of distros packaging the software, so it can be built from what is there.

**Comment by r0m30** [comment]
Conf updated in 1.11,  this is probably going to be an ongoing issue as I don't do a new release every time TinyCore does.  It may be time to explore using buildroot for the rescue image in addition to the PBA images.  

The fdisk command works fine in Ubuntu.
