### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by AloeG** [Drive-Trust-Alliance/sedutil#162]
**Wiki page:**
https://github.com/Drive-Trust-Alliance/sedutil/wiki/FAQ

**Content:**
To keep the code as uncomplicated as possible sedutil uses the minimum buffer size defined in the OPAL SSCs even _it_ the drive is capable of using larger buffers. Smaller buffers mean more transfer operations. The higher number of operations combined with the long operation time above means slow PBA loading.

**Solution:**
Change "it" to "if"

**Comment by r0m30** [comment]
Thanks, there are probably more, documentation isn't my favorite part of coding.
This was addressed in V1.15 so I deleted the entire entry.
