### ISSUE TITLE
Logitech VX Nano mouse not recognized as LinuxPBA v.1.12 reboots after unlocking SED

### ISSUE THREAD

**Issue by JaBoMa** [Drive-Trust-Alliance/sedutil#163]
Logitech Setpoint software does not recognize my VX Nano wireless mouse, if my laptop (HP EliteBook 8540w, Win7 Pro x64, BIOS v.F60) is booted after being powered off, with OPAL SED (Samsung 840 Evo) unlocking using LinuxPBA v.1.12.
If the Locking is turned off, there is no problem. But if OPAL locking is enabled, and there is the second reboot after entering the drive unlocking password, the Setpoint software does not recognize the mouse.
The simplest thing I need to do in order to let this software to see what mouse is used, it is to pull out, and then to reinsert the USB dongle (Logitech receiver), after the OPAL unlocking following reboot, while the BIOS asks me (the second time) for the Power On password.

Can anybody explain me, why this happens, and if there is any way to avoid such scenario?
Best Regards.

**Comment by r0m30** [comment]
The reboot is by design, the pba is not a boot manager so it reboots to the BIOS (UEFI or Legacy) and let's it handle that.

I'm not sure what is going on with your mouse, but it's probably an issue with the Linux kernel config.  Do you know what Linux kernel config is required to support it?

If your laptop does a power cycle as part of it's reboot process then the current PBA design isn't going to work for you.

**Comment by JaBoMa** [comment]
Thank you, r0m30, for your fast response.

I am not familiar with Linux, then I cannot answer your question. And I don't care about the mouse support during the PBA activity. The problem is that after the restart caused by the PBA, it is not properly recognized by the Logitech software working on booted Windows.

All I know that my laptop does not cycle the power during the reboot, because I should not be able to unlock my SED in such case. And if it at least cycled the power to the USB (and not to the hdd), it should be even helpful. I wrote, that when I re-seat the dongle (wireless mouse USB receiver) after the restart caused by the PBA (even before the real MBR starts acting), the mouse is being properly recognized by the Logitech Setpoint s/w for Windows. If the dongle is on its place continuously since power on, and the hdd has to be unlocked (and then there is another restart), the mouse is not recognized after the Windows OS is booted.
It seems that some information, that the dongle contains/obtains upon its power up, is gone during the PBA activity, or during the restart that the PBA causes after unlocking the drive. I have no idea, whether it is caused by PBA software, or by my laptop BIOS during the restart. I have no idea even, if the dongle may have any internal registers, in which it can store the information about itselve, and about the mouse that transmits toward it, or whether such info is stored in some BIOS memory, that is then cleared during restart (but if I restart my laptop, without powering it off, the mouse, if already recognized, it stays recognized after that restart).

Will perform some additional tests using other USB sticks, and using the version 1.15 rescue system, or PBA v1.15 from USB stick, or even biospba from USB stick. Will inform about the results.

This problem is not of kind "solve it, or die". It is just bothering. The mouse, if not recognized properly, still performs its basic functions (cursor moves, base pushbuttons and scrolling wheel work). Just the special functions assigned to particular pushbuttons, and to particular applications, don't work as configured.

Regards.

**Comment by r0m30** [comment]
My best guess, and it is just a guess, is that there is some kernel support missing.  Without that support the kernel probably leaves the mouse in a semi-initialized state.  I don't have any way to test this so I hope your testing can point to the problem.

**Comment by JaBoMa** [comment]
I have seen more cases, described on other websites, that there were problems with the USB HID installation by Windows, that was booted after Linux. But in those cases there was a problem with the port and/or HID device shown by the Device Manager. These problems were caused by Windows.

My case is different. Within the Device Manager everything looks fine. No matter whether the Logitech 
Setpoint software recognizes the mouse, or not (i.e. whether the dongle has been reinserted, or not).
My problem can be tied to Windows, or to Logitech software itself as well, not only to Linux kernel.

I tried to do something that helped to solve the problem described on the mentioned websites, but my BIOS lacks the related settings (like EHCI and XHCI advanced USB modes).

**Comment by alexis57** [comment]
Recompile the PBA without the support of your/any mouse in the kernel, then the kernel wont try any connexion with the mouse. This may work in your case. Worth it to try.

**Comment by JaBoMa** [comment]
Thank you, alexis57, for your comment.
You may be right, but I am the Windows user, not familiar with Linux, and I take the PBA what is available at Wiki -> "Executable Distributions", I don't compile my own ones.
May be, that I will try this solution sometime in the future.
Your advice can be helpful for the others, that exercise similar problem, but they are better skilled in Linux than me.

**Comment by r0m30** [comment]
I took most of the mouse drivers out of the 1.15.1 pba kernel.  I'm not sure if it will help but it's the only thing I could think of that might help.

**Comment by JaBoMa** [comment]
Thank you, r0m30 for your effort, but it did not help. I tried both pba 1.15.1 (BIOS32 and UEFI64) from the USB stick, and there is no change.

Note, that when I have used the old bios_pba_1.10.img from the USB stick, and restarted my PC (by pressing Ctrl-Alt-Del) instead of typing the password another time (in order to avoid another boot of the PBA from the USB, and to start the BIOS MBR boot from the just unlocked drive), the Logitech setpoint behaved as it should do. I did not have to do any tricks, and the Logitech s/w recognized the mouse after the Windows booted up.

**Comment by JaBoMa** [comment]
So, it seems that the biospba-1.10 should solve my problem, but it will not reboot my PC after unlocking the SSD, after it will be loaded as the shadow MBR to my drive. And I definitely prefer the reboot instead of chain load.

I wonder, if I would compile the Linux PBA (1.15) on my PC, would it change anything? Maybe there are some hardware dependencies in Linux core, however? Remember that I am Linux outsider.

**Comment by r0m30** [comment]
Building locally shouldn't have any effect unless there is some obscure bug in GCC.  1.10 is a long time ago, different kernel relase and config.  

You're on of the few who prefers a reboot.

**Comment by JaBoMa** [comment]
Is there any way I could get the LinuxPBARelease-1.10.img or LinuxPBADebug-1.10.img (executable .img, ready to be loaded to USB stick/ssd), in order to check, whether it is the v.1.10 kernel, that works for me, not the "small lean PBA"?

Yes, I prefer that my PC would perform reset after the shadow PBA activity on it, before the proper OS boots up. And also in order to have an opportunity of selection of the desired position from the BIOS boot order, because I sometimes boot from USB stick, or from CD/DVD, with my ssd already unlocked, not only from the ssd MBR.

**Comment by r0m30** [comment]
The exec repo is tagged with the same release numbers as the source code, so if you want a prior release you can select the tag you want in the pull down and then download the file(s) you want.

Here's a direct link https://github.com/Drive-Trust-Alliance/exec/blob/1.10/LINUXPBARelease.img.gz

**Comment by JaBoMa** [comment]
I have switched to another Logitech Mouse (MX Anywhere 2S) with the Unifying Receiver, and the above described problem no longer exists (despite it still exists regarding the VX Nano Mouse). I think that the problem is more related to MS Windows than to the sedutil and/or to the PBA.
Thanks for your concern and for your help.
Regards
