### ISSUE TITLE
debug mode from the LinuxPBA

### ISSUE THREAD

**Issue by nullgraph** [Drive-Trust-Alliance/sedutil#169]
After encrypting my drive, if I type "debug" as the password, there seems to be a debug mode where I can run sedutil-cli commands. What is the intention of this and is how do I turn off this mode? I'm using the BIOS32 PBA image with Linux v1.15 cli. Thanks.

**Comment by r0m30** [comment]
Not sure I understand what you want??  Yes, entering a password of debug will run the PBA and then drop you into a logon prompt so you can look at the stderr output of the PBA and issue sedutil-cli if you need to. There is no way to disable this, why would you want to?

**Comment by nullgraph** [comment]
Let me confirm that I'm doing it right: after encrypting the disk, at the password prompt, I can enter the password "debug", I then see a logon prompt which I can log in with username "root". From here, I can run things like `sedutil-cli --query /dev/nvme0`. Is this normal?

We're shipping these machines with encrypted disks to customers and want to limit them from getting into the PBA. With the prompt, they can run query. There is also no time limit between running commands like `sedutil-cli --setmbrdone on password /dev/sdc` to probe passwords.

**Comment by r0m30** [comment]
Yes, this is normal.  It allows a step by step process to verify that the PBA works (see the [encrypting](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive) page) on a given machine.  Password probing should be slowed down by the drive itself.  There is a trylimit field in the cpin table that should require a power cycle after x number of failed authentication attempts.

**Comment by nullgraph** [comment]
Right, the difference for me is that in sedutil v1.12, you can't do the same thing, so after every wrong guess of password, the system would reboot and you have to wait some time for it to come back to guess again. In v1.15, going into debug mode, you can try a couple of times before you're locked out, but since there's also a drive lock out, it should be sufficient blockage. Thanks for the reply.
