### ISSUE TITLE
buildrescue fails due missing Version.h

### ISSUE THREAD

**Issue by juliandroid** [Drive-Trust-Alliance/sedutil#17]
Since I don't have the build script that build everything, including the **msed/sedutil/linux** I had to do the following to build both Debug and Release versions:

> cd msed/sedutil/linux/CLI
> sudo make all

Unfortunately this journey ended with missing Version.h errors. I did a patch that basically does exactly what is done for "**build**" target in the Makefile.

Unfortunately the "**build**" target builds only Debug target which prevents me of building the entire **buildrescue**. Once I've fixed the **make all**, now I can build the **buildrescue**.

As I've already mentioned on the other bug report - it would be great if you find time to update the documentation about the building of all files. Thanks!

[getversion.patch.zip](https://github.com/Drive-Trust-Alliance/sedutil/files/111443/getversion.patch.zip)

**Comment by r0m30** [comment]
The project is built using the NetBeans IDE.  If you are building from the command line you need to issue a make CONF=<release> to pull in the submakes that they build for the different configurations (32/64 bit and Debug/Release).  If you look in the nbproject folder you will see these files they are in the format Makefile-<conf>.mk  So as an example you would type make CONF=Relase_x86_64 to build the 64bit release version of the software. 

One of the things these make files do is execute a script that builds Version.h from the output of the git describe command.  This ensures that the version that is displayed by the executable is always in sync with the git repo so I can go back and investigate an error at the same level that the person reporting the error is running.

**Comment by juliandroid** [comment]
Yes, you are correct, my mistake. I was building from the command line. If I use:
`make CONF=Release_i686`
then it works fine without need of my patch.
