### ISSUE TITLE
Intel 6000p problem

### ISSUE THREAD

**Issue by nullgraph** [Drive-Trust-Alliance/sedutil#171]
I'm trying to use sedutil to encrypt the Intel 6000p m.2 drive which claims to be OPAL 2.0 compliant. I encrypted the drive without problem but having trouble booting from it, I typed in the password, it reboots and then hangs forever. If I use the debug mode or the rescue disk to run any unlocking command, for example `sedutil-cli --disableLockingRange 0 debug /dev/nvme0`, I get the error "One or more header fields have 0 length". I can run with `-vvvvv` and save the result to a file, but not sure how to get the file out to post it here.

I have another Intel 6000p that I can run sedutil-cli on without encrypting, here is the result of the query command if it's of any help.
[output.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/1265458/output.txt)

Output of scan:
```
Scanning for Opal compliant disks
/dev/nvme0  2  INTEL SSDPEKKF512G7                       PSF104P
No more disks present ending scan
```

**Comment by r0m30** [comment]
What OS are you installing on the drive?  
You say you encrypted the drive OK but your disablelockingrange command still uses the password debug, didn't you change it?

To get the trace file off of the PBA/Rescue system you will need to mount the USB stick and either copy it there or direct the output there.

Every thing I see says that the drive is indeed an OPAL drive.  The problem appears to be either a password issue or an bios boot entry issue.

**Comment by nullgraph** [comment]
Thanks for the quick response. The drive had Ubuntu 16.04 on it, the machine is a NUC6i7KUK.

I gave it a couple more tries today, after typing the password at the prompt, it flashed "Starting OS" and then the screen went blank for several minutes. If I waited long enough, the following message appears:
```
BIOS has detected unsuccessful post attempt(s).
Possible causes include recent changes to BIOS
Performance Options or recent hardware change.
Press 'Y' to enter Setup or 'N' to cancel and attempt to boot with the previous settings.
```
Going with 'N' just rebooted the machine and brought me back to the prompt. Going with 'Y' brought me to the boot menu.

I also tried to put in an incorrect password, it also flashed "Starting OS" (so that's probably the PBA), and the same sequence of events happened as when I typed in the correct password.

I did change the password to "mypassword", the disablelockingrange command I posted was done with both "debug" and "mypassword" to see if there was any difference (there wasn't). I want to get the output to you, but not sure how. For example, using the Rescue drive, I can do `sedutil-cli -vvvvv --query /dev/nvme0 >& output.txt`, and I can see output.txt at /root, but if I reboot the machine with the Rescue drive, the file is no longer there. Is the Rescue drive writeable?

Some more info: upon entering debug mode by typing "debug" at the prompt, it outputs the drive's name and also said "is OPAL Failed"

As mentioned, I have a second drive that I can experiment on, but I would like to not brick it too, I can run sedutil-cli commands on it, and I have a Rescue drive that I can use on it. Let me know if there's any command you want me to try.

Thank you for the great work with sedutil, I've used v1.12 on a Samsung 850 Pro successfully before, glad you're back to the project.

**Comment by nullgraph** [comment]
Another thing I should mention is that I've used the same machine with the Samsung 960 Pro, also an m.2 drive, and that one encrypts/decrypts with no issue. If you want to start a list of supported drives, I can add some data points.

**Comment by ScottyBauer** [comment]
Hey @nullgraph, First your firmware is pretty old. #2 I'm trying to internally find a 6000p  drive to test on for you as well. https://www.intel.com/content/www/us/en/support/memory-and-storage/000017245.html

**Comment by nullgraph** [comment]
@ScottyBauer Thanks! I can upgrade my firmware to the latest ([0049](https://downloadcenter.intel.com/download/26935/NUCs-BIOS-Update-KYSKLi70-86A-?product=89187)) and give it another try.

**Comment by ScottyBauer** [comment]
I would update the drive's firmware too, that's mostly what I was talking about. I have no clue what goes on in BIOS land here at Intel.

**Comment by nullgraph** [comment]
@ScottyBauer I upgraded both the BIOS and the drive firmware, the drive is now at PSF121P. Still encountering the same problem.

**Comment by ScottyBauer** [comment]
Are you able to lock/unlock it normally not on the PBA? So if you setup encryption on a normal Linux machine then lock/unlock some range that works, but the PBA hangs?

**Comment by nullgraph** [comment]
Not sure if I understand you right, but I don't think I can lock/unlock it even not on the PBA, the way I tried this is by using the Rescue drive and issuing locking/unlocking commands. They all gave me the "One or more header fields have 0 length" error.

On the drive that I have not locked, I've done query command with the output below, note the line `Unknown Feature in Discovery 0 response 402`. This is the only hint I have that something is different with the 6000p, I'm not sure if that contributes to the problem.
[output.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/1271073/output.txt)

**Comment by ScottyBauer** [comment]
Do you have any data on the drive, can you revert it and start over? This sounds like a firmware problem -- I unfortunately do _not_ have a 6000p, only 600ps so I can't test here.

**Comment by nullgraph** [comment]
I'm not concerned about data on the drive, but I've been unable to revert it and start over. Any revert command that I've run so far, in fact, any sedutil-cli command that I've run so far gives me the "One or more header fields have 0 length".

I have another drive that I can try on, but I'm unsure how to proceed so that it won't be bricked like the old one. Any idea?

**Comment by ScottyBauer** [comment]
Even --query on the drive doesn't work?

**Comment by nullgraph** [comment]
`--query` sort of works. It gives me all the usual info but at the end, it says `**** 1 **** Unknown function codes IGNORED`

I'm not sure what that means.

**Comment by nullgraph** [comment]
I don't know how to get the query log off that one, I can run sedutil commands on it either by entering debugging mode or by using the Rescue drive, I'm unable to unlock and boot it into OS. Using the Rescue drive, I can save the output of a command to a text file at /root, but when I mount the Rescue drive to a different machine, the text file is not there. Do you know how to do get the output file out? Otherwise, I guess I can take photos of the output.

**Comment by nullgraph** [comment]
This is what I see from the busted drive with query:
`Locked = Y, LockingEnabled = Y, LockingSupported = Y, MBRDone = N, MBREnabled = Y, MediaEncrypt = Y`

**Comment by ScottyBauer** [comment]
Okay, last thing I can suggest trying is issuing a reset to the controller, and trying again:

# echo 1 > /sys/class/nvme/nvme0/reset_controller
then try and rerun revert / PSID revert

**Comment by nullgraph** [comment]
Ah, that seems to produce a slightly different output, I ran the reset_controller command like you said, then (without rebooting), I ran `sedutil-cli --disablelockingrange 0 mypassword /dev/nvnme0` and I got:
```
method status code SP_BUSY
Session start failed
One or more header fields have 0 length
```

**Comment by ScottyBauer** [comment]
SP_BUSY usually (to my understanding) means a session wasn't terminated properly, and the session is still open. A reboot or a close session will stop close the session and we can move forward. Unfortunately I don't think sed-util has just a close session. Let me code up a modified sed-util real fast that can just close a session.

**Comment by ScottyBauer** [comment]
I don't see how the session could stay open, the code properly deletes the session object(which closes the session) everywhere.

**Comment by r0m30** [comment]
A power cycle, not just a reboot, is usually required to reset a SP_BUSY unless there is a session timeout set by the drive (OPAL doesn't let the host set a session timeout).

SP_BUSY usually indicates a bug somewhere.  I'm not sure where it is in this case. In the early stages of development it wasn't uncommon but I haven't seen or heard of any recently.

**Comment by ScottyBauer** [comment]
I wonder if the reset controller occurred in the middle of command, that's the only way I see we could get SP_BUSY back -- aside from bad firmware.

**Comment by nullgraph** [comment]
This time I shut the machine down completely before running the reset_controller command and it worked, I could unlock the drive now!

**Comment by nullgraph** [comment]
I'll try to re-encrypt the drive again to see what happens. Would you say it was the old firmware of the drive that was the problem?

@ScottyBauer Thank you very much for all your help. We're trying to decide between shipping our appliance with the Samsung 960 or the Intel 6000p, the Samsung drive has an EOL on Feb 2018, so we'd like to figure out how to use the Intel drive.

**Comment by ScottyBauer** [comment]
It's possible flashing the new firmware while the drive had OPAL enabled messed something up internally. Not sure. Try and re-setup the drive and see what happens. If you have further issues with the drive you can email me at scott.bauer (at) intel.com and I can attempt to help.
