### ISSUE TITLE
Cant run any of the executables, tried everything

### ISSUE THREAD

**Issue by Honcho123456** [Drive-Trust-Alliance/sedutil#185]
Have a lenovo tablet with a locked M.2 SSD.
First problem is that I cannot skip password screen with the drive fitted, so I have to boot first , and then put the drive in the slot after post.
it only has UEFI bios so I can only boot via UEFI formated usb sticks.

first issue: none of the linux images works for me, it just hangs after it has shows initrd rootfs.cpio.xz, no error message, it just hangs after "..OK"

same with the Rescue images.

Then I tried putting the windows executable on a windows 10 installation usb. then I use the rescue command promt.
The 32 bit win exe gives me an error message that it is for the incorrect os (or something like this) given that the PC is 64 bit I suspect that is the reason..
the 64 bit exe however runs, but I get no output whatsoever. tried all commands. it just go straight to prompt. 

tried adding the linux version on a live CD but same issue there, no output at all.
When I attach the SSD after boot, it is not discovered via diskpart, so I suspect it needs to be identified via uefi bios prior to use? i was under the impression that it was possible to hot swap the M.2 drives but perhaps not.

I have no other computer with an m.2 slot except this lenovo tablet. I have tested via a M.2 SATA to usb cabinet, but it is not detected properly. it shows up quickly in disk manager but goes away again in a few seconds. it keeps doing this forever it seems.

I also have a M.2 NGFF SSD to 2.5in SATA Adapter, with that one I had some better luck getting the disk identified in Victoria. 
I was also able to run commands via hdparm. but no matter what I try I cannot do a secure erase.

Any tips on a USB bootable media that I can add the linux or windows executable on that might work? 
UEFI bootable media.

**Comment by cristim** [comment]
You may need to manually configure your UEFI boot entry in the system setup menu, I think I also needed to do it first time I started to use the sedutil PBA image.

Browse through the EFI filesysten until you get to the shim binary. I don't remember the exact name but you should be able to recognize it.

**Comment by Honcho123456** [comment]
Hi. I got further yesterday. Sedutil says the drive is not encrypted.. but Victoria says it is.
I see this in hdparm
Security: 
    Master password revision code = 65534
        supported
        enabled
        **locked**
    not frozen
    not expired: security count
        supported: enhanced erase

so it seems locked? tried every possible command in hdparm but I get I/O error . and I can't really access the drive because it will not let me due to the ATA password.
Not sure how to get it unlocked, read somewhere that you only have 2 min to run commands to it before it gets locked (or was it frozen?) but I unplugged drive and reattached it many times while computer was started.
I think Lenovo might do some combination of ATA password used for the OPAL encryption. I am no expert on this so I might got it wrong.

will try this hdparm patch later today
https://jbeekman.nl/blog/2015/03/lenovo-thinkpad-hdd-password/

Also tried this software but it only worked for 32bit OS/or HW?)
https://download.lenovo.com/pccbbs/mobiles/83fd04ww.txt

**Comment by cristim** [comment]
Not sure how it is on Lenovo, on my Dell laptop I reset the ATA password by setting it empty in the system setup menu.

But I would actually prefer to use the ATA password instead of sedutil if I had to choose, it's much more seamless from the user's perspective. NVMe drives are unfortunately only compatible with sedutil, which has some usability limitations, such as lack of support for suspend/sleep.
