### ISSUE TITLE
SED Util to recover from BitLocker not unlocking locking ranges?

### ISSUE THREAD

**Issue by Henning-C** [Drive-Trust-Alliance/sedutil#186]
Hi,
I attempted to use sedutil-cli to recover from a problem, that Windows BitLocker must have lost its "connection" to the drive security mechanism, possibly due to a bug in the Falls Creator update.  My suspicion is, that Bitlocker doesn't recognise or regard the drive's locking range over the C: partition any longer.  Because of that, C: isn't unlocked when booting. And no recovery tool can read anything, not even Windows' own tools (such as 'repair-bde' which would use the recovery password) (which I have of course).  

My environment: Samsung EVO 850 on recent laptop (64 bit UEFI, TPM 2.0); GPT partitioning; the C: partition is Bitlocker 'eDrive' encrypted, so that it utilizes the disk's self-encryption via OPAL and IEEE-1667).

'sedutil-cli --disableLockingRange' is what would have helped here, I thought, but that requires a drive password.
Would you know by chance a way, how to retreive or derive the drive password for sedutil-cli, given a BitLocker recovery password (48 digits)?
Or, is there a another option out there, to get the C: locking range unlocked w/o destroying data?  

Many thanks for any suggestions :)
Henning

**Comment by r0m30** [comment]
I know of no way to derive the drive password from the bitlocker recovery password.  Sorry.  The only thing you can do with sedutil is psid revert the drive and reinstall, of course all you data is gone if you do this.
