### ISSUE TITLE
Sandisk X300. Drive is unrecognizable

### ISSUE THREAD

**Issue by ViterAlex** [Drive-Trust-Alliance/sedutil#189]
I've got a brick during pba unlocking. I did these commands:
```sedutil-cli --initialsetup debug /dev/sdc
sedutil-cli --enablelockingrange 0 debug /dev/sdc
sedutil-cli --setlockingrange 0 lk debug /dev/sdc
sedutil-cli --setmbrdone off debug /dev/sdc
```
I didn't load pba image.
Now my drive cannot be detected neither in Windows no in Sandisk SSD Dashboard. Cannot do PSID Revert
Here is what i got from Rescue System
![img_20171115_191534](https://user-images.githubusercontent.com/15142804/32850380-9f0e0f0a-ca3a-11e7-97b5-f4487701d6e5.jpg)
And this is from Sandisk SSD Dashboard PSID Revert:
![img_20171115_181338](https://user-images.githubusercontent.com/15142804/32850434-cb9dedb0-ca3a-11e7-831c-95fb179ad2dd.jpg)
Can I resolve this problem?

**Comment by ViterAlex** [comment]
sedutil for Win output:
```
C:\Users\viter.alex\Downloads\sedutil_WIN\x64\Release>sedutil-cli --scan

Scanning for Opal compliant disks
\\.\PhysicalDrive0 No  KINGSTON SV300S37A120G                   603ABBF0
\\.\PhysicalDrive1 No
No more disks present ending scan

C:\Users\viter.alex\Downloads\sedutil_WIN\x64\Release>sedutil-cli.exe --query \\.\PhysicalDrive1
Invalid or unsupported disk \\.\PhysicalDrive1
```

**Comment by r0m30** [comment]
At the beginning of the thread you locked the drive but didn't load the pba, so you left yourself no way to unlock or boot the drive.   The drive is acting like you mixed AT security and OPAL security, if a complete power cycle doesn't make it recognizable by setutil then I'm not sure what went wrong.
