### ISSUE TITLE
Multiple Hard Drives

### ISSUE THREAD

**Issue by alfechner** [Drive-Trust-Alliance/sedutil#192]
I've two hard drives. Both support OPAL 2.0. I'd like to decrypt both of them on startup. Is that possible using sedutil?

**Comment by tantrev** [comment]
I, too, would like to know the answer to this question.

**Comment by dlanghorne0428** [comment]
I was trying to make a two-drive system work, but my 2nd drive is a Crucial MX500 that I am unable to put into the lock state (issue #198).  

It seems like multiple drives should work, as the PBA on my first drive appears to print a status of all the OPAL drives before it unlocks my boot drive. 

Has anyone been successful decrypting two drives on startup?

**Comment by cristim** [comment]
I have a single drive configuration but multiple drives should work assuming they all can be unlocked with the same password.

**Comment by r0m30** [comment]
I have a two drive setup for my windows environment and unlock both drives during boot/wake from hibernation, so yes it does work if you use the same password for all the drives you want to unlock.
