### ISSUE TITLE
Drive-Trust-Alliance/exec sedutil_Win.zip / sedutil-cli.exe error on execution (Windows 7)

### ISSUE THREAD

**Issue by brendanhoar** [Drive-Trust-Alliance/sedutil#2]
---------------------------
sedutil-cli.exe - System Error
---------------------------
The program can't start because MSVCP140.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------

PS - there's no Issues option in /exec, so I posted in the issues repository for /sedutil.

**Comment by r0m30** [comment]
@brendanhoar   Hi Brendan,
Yep, must be the first VS2015 project you have run on your machine,  You'll need the newest redistributable package from MS.

https://www.microsoft.com/en-us/download/details.aspx?id=48145

Yes, I wanted to keep all the issues on the source repo so I disabled issues on the binary repo.

**Comment by brendanhoar** [comment]
When releases of sedutil are announced, will end users be required to find, download and install the VS 2015 Redistributable package in order to run it? Or will it be included in an installer? :)
