### ISSUE TITLE
Windows build not detecting Samsung Evo 840s (unlocked) 

### ISSUE THREAD

**Issue by vogelfreiheit** [Drive-Trust-Alliance/sedutil#201]
Running with elevated privileges, sedutil is not detecting 840 Evo disks that are presently unlocked. I believe these were OPAL 1? I used the original msed to set them up. The tool reports nothing after scanning.

**Comment by hotchkiss87** [comment]
The 840 EVO does not. The 840 PRO might though, but I do not remember. Samsung did a split between the pro and evo versions a generation or two ago, where one did and the other did not.

**Comment by vogelfreiheit** [comment]
"Does not" what? The 840 EVO *did* work with msed and earlier versions of sedutil. 840s PRO and not PRO, support OPAL. Then again I'm not sure what was your intended answer because you didn't write a full phrase... (I assume a non native English speaker).

**Comment by r0m30** [comment]
The 850 Evo (they never did update the firmware for the PRO( is the first samsung drive that I am aware of that supports OPAL
