### ISSUE TITLE
Can not unlock Crucial SSD devices

### ISSUE THREAD

**Issue by jmcconocha** [Drive-Trust-Alliance/sedutil#205]
Hi,
Any idea why I can not unlock these SSDs? (Crucial MX300)
I am using this command:
sedutil-cli --yesIreallywanttoERASEALLmydatausingthePSID 5848EA13-xxxx-xxxx-xxxx-xxxxxxxxxxxx \\\\.\PhysicalDrive(n)
(Of course, I am using the *full* PSID as printed on the drive and the actual drive number as shown in --scan)
---
Several drives give me this output:
One or more header fields have 0 length
Properties exchange failed
One or more header fields have 0 length
Session start failed rc = 136
One or more header fields have 0 length
EndSession Failed
---

Attached is the -vvvvv log output as well.

Thanks,
Jeff
[revertlog.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/1678866/revertlog.txt)

**Comment by com-quoininc-gmanning** [comment]
The PSID must be 32 characters long.  Try omitting the dashes.

A nice improvement to the program would be to detect that the PSID is the wrong length, and tell the user.  Or even "the user entered a 36 character PSID which has four hyphens so I'll omit those".

**Comment by jmcconocha** [comment]
Yes. It was how I was entering the command. I did finally stumble onto the correct syntax. ;-)
Thanks!
Jeff
