### ISSUE TITLE
Interrupting the PBA flashing leads to inconsistent NVMe OPAL state

### ISSUE THREAD

**Issue by vogelfreiheit** [Drive-Trust-Alliance/sedutil#211]
I have interrupted the flashing of the PBA by accident on one NVMe drive, a 960 model. Now the rest of the locking/unlocking/management functions don't work. I am going to power cycle and see if that solves it, or issue a PSID revert in the worst case scenario...

**Comment by r0m30** [comment]
You didn't update this, I assume that a power cycle fixed it because when you interupt a PBA flash the session is not properly terminated and therefore cannot be restarted.
