### ISSUE TITLE
Crucial MX500. Worth taking a chance?

### ISSUE THREAD

**Issue by scobiehague** [Drive-Trust-Alliance/sedutil#214]
I'm seeing a few [issues](https://github.com/Drive-Trust-Alliance/sedutil/issues/198) with Crucial drives. Will these issues result in bricking the drive if I encounter them, or can I revert the changes? I've just bought an MX500 from my Thinkpad X230 and looking to use sedutils to set a stronger password than the BIOS can set (I don't use Windows).

**Comment by r0m30** [comment]
The only time I've seen a brick is when people try to set both OPAL and ATA passwords.  If you just use OPAL commands at the very worst a power cycle and psid revert should get you back to having a usable, if empty, drive.
