### ISSUE TITLE
Samsung NVMe EVO 960 500GB 3B7QCXE7 Invalid or unsupported disk /win10 pro 64bit

### ISSUE THREAD

**Issue by GithubusMaximus** [Drive-Trust-Alliance/sedutil#215]
Hello

I'm trying to disable OPAL, Revert PSID, disable hardware encryption, set drive back to "ready to enable". When i go to Samsung Magician 5 it shows "Encrypted Drive Enabled", because of that when i attempt to do secure erase it does not work "error 29".

I downloaded sedutil_WIN\x64\Release\sedutil_cli.exe from executable distributions and when i run 

sedutil_cli --scan it shows my EVO as "compilant NO"

any further action will end up with "Invalid or unsupported disk" https://github.com/Drive-Trust-Alliance/sedutil/wiki/PSID-Revert

The drive is not initialised yet (afted diskpart clean). Is that an issue?

**Comment by r0m30** [comment]
NVMe drives can only be configured and managed under Linux.  The current M$ driver doesn't support the security protocol commands as far as I can tell.  It's ambigous in the doc but tests all fail.
