### ISSUE TITLE
Crucial MX200. Error when trying enable locking.

### ISSUE THREAD

**Issue by HardWayProgramer** [Drive-Trust-Alliance/sedutil#216]
After first steps of testing PBA on RESCUE32.img
I try to enable locking on my SSD and I've got this error message.

`sedutil-cli --initialsetup debug /dev/sda`
`method status code AUTHORITY_LOCKED_OUT`
`Session start failed rc = 18`
`One or more header fields have 0 length`
`EndSesion Failed`
`takeOwnership failed`
`Initial setup failed - unable to take ownership`

I don't know what I'm doing wrong. I'll appreciate ever help.

**Comment by r0m30** [comment]
The wiki has info on the most common errors.  Authority locked out means you need to powercycle the drive as you have used an invalid password to many times.  Did you get any not authorized errors?  Is this on a Win10 install (WIn10 takes ownership of OPAL drives during install)?

**Comment by serossi** [comment]
win10 doesnt but cruical comes edrive ready. what ive seen is you need to reset the drive with a PSID revert.
that was it for me

**Comment by Mexx77** [comment]
PSID revert helped me too. No data was actually erased. Made a backup before anyway. thanks!
