### ISSUE TITLE
question: is S3 sleep support for windows even possible?

### ISSUE THREAD

**Issue by elpetak** [Drive-Trust-Alliance/sedutil#218]
I've read through the other issues and patches and pull requests and found that they all discuss (and somewhat fix) the S3 sleep issue for linux. But what about windows?
Is S3 sleep support for windows even possible?

**Comment by elpetak** [comment]
Yes, but Bitlocker only supports Opal with UEFI 2.3.1 and it must have the EFI_STORAGE_SECURITY_COMMAND_PROTOCOL defined. It also needs Win10 pro ($$$).
Right now I'm using sedutil and so far it works great and since hibernating takes seconds I'm not worried about sleep, but I was wondering how did the Winmagic guys did it.

**Comment by r0m30** [comment]
I believe that commercial sleep support is done via a driver.  I'm not even sure of what type of driver windows would require and it's way down on the list of things that need research.
