### ISSUE TITLE
Recommended motherboard which don't erase EFI boot entries ? (not ASUS)

### ISSUE THREAD

**Issue by noguespi** [Drive-Trust-Alliance/sedutil#219]
I have some issues with my ASUS motherboard which erase EFI boot entry at reboot (because the EFI /dev/nvmen1p1 partition disappear after unlocking). I tested various hack from #27 and #103 but without success. 

The encryption and boot process works well but I have to always manually select the boot entry at each reboot which is really painfull. I'm using an m.2 SSD 960 pro, with multiple partitions on it (windows, efi, linux...).

My next attempt will be to put windows partitions on another hard disk and try to setup my EFI partition to /dev/nvmen1p1 and renaming boot.efi files so that the shadowed/locked state and unlocked state of the disk looks nearly the same.

I would like to know if you have good motherboard manufacturer which don't erase my configured EFI boot entries...

**Comment by r0m30** [comment]
I use ASUS, but with a SATA boot drive, so I can't really help, sorry.
