### ISSUE TITLE
PBA images on the rescue image

### ISSUE THREAD

**Issue by juliandroid** [Drive-Trust-Alliance/sedutil#22]
This is more or less feature request if you think that might be helpful to someone.

Currently, if I swap my system drive with OPAL SSD (presumably I'm having only one SATA slot) then the obvious way to test sedutil-cli and install the PBA is by using the rescue image on the USB thumb drive.
Once tested the sedutil and the SSD, you should be able to write the BIOS/UEFI64 PBA on the SSD.

Currently I'm doing something like this:

```
diff --git images/buildrescue images/buildrescue
index 63c972e..4f6b0c4 100755
--- images/buildrescue
+++ images/buildrescue
@@ -4,6 +4,8 @@ set -x
 ## define releases for tools
 . conf
 PROGRAM=../../linux/CLI/dist/Release_i686/GNU-Linux/sedutil-cli
+BIOSPBA=../LINUXPBARelease/LINUXPBARelease-*
+UEFI64PBA=../UEFI64_Release/UEFI64_Release-*
 VERSIONINFO=`git describe --dirty`
 BUILDTYPE=Rescue
 BUILDIMG=${BUILDTYPE}-${VERSIONINFO}.img
@@ -18,7 +20,7 @@ sudo rm -rf ${BUILDTYPE} ; mkdir ${BUILDTYPE} ; cd ${BUILDTYPE}
      -f ${PROGRAM} \
   ] || { echo " prereqs are not available "; exit 1; }
 #
-dd if=/dev/zero of=${BUILDIMG} bs=1M count=15
+dd if=/dev/zero of=${BUILDIMG} bs=1M count=30
 (echo o;echo n;echo p;echo 1;echo "";echo "";echo a;echo 1;echo w) | fdisk -C 100 ${BUILDIMG}
 dd if=../scratch/${SYSLINUX}/bios/mbr/mbr.bin of=${BUILDIMG} count=1 conv=notrunc bs=512
 LOOPDEV=`sudo losetup --show -f -o 1048576 ${BUILDIMG}`
@@ -44,6 +46,21 @@ cd ..
 sudo mkdir -p core/usr/local/sbin/
 sudo unsquashfs -f -li -d core ../scratch/hdparm.tcz
 sudo cp ${PROGRAM} core/usr/local/sbin/
+
+if [ -e ${BIOSPBA} ]
+then
+    sudo mkdir -p core/usr/local/pba
+    zcat ${BIOSPBA} >./LINUXPBARelease.img
+    sudo cp ./LINUXPBARelease.img core/usr/local/pba/
+    rm -f ./LINUXPBARelease.img
+fi
+if [ -e ${UEFI64PBA} ]
+then
+    sudo mkdir -p core/usr/local/pba
+    zcat ${UEFI64PBA} >./UEFI64_Release.img
+    sudo cp ./UEFI64_Release.img core/usr/local/pba/
+    rm -f ./UEFI64_Release.img
+fi
 ## now repackage it
 cd core
 sudo find | sudo cpio -o -H newc | gzip -9 > ../image/boot/core.gz
```

I'm not quite happy with the implementation, but at least I'm guarding against missing images (not yet built).

Also, I'm not sure whether I can use the UEFI64 image to write it with sedutil-cli, since the rescue image boots in BIOS mode?

**Comment by r0m30** [comment]
I've thought about adding the PBA images to the rescue image.  It's a personal pain point that stops me, I write the rescue image to the PBA of my data drive so I always have the rescue system available and writing the PBA is currently painfully slow due to some design choices I made in the beginning. This would probably have to be implemented with a rework of the message buffer size.  

Yes you can write the UEFI image to the PBA even if you have booted in BIOS/CSM mode.

**Comment by juliandroid** [comment]
I've tried today myself to write the PBA on the SSD and it took 10 minutes to complete :(
How complicated is the problem with the buffer size? Do you have any reference to documentation explaining the process of writing PBA? Is there anything special?

**Comment by r0m30** [comment]
It's not special, look at the loadPBA function in (Dta|Msed)DevOpal.cpp.  It's just a standard Trusted Send.   The issue is that when I started writing the code I decided for simplicity I would use the default buffer size so I wouldn't have to do any buffer management.  There is a constant #defined called IO_BUFFER_LENGTH  and it is scattered throughout the code.  To change this first you would need to make certain that nothing breaks if you change this to a variable including looking for places where it is assumed but not referenced (CDBs and Taskfiles) and then you would need to parse the properties to see how large of a buffer the drive will take, change the buffer size and use it in loadPBA().  

Sounds simple right....

**Comment by juliandroid** [comment]
Yep, meanwhile I've spent some time digging.
Correct me if I'm wrong, but what we need is a "Long atom" (up to 16MB) implemented at "DtaCommand::addToken".

I guess the "Medium atom" is of no use for us, since it has very small limit: 2KB.

Source: https://www.trustedcomputinggroup.org/files/static_page_files/B6811067-1D09-3519-ADDAFC18E3A87CB2/Storage_Architecture_Core_Spec_v2_r1-Final.pdf  (pages 35-36).

I assume we can tweak the commandbuffer[IO_BUFFER_LENGTH + IO_BUFFER_ALIGNMENT] and IO_BUFFER_LENGTH respectively to something like 1MB?

Sure, the part of "nothing breaks" is the most important and hard to accomplish ;) The breaking is easy :) That's why I was looking at "Long atom", because I was expecting that there are some limits and restrictions.

**Comment by r0m30** [comment]
The loadPBA function uses addToken( vector uint8_t ) to construct it's own atom so I don't think you would need to add a long atom just modify that code to build the proper token header for a long atom.

1MB is overkill you still have to honor the packetsize the drive will accept (returned in the properties) and the limits of the io bus.  From a sampling the drives that I use 131072 to 17388 bytes is the range that any of them will accept for a packet.  100Kb should be plenty large enough and will reduce the load time by ~100x if the drive will accept that large of a packet.

A few other things you'd want think about. Adding a way to determine how big the command is so you don't pass the full max packet size when you don't have to.  Making sure you don't try to write more than 128M to the shadow table.  The taskfile byte that has the number of 512 byte blocks effectively limits you to a max total transfer of 127.5K (255*512) bytes.

**Comment by juliandroid** [comment]
taskfile byte - not sure I can follow. I've grepped for taskfile and I saw billion of matches :)

Anyway - can you take a look at  94e5887 ? Not sure about memory management (see the new DtaCommand(uint32_t) constructor, calloc() calls and free() at the destructor). I didn't touch c++ for many years. The goal here, with this commit is to fix loadPBA() only, not the general problem with the memory buffer.

Do you think that looks feasible?

**Comment by juliandroid** [comment]
I've tried those changes, but I'm getting cryptic errors :(
First thing that I've tried was:

`sedutil-cli --initialsetup mypwd /dev/sdb`

with the following result:

```
method status code NOT_AUTHORIZED
Session start failed
EndSession Failed
takeOwnership failed
Initial setup failed - unable to take ownership
```

Then I've tried:
`sedutil-cli --loadPBAimage mypwd /usr/local/pba/UEFI64_Release.img /dev/sdb`

and the result:

```
Writing PBA to /dev/sdb
[*                    ] 0- date ERR : Buffer Overrun
```

Running --revertTPer ended with the same NOT_AUTHORIZED error.

While for the --loadPBAimage I was expecting errors, I don't quite understand what I've messed up with the other commands.

My SSD is Samsung 850 Pro and I guess for the "Buffer Overrun" error the problem might be that those 100KB was too optimistic. I'm attaching a screenshot from --query command.

For me is quite painful to swap disks for every test. I hope, when you have time to step in.
![20160220_010721](https://cloud.githubusercontent.com/assets/7766093/13192294/17d7c3fc-d773-11e5-9da4-a594a94a4864.jpg)

**Comment by r0m30** [comment]
I just pushed some code to increase the speed of the load by ~1.9x.  This is the best that I can do at the moment because it doesn't require changes to anything but the loadPBA function.  At some point I hope to get this completely resolved so that a load time isn't an issue.

**Comment by r0m30** [comment]
V1.15 now loads the PBA in under 2 minutes on Samsung and Micron SSDs and the rescue images now include the PBA image files included.
