### ISSUE TITLE
What is the correct order to install the PBA and a Linux OS on an empty drive?

### ISSUE THREAD

**Issue by AlphasCodes** [Drive-Trust-Alliance/sedutil#221]
I'm awaiting an Intel Pro 7600p M.2 NVME SSD that supports TCG Opal 2.0 according to the Intel support. I read all the documentation in this wiki and some related documents in the internet but i still don't know one important information.

What is the correct order to install the PBA and a Linux OS / other OS on an empty drive?

I would use the Rescue Image on a USB stick to setup the PBA.

1.) Install the Linux OS / other OS first then setup the PBA?

or

2.) Setup the PBA first then install the Linux OS / other OS?

I assume it is 1. because the documentation in this wiki and the related documents in the internet do this.

Thank you

**Comment by r0m30** [comment]
It makes no difference, install in whatever order is most convenient for you.  The one advantage if 3 is that you can test and verify the setup before you spend the time installing the OS.
