### ISSUE TITLE
What's the best way to modify the PBA image?

### ISSUE THREAD

**Issue by suilven** [Drive-Trust-Alliance/sedutil#223]
Hi

I'm trying to modify the PBA efi layout to match my Linux efi layout and would appreciate some pointers as to the best way to do this. I'm running Fedora on an ASUS Z270-P motherboard with a Samsung 960 Evo M.2 drive and have followed all the instructions but after locking my drive and rebooting, no bootable disks are found. The problem seems to be the one reported by others  (#180, #194, #213) and the suggested solution is to modify the efi layout on the PBA to match the efi layout in my Linux system (#213). 

I've tried unsuccessfully to mount the PBA image after booting into the rescue system. Is this possible in the stripped down version of Linux used in the rescue system? I've also tried downloading the UEFI image file and can mount that and modify the layout in my full Linux system, but is there a way to move the modified PBA into the rescue image without rebuilding the rescue image from scratch?

Thanks.

**Comment by r0m30** [comment]
The best way I can think of is to mount and change the image on your full system, move it to a separate usb stick from the rescue system, mount the usb stick in the rescue system and load it to the PBA.  The rescue system is based on busybox so you should be able to do anything busybox is capable of but the commands are limited compared to a full distro.

**Comment by suilven** [comment]
Thanks. Your suggested approach works perfectly. I'm still trying to find the correct EFI layout on the PBA to get it all working but that's another problem.
