### ISSUE TITLE
not discovering SED capability of Intel 535 series

### ISSUE THREAD

**Issue by brianjmurrell** [Drive-Trust-Alliance/sedutil#227]
I have what I believe is an Intel 535 series disk which apparently supports SED as far as I have been able to determine, however `sedutil-cli` can't seem to determine that:

```
# sedutil-cli --scan

Scanning for Opal compliant disks
/dev/sda No  INTEL SSDSC2BW480A3L                     LF1i    
/dev/sdb No   
No more disks present ending scan
```

Any ideas?

**Comment by D-Albers** [comment]
The SSDSC2BF480A5L seems to belong to the SSD Pro 2500 series.
The Opal V2.0 function is listed in the datasheet of the 2500 series but not for the 535: 

> Trusted Computing Group* (TCG*) Opal Security Subsystem Class (SSC) Specification Version 2.0 features

The controller of both series seems be the same but the firmware may be different.
The Opal V2.0 option may be one of the sweet extra functions of the Intel Pro 2500 series. Or simple an option to divide the consumer line up from the "pro" line up.

[Datasheet 2500](https://www.intel.com/content/www/us/en/solid-state-drives/ssd-pro-2500-series-sata-specification.html)

**Comment by brianjmurrell** [comment]
Yeah.  I think I was mistaken about this being a 535.

This [page at Intel](https://ark.intel.com/products/66251/Intel-SSD-520-Series-480GB-2_5in-SATA-6Gbs-25nm-MLC?q=SSDSC2BW480A3L) is saying it's a 520 which I don't believe has OPAL.  :-(
