### ISSUE TITLE
Multiple password input on boot

### ISSUE THREAD

**Issue by sdca** [Drive-Trust-Alliance/sedutil#23]
If you have multiple SEDs with different passwords (or locking ranges I assume) and want to unlock them all, you have to wait through a reboot for each one.

Also, if the PBA is on the default boot device and it becomes unlocked it means you have to select another locked drive with the PBA to boot from, if your boot selection menu isn't locked down.

Some workarounds for users to avoid the second problem:
- Enter the default boot device's password last in the sequence
- Add an option in GRUB to chain load the rescue image as a last resort (untested)

**Comment by snow3461** [comment]
@sdca

The PBA is for a booting device. If you have multiple SEDs, obvisouly you're only booting on one, and can unlock the rest later on, via sedutil-cli. No need to unlock them all before actually booting the OS.

**Comment by sdca** [comment]
@snow3461 

sedutil-cli requires raw ATA access and/or root, and possibly represents a less secure way to enter the decryption password.

**Comment by r0m30** [comment]
@sdca 

You have a few options here.  Set the same password for all the drives you need to successfully boot and then you can manually unlock the rest as @snow3461 suggests.  You could also load the rescue image to the shadow table, use sedutil-cli to manually unlock the drives and reboot.

Adding features to the PBA for edge cases will slow down boot for everyone.

**Comment by r0m30** [comment]
@sdca 

The PBA/rescue requires that same access.
