### ISSUE TITLE
PBA support for GPG-encrypted key files

### ISSUE THREAD

**Issue by mkszuba** [Drive-Trust-Alliance/sedutil#234]
Hello,

I wonder, how complicated would it be to extend the PBA images so that it is possible to have the unlock password stored in a GPG-encrypted key file on removable storage? This is something fairly common among the users of software FDE (under both Linux and Windows, as BitLocker does offer some degree of support for this) because not only does it essentially make pre-boot authentication two-factor and facilitates the use of strong drive passwords, but also makes it possible to state in clear conscience that one does not *know* the encryption password.

One potential issue I see here is that unlike software FDE under Linux where the kernel command line can be used for this, it might be complicated to tell the PBA what removable drive to use and what the name of the key file is. Then again, this could be worked around by establishing some conventions regarding the naming etc. of said drive and file (which IIRC is how BitLocker handles it).

**Comment by r0m30** [comment]
corporategoth submitted a pr #86 that should give you a good idea of how difficult/easy what you want to do is.  At this time I have no plans to persue this type of mod.
