### ISSUE TITLE
Can not include "Version.h"

### ISSUE THREAD

**Issue by SzuYuan-Huang** [Drive-Trust-Alliance/sedutil#235]
When i Compiled this object in Visual Studio 2017, the messageBox said Can not open Version.h and GIT_VERSION didn't define! How do I fix it? Thank you!

**Comment by stevekiene** [comment]
Please see the information in the file README_build_win32.txt in the main directory. It explains how to set up Powershell to make a call to Git to get the version and build the file. It generates a #define with the version.

**Comment by brendanhoar** [comment]
Seeing my only github contribution (README_build_win32.txt) referenced above just gave me the warm fuzzies.

**Comment by SzuYuan-Huang** [comment]
Sorry about that! I didn't see (README_build_win32.txt) before! Now I get it!

**Comment by stevekiene** [comment]
Ha! And that was my first comment on github!

**Comment by r0m30** [comment]
Hi @brendanhoar it's weird, when you wrote that up there were probably less than a dozen of us who even knew that msed/sedutil existed.  Hope everything is going well for you.

**Comment by brendanhoar** [comment]
Hi M!

Everything is going well. Now a dad, very little time to tinker. :)

Thought you might find this paper exciting...as it utilizes sedutil in attacks...
PR: https://www.ru.nl/english/news-agenda/news/vm/icis/cyber-security/2018/radboud-university-researchers-discover-security/
Advisory: https://www.ru.nl/publish/pages/909282/advisory.pdf
Paper (the exciting part): https://www.ru.nl/publish/pages/909282/draft-paper.pdf

Brendan
