### ISSUE TITLE
sedutil commands to replace Samsung Magician in configuring an eDrive

### ISSUE THREAD

**Issue by bermanmf** [Drive-Trust-Alliance/sedutil#236]
All--
Lenovo (and probably other PC vendors) are selling Samsung OEM'd OPAL compliant drives, but Samsung Magician does not recognize them (by design) so one can't prep the drives for eDrive.  Samsung SATA EVOs and PCIe EVOs like the 970 are configured (first step) in Magician to eDrive in a step that Samsung says semi-permanently disables standard Class 0 and TCP OPAL encryption.  Then the drives are wiped with a Samsung provided DOS program.  The BIOS in current Lenovo machines handles eDrive fine, if one uses Samsung branded SSDs and preps them with the Magician software.

But you can't use eDrive with the Samsung SSDs that Lenovo provides, because you can't prep them. 

Has anyone used sedutil as a substitute for Samsung Magician or to prep eDrives?  Any ideas what the sedutil commands would be?

Thanks in advance.

[DTA_Contributor_Agreement_v2 18fJun25.pdf](https://github.com/Drive-Trust-Alliance/sedutil/files/2134347/DTA_Contributor_Agreement_v2.18fJun25.pdf)

**Comment by r0m30** [comment]
The way I understand it is that Samsung and M$ have an agreement to use some unassigned bits it the identify response to signal this state.  There is no doc so there is no way for me to duplicate the function.
Sorry

**Comment by bermanmf** [comment]
One last question.  Since I have several un-prepped Samsung EVO drives, is there a sedutil command that will let me read the header section or identity response before Magician creates the eDrive, and then again after Magician has prepped the drive.  Whatever header fields (or bits in the identity response) had changed would be those bits that identify the drive as eDrive.

Then use sedutil to make the appropriate changes.
Or is this a naive approach?

Either way, thank you very much for all this information and for sedutil.
