### ISSUE TITLE
Invalid or unsupported disk

### ISSUE THREAD

**Issue by Gun-neR** [Drive-Trust-Alliance/sedutil#245]
This seems to be a popular issue :)

I have an old M.2 SSD (SK hynix SC300 SATA 256GB) and only recently got a laptop that can actually fit it.  

Windows sees the drive in the Drive Manager, but I cannot initialize, partition or format it, so I think it might be locked?

I am trying to do a PSID Revert, but I can only get so far before running into this error.

Running sedutil on Windows 10 Command Prompt as Administrator...

```
Microsoft Windows [Version 10.0.17134.254]
(c) 2018 Microsoft Corporation. All rights reserved.

c:\Users\Gunner\Desktop>sedutil-cli --scan

Scanning for Opal compliant disks
\\.\PhysicalDrive0 No  ST500LT012-1DG142                        1003YAM1
\\.\PhysicalDrive1 No  SK hynix SC300 SATA 256GB                20121P00
\\.\PhysicalDrive2 No  WDC WD20EADS-00R6B0                      01.00A01
No more disks present ending scan

c:\Users\Gunner\Desktop>sedutil-cli --query \\.\PhysicalDrive1
Invalid or unsupported disk \\.\PhysicalDrive1

c:\Users\Gunner\Desktop>
```
Any idea what I am missing here?

**Comment by BeLZeL** [comment]
Hi,

When you use sedutil-cli --scan, you have this result :

```
\\.\PhysicalDrive1 No
```

So, I think this disk is not compatible with OPAL. When the disk is compatible with OPAL 1/2, you have **12** instead **No**

**Comment by Gun-neR** [comment]
It should be OPAL 2

It is a SK Hynix SD300 M.2

**HFS256G39MND-3520A  DB**

**Comment by Painkilla** [comment]
I use for my normal hard disk hdparm to set the SED password.
hdparm -C /dev/sda tells you if your drive supports SED or not.
hdparm --security-set-pass <password> /dev/sda will do the work and set the password to your drive.

i don´t know if hdparm works with windows, as i use linux, but there are plenty live distros with hdparm on it.

**Comment by Gun-neR** [comment]
I have tried hdparm... but I need to wipe out an existing secured partition, not set a new password.  It didn't seem to have that option and probably would have run into same issue if it did.

I suspect my issue is that the only m.2 slot I have available (aside from being a bit short, so no permanent install anyhow) is meant as a secondary SSD port on my HP Probook, and possibly not correct (needed security option?) for what I am trying to do (PSID Revert)...  Just a guess.

I will simply have to set this old SSD aside until I have proper hardware to test further... I didn't pay much, so no big loss.

**Comment by ShuaiTony** [comment]
Have you solved the problem? I had the same problem with the Samsung 970 EVO, so i hope that you can help me ,thank you.

**Comment by Painkilla** [comment]
Here is how i solved this:
https://github.com/Drive-Trust-Alliance/sedutil/issues/257

**Comment by ShuaiTony** [comment]
Hi Painkilla,
       Here's the problem,when i use  sedutil on Windows 10 (sedutil-cli --scan),the result is **NO**
![image](https://user-images.githubusercontent.com/41790635/52845780-ed478280-3142-11e9-8cbb-34bcad6206ea.png)

but,samsung 970 EVO support TCG OPAL,so,i don't know why?

**Comment by Painkilla** [comment]
Sorry, i only used this on linux and it works there fine. I don't know how this works on windows.

**Comment by ShuaiTony** [comment]
@Painkilla 
Alright,How to use SED under Linux? I have downloaded sedutil-linux, but I don't know how to use it. After Unzipping, it won't run under that path,and I don't know how to send SED cmd.
 ![image](https://user-images.githubusercontent.com/41790635/52847923-790fdd80-3148-11e9-82ac-ba558f044aae.png)

**Comment by Painkilla** [comment]
Apparently you don't know how to install a live Distribution. Activating and working with SED is very DANGEROUS. I would recommend you to work for a while with linux and get used to it before you try to activate SED. Sorry for that, but if i staring to explain here how to install a live distro and all the commands you need, i would abuse this issue. And i don't want to do that.

**Comment by ShuaiTony** [comment]
I already know how to do it. Thank you very much.

**Comment by Gun-neR** [comment]
I never got it to unlock this way (or anyway ;P ) And while I know my SSD is OPAL compliant, I am beginning to suspect the partition lockdown was more the ATA? method... determined by using hdparm.  

However, my SK Hynix brand doesn't have a pre-assigned Master Password (according to them) and even their own software is unable to erase or even do a PSID revert, let alone hdparm or this sedutil.

So I basically gave up. :)

**Comment by rchovan** [comment]
Hi, 
I have Samsung EVO 750 500GB SSD, but can't erase it too. Same issue. I have tried Linux and Windows version too.

**Comment by yinpingSHIH** [comment]
Hi, 

I found all of the NVMe OPAL SSD will show no support OPAL in the sedutil-cli in Windows but support under Linux.

**Comment by Gun-neR** [comment]
Mine is now hanging on my wall along with other various and older PC media - Art?
