### ISSUE TITLE
Support SanDisk X400 M.2 2280 256GB

### ISSUE THREAD

**Issue by thomaszbz** [Drive-Trust-Alliance/sedutil#248]
The SanDisk X400 M.2 2280 is an SSD M.2 drive (_not_ a NVMe drive).

When booting from the rescue image (v1.15.1), `sedutil-cli --scan` reports an unsupported drive. However, the SanDisk X400 M.2 is supposed to support TCG Opal 2.0, according to [specs](https://www.sandisk.com/content/dam/sandisk-main/en_us/assets/resources/enterprise/data-sheets/X400-datasheet-v1-1.pdf). 

The drive came shipped with a recent Dell Latitude 5580 so that I assume it is widely used in Dell's products at least. I also scanned with a 1TB Samsung Evo 960 NVMe M.2 drive which was reported to be TCG Opal compatible and now also is locked/unlocked using the sedutil PBA. The latter only documents that the Latitude 5580 deals well with TCG Opal in principle so that the surrounding hardware is not the issue unless having NVMe and non-NVMe drives makes a difference (which I assume is not the case).

![cimg1122](https://user-images.githubusercontent.com/11200727/45916370-22d29300-be65-11e8-8b8c-b6836c32965a.JPG)

**Comment by dtasupport** [comment]
We did find a Samsung new drive had to be PSID reverted before it could be
noticed as Opal.  In effect, this blocks the attack vector of a bad guy
seizing an un-owned Opal drive which has been known for many years.
However, I do not believe this blocking behavior is approved by any of the
TCG specs yet. Sedutil can be employed for the revert.
regards,

Bob Thibadeau
412 370 1245

**Comment by thomaszbz** [comment]
@dtasupport This issue is about a  SanDisk X400 M.2 2280, not about a Samsung drive.

**Comment by thomaszbz** [comment]
The exact model number of my disk is SD8SN8U-256G-1012 (presumably Dell OEM model). This model number does not occur in the specs provided by SanDisk. I also can't find reliable information somewhere else. I've asked Dell if they know if this model is supposed to support TCG OPAL.

**Comment by aarrtteemm** [comment]
[thomaszbz](/thomaszbz), your SanDisk SSD does not support TCG Opal. They have both SED and Non-SED versions of X400. If you look to the model number table in the provided [specs](https://www.sandisk.com/content/dam/sandisk-main/en_us/assets/resources/enterprise/data-sheets/X400-datasheet-v1-1.pdf), SED models have 'T' at the 4th position in the SKU name (e.g. SD8**T**B8U-128G-1122) while Non-SED has 'S' (e.g. SD8**S**N8U-128G or yours SD8**S**N8U-256G-1012).

**Comment by thomaszbz** [comment]
@aarrtteemm Thank you very much for pointing this out. I had not noticed that in the [specs](https://www.sandisk.com/content/dam/sandisk-main/en_us/assets/resources/enterprise/data-sheets/X400-datasheet-v1-1.pdf) only some of the models are labelled with _SED_. Those are all 2.5 inch drives and mine is a M.2 drive. Anyways, one of the first things I did with that laptop was to replace the 
SanDisk X400 M.2 2280 with a 1 TB Samsung 960 EVO NVMe M.2 drive. The latter runs perfectly fine while sedutil/PBA enable OPAL based hardware encryption.
