### ISSUE TITLE
2 Samsung Nvme Evo 960 with one PBA on a other disk

### ISSUE THREAD

**Issue by Painkilla** [Drive-Trust-Alliance/sedutil#257]
Hello,

i am just wondering how to configure my specific wish.
I have three (four) disks in my laptop (two Samsung Nvme Evo 960, one old 320GB HGST and a new 1TB WD)

I want to lock both Nvmes with the same password, but i want to place the PBA on the 1TB WD disk. The 1TB WD Disk is also locked with SED, but it can be unlocked by the bios, the nvme not.

I dont want to have a unsecure PBA on the nvme. It could be compromised and log the key.

Is this actually possible? Or is it possible to unlock the drives e.g. from a usb stick?

thanks

**Comment by cs224** [comment]
I have a similar set-up and would like to achieve the same goal as you do. Currently I am only reading documentation to prepare my install. Once I tried it out I can share my experience here.

After reading documentation I am especially unsure about the interaction between the shadow mbr and the efi system partition (ESD). My current understanding is that as long as the disk is locked it looks like there is only the shadow mbr visible to the BIOS. Once the disk is unlocked only the other partitions (like the ESD) become visible. Wouldn't that confuse the BIOS?

Let's see after my experiments, but any upfront guidance would be very much appreciated, too :)

**Comment by Painkilla** [comment]
hello,

this is quite interesting. As you mentioned you have followed the instructions on both disks. Do you have the PBA also installed on both?

thank you

**Comment by cs224** [comment]
Yes, I installed it on both disks, just to be sure.

**Comment by ShuaiTony** [comment]
@Painkilla 
Hello,
I have a problem ,when PC power on , after unlock the disk , i can't format this disk successfully. I use the samsung 970 EV0 (nvme) . And, I have seen the LINUXPBA source code , inside , "d -> Locked()", the Locked value is at level 0 discovery locking feature , however , when I set on it , after power cycle , the Bios can't identify the samsung disk ! Hope you can help .
Thank you very much.

**Comment by Painkilla** [comment]
you need to install PBA on a disk without a encryption or on the nvme within a space that is not encrypted.

**Comment by ShuaiTony** [comment]
Thank you , according to your anwser, I have solved this problem and unlock the disk ,it is working normally at present. Thank you again!
