### ISSUE TITLE
Issue Locking on Samsung 850 Pro

### ISSUE THREAD

**Issue by gill984** [Drive-Trust-Alliance/sedutil#26]
I'm having an issue unlocking the Samsung 850 Pro after locking it. I followed the instructions at the "Encrypting Your Drive" page. I'm using Ubuntu 14.04 on a drive and connecting the drive with an external eSata port.

1. First I ran "./sudo sedutil  -–initialsetup PASSWORD /dev/sdb"
2. Since this is not a boot drive, I then ran "./sudo sedutil --enableLockingRange 0 PASSWORD /dev/sdb"
3. These commands seem to run successfully so I reboot the laptop, but the drive seems to still be unlocked after rebooting.

I was hoping that since I was not using this as a boot drive, I would be able to run the --disableLockingRange command to unlock the drive and access contents. I thought that the --loadPBAimage and --setMBREnable commands weren't used since the drive is not a boot drive.

**Comment by dtasupport** [comment]
Does your eSata Enclosure provide power to the drive?  The drive will only
lock when it is power cycled.

On Thu, Feb 25, 2016 at 7:49 AM, gill984 <notifications@github.com> wrote:

> I'm having an issue unlocking the Samsung 850 Pro after locking it. I
> followed the instructions at the "Encrypting Your Drive" page. I'm using
> Ubuntu 14.04 on a drive and connecting the drive with an external eSata
> port.
>
>    1. First I ran "./sudo sedutil -–initialsetup PASSWORD /dev/sdb"
>    2. Since this is not a boot drive, I then ran "./sudo sedutil
>    --enableLockingRange 0 PASSWORD /dev/sdb"
>    3. These commands seem to run successfully so I reboot the laptop, but
>    the drive seems to still be unlocked after rebooting.
>
> I was hoping that since I was not using this as a boot drive, I would be
> able to run the --disableLockingRange command to unlock the drive and
> access contents. I thought that the --loadPBAimage and --setMBREnable
> commands weren't used since the drive is not a boot drive.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Drive-Trust-Alliance/sedutil/issues/26>.
>



-- 
==========
Mike

**Comment by gill984** [comment]
The esata cord does provide power. After shutting down the laptop and removing and reinserting the cord, the drive was locked. At least I think the drive is locked, Ubuntu doesn't recognize it after booting up. However, now after running the --disableLockingRange command, the drive seems to stay locked, even after power a power cycle. One thing I noticed is that the drive status from --query didn't seem to change, it still says "Locked = N, LockingEnabled = Y ..." which is what it said before I ran the --disableLockingRange command.

**Comment by dtasupport** [comment]
You don't want to disable the locking range, that turns off locking
completely.  To unlock the drive you would --setLockingRange 0 rw password
/dev/sd_ after re-enabling the global locking range.

On Thu, Feb 25, 2016 at 10:00 AM, gill984 <notifications@github.com> wrote:

> The esata cord does provide power. After shutting down the laptop and
> removing and reinserting the cord, the drive was locked. At least I think
> the drive is locked, Ubuntu doesn't recognize it after booting up. However,
> now after running the --disableLockingRange command, the drive seems to
> stay locked, even after power a power cycle. One thing I noticed is that
> the drive status from --query didn't seem to change, it still says "Locked
> = N, LockingEnabled = Y ..." which is what it said before I ran the
> --disableLockingRange command.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Drive-Trust-Alliance/sedutil/issues/26#issuecomment-188905313>
> .
>



-- 
==========
Mike

**Comment by gill984** [comment]
Ok I tried as you suggested by doing the following:

1) re-enabled locking range 0, sudo ./sedutil-cli -v --enableLockingRange 0 PASSWORD /dev/sdb
2) rebooted and removed/reinserted esata connector
3) ran query and saw that the drive was in fact locked "Locked = Y"
4) ran the command you suggested: sudo ./sedutil-cli -v --setLockingRange 0 rw PASSWORD /dev/sdb
5) Did another hard reboot as in step 2
6) Ran query, the drive says it is still locked "Locked = Y"

Am I missing something? Thank you for your help by the way.

**Comment by r0m30** [comment]
After step 4 if you do a query you will see that the drive is unlocked.
You probably will also need to --setmbrdone on to hide the shadow mbr and
make the data available.  You will possibly need to issue a sync so that
the os will reread the partition table from the unlocked disk.

The disk will remain unlocked until you power cycle it or manually lock it
(--setlockingrange 0 lk password /dev/sd?)



On Tuesday, March 1, 2016, gill984 <notifications@github.com> wrote:

> Ok I tried as you suggested by doing the following:
>
> 1) re-enabled locking range 0, sudo ./sedutil-cli -v --enableLockingRange
> 0 PASSWORD /dev/sdb
> 2) rebooted and removed/reinserted esata connector
> 3) ran query and saw that the drive was in fact locked "Locked = Y"
> 4) ran the command you suggested: sudo ./sedutil-cli -v --setLockingRange
> 0 rw PASSWORD /dev/sdb
> 5) Did another hard reboot as in step 2
> 6) Ran query, the drive says it is still locked "Locked = Y"
>
> Am I missing something? Thank you for your help by the way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Drive-Trust-Alliance/sedutil/issues/26#issuecomment-190858624>
> .
>


-- 
-----
r0m30

**Comment by gill984** [comment]
I did as you suggested and it worked.

Thank you very much!
