### ISSUE TITLE
Access MBR table after unlock

### ISSUE THREAD

**Issue by ranshalit** [Drive-Trust-Alliance/sedutil#266]
Hello,

After a successful unlock I wanted to access the MBR shadow from Linux OS disk.
But I don't see it listed in mounted devices.
Is it possible to access the MBR table after unlocking ?
Do we need to mount a device in order to view the files/path of the MBR table ?

Thank you,
Ran

**Comment by LITTENg** [comment]
maybe you can use the command: sudo ./sedutil-cli --setMBRDone off <password> <device>
then mount it

**Comment by pfiser** [comment]
Try hdparm -z /dev/sdX to re-read the MBR?

**Comment by ShuaiTony** [comment]
@ranshalit     
Hello,
        I have a problem ,when PC power on , after unlock the disk , i can't format this disk successfully. I use the samsung 970 EV0 (nvme) . And,  I have seen the LINUXPBA source code , inside , "d -> Locked()",  the Locked value is at level 0 discovery locking feature , however , when I set on it , after power cycle , the Bios can't identify the samsung disk ! Hope you can help .
Thank you.

**Comment by r0m30** [comment]
The Shadow MBR is not available to the OS after MBRDone is set on.  It can be accessed via OPAL commands but not as a device.
