### ISSUE TITLE
Disabling locking issue

### ISSUE THREAD

**Issue by ranshalit** [Drive-Trust-Alliance/sedutil#269]
Hello,

I have some strange issue.
I have created EFI partition in /dev/sda3 which contains the PBA and starts correctly, but only if I start from usb stick with password.
This is what I did:
sedutil-cli --reverttper password /dev/sda
sedutil-cli --initialsetup password /dev/sda
sedutil-cli --setupLockingRange 1 0 2048 password /dev/sda
sedutil-cli --setupLockingRange 2 466862080 1998848 password /dev/sda
#sedutil-cli --loadPBAimage password pbafilename /dev/sda
#sedutil-cli --setMBREnable on password /dev/sda
sedutil-cli --enableLockingRange 0 password /dev/sda
sedutil-cli --disableLockingRange 1 password /dev/sda
sedutil-cli --disableLockingRange 2 password /dev/sda
sedutil-cli --setsidpassword debug ranran /dev/sdc
sedutil-cli --setadmin1pwd debug ranran /dev/sdc

As you can see I've put the MBR table (0,2048 above)  and the EFI (which has the UEFI64 PBA) in /dev/sda3 both in disableLockingRange .
So I had expected the PBA to start, yet on clicking the bios boot mode for the PBA (/dev/sda3) it does not start unless I first run password from usb.
Why I can't see partition table even after disabling all ranges with disableLockingRange  ?

The strangest thing is that even if I change all partitiont to unlocked (disableLockingRange ), it does not act as if the opal was removed, and I still can't see the partitions.... :(
I verified it with listlockingranges, everything is (N) - not locked!

Later, I just tried to do the exact sequence in the wiki and then disable, and surprsingly it also does not work. I can't see my data after unlocking !

The sequence I did:
1. PSID revert
2. exact sequence of locking
3. power off -> works
4. then did the unlocking as written in wiki , and power off -> doesn't work any more, can't see the data in disk !

Thank you for any idea,
ranran

**Comment by oom-is** [comment]
Please advise if you're still trying to troubleshoot this.

From what I can tell the steps you performed above put you in an unusual state.
There is no requirement to exclude the PBA from the locking range, as the PBA image is stored in a separate "shadow" area of 128MB (minimum per spec) which only becomes visible if the MBRdone/MBRenabled areas are set...but when that image becomes visible then the entire "normal" drive is locked/hidden.

The minimum sequence of commands that I think you actually wanted to follow:
sedutil-cli --reverttper password /dev/sda
sedutil-cli --initialsetup password /dev/sda
sedutil-cli --enableLockingRange 0 password /dev/sda
sedutil-cli --loadPBAimage password pbafilename /dev/sda
#sedutil-cli --setMBREnable on password /dev/sda
sedutil-cli --setsidpassword password ranran /dev/sda
sedutil-cli --setadmin1pwd password ranran /dev/sda

If you performed those commands in sequence with a "normal" SED as /dev/sda, then subsequent reboots *should* get you the PBA, which can be unlocked with password "ranran", and then your system should boot normally into the OS.
