### ISSUE TITLE
Pba loop on dell e6420xfr

### ISSUE THREAD

**Issue by FedericoDiGiuseppe** [Drive-Trust-Alliance/sedutil#274]
Hello.
after performed the various recommended tests and setting the SSD according to tutorial, turning on my laptop I am asked for the pba password but once entered, right or wrong It was, the computer reboots and go back to the request for a password again and so on.
the only thing I can grasp in the quick screen before reboot is the name of my SSD (Samsung 860 evo 1T) and "is Opal unlocked" if the right password Is submitted or "Is Opal failed" if an incorrect password Is submitted and "starting os" but After the reboot the situation Is the same.
Has anyone had the same problem and could recommend a solution?
Many thanks

**Comment by maenpaa24** [comment]
your laptop is cutting the power of the ssd on reboot surely. Hard to solve.

**Comment by FedericoDiGiuseppe** [comment]
This is odd because installing Windows and using the Dell data protection it works. 
Can this suggest something?

**Comment by r0m30** [comment]
Some Dell computers power cycle the drive during a soft reboot, that relocks the drive.  This is incompatible with the sedutil PBA.
