### ISSUE TITLE
Shadow MBR for multiple disks

### ISSUE THREAD

**Issue by clifforama** [Drive-Trust-Alliance/sedutil#275]
I've successfully setup drive encryption by following the wiki instructions. I've been trying to wrap my head around the concept of the shadow MBR, and am wondering if I'm understanding correctly.

Supposition: Shadow “MBR” is a misnomer in the context of a UEFI system. It's really more of a shadow “disk” using GPT (not MBR) and contains an EFI system partition (within which the PBA image is placed via sedutil's loadPBAimage).

As a test, I booted to a Windows 10 USB flash drive (without unlocking my SED SSDs — I have two). Using diskpart, I could see that one disk did indeed use GPT and contained a small EFI partition. That's what I expected to find within a shadow MBR.

However, the other disk was not identified as GPT and showed no partitions. This was unexpected. Is this because there's some awareness (by UEFI?) of multiple locked OPAL drives so that somehow only one shadow MBR will be exposed?

**Comment by dtasupport** [comment]
UEFI is a boot mechanism and so only recognizes one boot at a time.  out of
the box UEFI knows nothing about Opal or locked drives or anything like
that.  It is possible to have a VM boot off a different disk if the VM
vendor and OS vendor has allowed this.
regards,

Bob Thibadeau
412 370 1245

**Comment by clifforama** [comment]
Actually, it turns out both shadow MBRs *are* visible, as I thought they should be. For some reason, when booted into a Windows 10 USB, I could only see one shadow MBR (via `diskpart`). But, when I instead booted from the sedutil rescue USB, I could see both shadow MBRs (via `fdisk`). Sorry, I don't know why I didn't use the rescue disk from the get go ;)

**Comment by brendanhoar** [comment]
Windows really doesn't like two volumes with the same volume signature. Normally Windows will see that and immediately change the signature of the duplicate signature, but since the shadow MBRs are read-only...it is likely just refusing to register the volume on the system.

**Comment by henriquebecker91** [comment]
I expected this issue to mention how you change the label/UUID/PARTUUID of the image you write to the shadow mbr, there is no way?
