### ISSUE TITLE
PBA errors

### ISSUE THREAD

**Issue by uidar** [Drive-Trust-Alliance/sedutil#28]
I am suck on testing PBA. In both BIOS1.12 and UEFI1.12 after entering pass errors show up [http://imgur.com/a/AlOZ9](http://imgur.com/a/AlOZ9) and computer restarts. Sorry for quality of pictures but it is visible only for fraction of a second.

Possibly helpful:

zba@zba-desktop:~/sedutil/Release_x86_64/GNU-Linux$ sudo ./sedutil-cli --scan
Scanning for Opal compliant disks
/dev/sda  2  Crucial_CT250MX200SSD1                   MU01   
/dev/sdb No  ST3500320AS                              SD1A   
/dev/sdc No  
No more disks present ending scan

zba@zba-desktop:~/sedutil/Release_x86_64/GNU-Linux$ sudo ./sedutil-cli --query /dev/sda
/dev/sda ATA Crucial_CT250MX200SSD1                   MU01             15040E8CCA9E
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = Y, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = Y, Alignment Granularity = 8 (4096), Logical Block size = 512, Lowest Aligned LBA = 0
SingleUser function (0x0201)
    ALL = Y, ANY = N, Policy = N, Locking Objects = 16
DataStore function (0x0202)
    Max Tables = 16, Max Size Tables = 94371840, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x1000, Initial PIN = 0x0, Reverted PIN = 0x0, comIDs = 1
    Locking Admins = 4, Locking Users = 16, Range Crossing = N
TPer Properties:
  MaxComPacketSize = 131072  MaxResponseComPacketSize = 131072
  MaxPacketSize = 129792  MaxIndTokenSize = 126976  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxSessions = 1
  MaxAuthentications = 21  MaxTransactionLimit = 1  DefSessionTimeout = 240000
Host Properties:
  MaxComPacketSize = 2048  MaxResponseComPacketSize = 2048
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1

**Comment by r0m30** [comment]
Hi,

NOT_AUTHORIZED means that you entered an incorrect password.  Is it possible that you are using a non US keyboard?  That can be an issue as the PBA used the default (US) keyboard.

**Comment by uidar** [comment]
Well, I had to misunderstood something that. I was trying to follow your instruction:
> Boot the USB stick, enter anything when asked for the passphrase and verify that it scans your system correctly identifying your OPAL disks.

**Comment by r0m30** [comment]
It probably wasn't as clear as it could have been.  The instructions were written for an early version of the PBA and it was more verbose so it told you that it found an Opal drive and was trying to unlock it.  I have found that since the messages scroll by so quickly that no one ever sees the messages.

If you are getting the NOT_AUTHORIZED then the PBA is recognizing your drive and should be able to unlock it if you enter the correct password.
