### ISSUE TITLE
Determining which drives are compatible...before purchase?

### ISSUE THREAD

**Issue by brendanhoar** [Drive-Trust-Alliance/sedutil#283]
As far as I am aware, there is not a mailing list dedicated to sedutil and/or some of the excellent folks behind it (DTA). So, consider this a quasi-issue.

Q: If an end user wanted to determine which SSD to purchase so that compatibility with sedutil was (nearly) assured, how does this prospective user of sedutil know what drives will work with it, and which ones will not?

A1: the project could support and mainting a hardware compatibility list (HCL). This is, effectively, what mining the issues list kinda-sorta does.

A2: the project could give guidance on what features to look for advertised with drives (E.g. AES or OPAL). This, unfortunately, does not always work, as several manufacturers have both "with" and "without" AES or OPAL under the same model name, and one must learn the model *number* to delineate (e.g. Micron with 6 vs Z at a particular location in the model number - and a several hundred dollar difference). Even worse, the same product features (e.g. AES encryption) is listed in all listings for these particular model name, even if the model number doesn't support it... which would at least allow you to have a valid reason to return it ("doesn't actually have the listed feature").

A3: what I usually do: stick to what I know works best, even though it costs a premium.

A4: create and maintain anti-HCL: e.g. Pyrite and non-encrypting drives... :(

Thoughts?

**Comment by kaweksl** [comment]
To determine if ssd support opal I'm always looking for PSID on label and as far all disks i bought with psid works with sedutils.

BAD example: Corsair MP510 - affordable NVMe -  some sites state that it supports Opal but I can't find PSID anywhere on that drive. Anyone have one ?

**Comment by Venemo** [comment]
> If an end user wanted to determine which SSD to purchase so that compatibility with sedutil was (nearly) assured, how does this prospective user of sedutil know what drives will work with it, and which ones will not?

* SSD spec sheet should advertise TCG/OPAL support
* If the spec sheet says it supports "AES", but does not mention OPAL then it is usually just "class 0" encryption and not OPAL

**Comment by brendanhoar** [comment]
>     * If the spec sheet says it supports "AES", but does not mention OPAL then it is usually just "class 0" encryption and not OPAL

Or even worse...

The manufacturer distributes a drive with multiple  firmware versions: half w/ SED capabilities and half without. The drives have the same consumer facing model name, but the model number flags indicate form factor, size and inclusion of optional features. And the features have different wholesale/MSR prices.

Resellers can't be bothered, however, to note any differences in their listings, so they all list TCG OPAL/AES-256 in the product features and appear to carry the same model name at vastly different prices with no difference in the listing other than the manufacturer model number.

So...

It's worth keeping track of the right Micron model numbers. Almost made a very expensive mistake once!
