### ISSUE TITLE
Unable to revert TPER on Intel p4800 SSD

### ISSUE THREAD

**Issue by pdambal** [Drive-Trust-Alliance/sedutil#288]
I am trying to revert the Intel P4800 SSD with following command and I get following error.  
NVME Security Command Error:7
revertTper completed successfully

Revert TPER is not successful.
[reverttper_issue.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/3160282/reverttper_issue.txt)

**Comment by oom-is** [comment]
The log you sent, and the results you reported (NVMe Security Command Error) are consistent with the P4800 series not actually implementing support for either TCG Enterprise or TCG Opal.

Looking at the datasheets and searching around, the P4800/P4800X "Optane" drives do claim to have AES-256 support but I can't find anywhere that they actually implement TCG Enterprise or TCG Opal on these drives.  I definitely don't speak for DTA, but given that SEDutil appears to be designed around support for the TCG specs I don't expect that SEDutil can support a disk that doesn't implement either TCG Opal or TCG Enterprise.
