### ISSUE TITLE
Not locked, but `NOT_AUTHORIZED`

### ISSUE THREAD

**Issue by j-a-m-l** [Drive-Trust-Alliance/sedutil#289]
Iḿ trying to encrypt my SSD, but I'm having several problems.

`linuxpba`shows `/dev/sda` as `OPAL NOT LOCKED` (using `debug` as password).

`sedutil-cli --query /dev/sda` displays it as not locked:
`Locked = N, LockingEnabled = N, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y`

But when I run `sedutil-cli --initialsetup debug /dev/sda`, I get a `NOT_AUTHORIZED` code.
I've tried several times the process, and I've reverted it too, so I don't know if there is something more that I need to do.

**Comment by Venemo** [comment]
Maybe you are not authorized because OPAL was already set up on the drive? Have you tried https://github.com/Drive-Trust-Alliance/sedutil/wiki/Remove-OPAL ?

**Comment by j-a-m-l** [comment]
Thanks.

I tried that, but I didn't reset the state of the drive. I might do it in some weeks or months, when I'm not using that computer anymore.

**Comment by ladar** [comment]
I can into this same problem, but it went away after I enabled CSM support in the BIOS. Once that was done I was able to remove OPAL, and run the setup process from the beginning without an issue. 

I don't know if the PBA images require CSM, or just the recovery.

**Comment by Venemo** [comment]
Neither of them needed CSM, at least on my machine. I guess it depends on whether or not you can boot the recovery image in UEFI mode or not.

**Comment by ladar** [comment]
CSM support is only required for UEFI boots. Doesn't apply if your booting in BIOS mode.

**Comment by j-a-m-l** [comment]
I think that this issue could be closed since I'm not in position to experiment again with that computer. When I'm able to try these solutions, I'll re-open it if they fail.

**Comment by bjmgeek** [comment]
I'm trying to boot on a Dell Latitude E7470 with a Crucial_CT525MX300SSD4 drive.  I'm seeing this issue, but I'm pretty sure CSM is enabled on my system.

**Comment by ladar** [comment]
@bjmgeek boot into the BIOS (usually means holding down the F1 key when you power on), and confirm the system is booting with UEFI and CSM. If it says both, that means BIOS and UEFI, in which ensure it's trying UEFI first. 

Alternatively, try booting one of the BIOS recovery images, and using that. I haven't tested this, but it might be worth a try.

I unlocked my drive but didn't remove OPAL, and when I went back later, I saw both NOT_AUTHORIZED and Header Length 0. But that was with a ThinkPad, and Samsung drives.

**Comment by ladar** [comment]
I should add, the NOT_AUTHORIZED was with the initial setup, on a drive that had previously been setup, but had locking disabled. Other commands, like re-enabling locking, removing OPAL, failed with an error  like invalid parameter, header length 0 (I don't recall the exact message). Once I enabled CSM, I was able to remove OPAL, and then run the initial setup without a problem.I

**Comment by ngrigoriev** [comment]
I had a similar issue and found through another bug report that doing PSID revert and then initialsetup works. Do not power off the drive in between, of course.
