### ISSUE TITLE
how big pbaimage can be ?

### ISSUE THREAD

**Issue by areqq** [Drive-Trust-Alliance/sedutil#293]
Hi
How big pbaimage can be ?
BIOS32.img is only 32MB
My disk SSD Samsung 860 QVO

**Comment by oom-is** [comment]
Technically on Opal TCG 2.0 compliant drives, the PBA image can use the entire "Shadow MBR" dedicated space which must be 128MB.

In reality it's not a question of how big the PBA image can be but how big it *should* be.  It *should* be (for most folks) a minimum size that boots the system enough to authenticate a credential set and unlock the drive, then causes a reboot into the "real" MBR space (or EFI space for newer drives).

WinMagic (which has a commercial product "SecureDoc" that can manage TCG drives) has a pretty good explanation of it here:  [https://www.winmagic.com/blog/how-seds-really-work/](url)
