### ISSUE TITLE
Unable to dual boot Windows and Linux

### ISSUE THREAD

**Issue by ghost** [Drive-Trust-Alliance/sedutil#297]
Hey! I have used this program for a while now however a couple of months ago I had to remove it because I was unable to get it working with a Linux dual boot. The issue is the program completely bypasses the Linux dual boot a goes straight into Windows. I even set my BIOS to use the Linux boot as default however it still bypassed it.

So I guess my questions/issue is am I able to fix this or point it towards the correct boot?

**Comment by maenpaa24** [comment]
I am pretty sure that is completely unrelated to sedutil. Try reinstalling grub (or the boot-loader you use)

**Comment by serafimeid** [comment]
Did you get it working? I'm having the same issue. I'm not sure if it is a bootloader problem. Every time I set the boot order menu to first boot in grub, save and quit from the firmware, the drive got locked and when I unlock it, my boot order configuration goes back to the state it was before, which is boot into the windows bootloader. Without sedutil it just works, the boot order config keeps untouched between reboots.

**Comment by r0m30** [comment]
This is a pretty common problem.  The firmware on some systems removes boot entries that it is unable to find.  The drive is encrypted so it can't see the linux esp provided by your distro and deletes the entry.  The only workaround that I have seen work is to structure the PBA image (the pba is an esp)  the same way as the esp provided by the distro you are using.  It's a PITA and there is no way we can do this for each distro.

**Comment by asfernandes** [comment]
I'm having the same problem.
