### ISSUE TITLE
Failure testing the "Small Lean PBA"

### ISSUE THREAD

**Issue by GutHib** [Drive-Trust-Alliance/sedutil#30]
Hello,

I've already installed the "regular" PBA on my Samsung Evo drive running Windows, and everything is working just great. Now I discovered there's a "Small Lean PBA" as well, I've tried testing it by putting in on a USB stick first, but when I do, entering a password on bootup gets me the following error:

"found device identify failed"

I went ahead and turned off locking and the original PBA as described on the bottom of your "Encrypting your drive" page, but it makes no difference. Does this simply mean the "Small Lean PBA" won't work on my machine, or is there something else I can try?

Thanks (above all for the hard work you are putting into this - fantastic!)

**Comment by r0m30** [comment]
Yes, if you get that message then that PBA doesn't support your hardware.

**Comment by GutHib** [comment]
Thanks. Since I'll be equipping other machines as well - is this a "hit and miss", or is there a compatibility list somewhere or at least a rule of the thumb, what to expect from what kind of hardware (e.g. by brand, or by age)? Thanks again.

**Comment by r0m30** [comment]
There is no compatibility list.  It seems to be older PC's and laptops without the newest power management features.

**Comment by GutHib** [comment]
...which work - or don't work? :)

**Comment by r0m30** [comment]
See edit.

**Comment by GutHib** [comment]
Thanks
