### ISSUE TITLE
Cannot PSID revert Samsung 850 PRO: One or more header fields have 0 length

### ISSUE THREAD

**Issue by nbonamy** [Drive-Trust-Alliance/sedutil#312]
Hello,

trying to revert a Samsung 850 PRO to no avail. Error message is "One or more header fields have 0 length".

Please find attached query and revert logs:
[query.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/4003048/query.txt)
[revertlog.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/4003047/revertlog.txt)

Thanks for your help!
Nicolas

**Comment by nbonamy** [comment]
This was run under Windows. Using the rescue system image, got error code 255.

**Comment by oom-is** [comment]
Nicolas, did you previously go through the process of taking crypto ownership of the drive and encrypting it?  (The query.txt implies the drive is not encrypted, no PBA loaded to the "shadow MBR" area, etc.).  Or were you trying to do the PSID revert to get the drive to the point where you could initialize it?

If you ever get error code 255, that implies that you've tried something that the drive (Trusted Peripheral/TPer) sees as illegal or questionable too many times - so it's locked out.

Try power cycling, make sure you use the PSID in all upper case with no dashes, and see what results you get this time.  Drop a line in this thread and I'll try to keep an  eye out - note that @r0m30 and DTA haven't been actively supporting SEDutil for several years so it's volunteers trying to help at this point.

**Comment by oom-is** [comment]
Also, if you do respond, please verify what motherboard and CPU you're using.
The "vanilla" DTA SEDUtil v1.15.1 is using a very old Linux kernel that has issues with many new AMD CPUs and may have other hidden gotchas, so we want to rule those items out instead of wasting time.
