### ISSUE TITLE
Can't unlock shadow MBR on my NVMe device with Pyrite

### ISSUE THREAD

**Issue by miniedwins** [Drive-Trust-Alliance/sedutil#313]
Hi Everybody,

When booting shadow MBR partition, I can't unlock my NVMe device.
It always showed "Not OPAL".

Why I got the "Not OPAL" message ? 
I'm sure that I have enabled the TCG OPAL on my NVMe device.

[Info]
OS : Ubuntu 18.04.1
Kernel : 5.0.0-37
Device : PCIe NVMe 1.3 with Pyrite 
Shadowing Image : UEFI64-1.15.1.img

[Problem]
Can't unlock "shadow MBR"

[Operation]
1. ./sedutil-cli --initialSetup [MSID password] [device]
2. ./sedutil-cli --setAdmin1Pwd [MSID password] [admin1 password] [device]
3. ./sedutil-cli --setMBRDone off [admin1 password] [device]
4. ./sedutil-cli --loadPBAimage [admin1 password] [image] [device]
5. Reboot

**Comment by Geblaat** [comment]
> Hi Everybody,
> 
> When booting shadow MBR partition, I can't unlock my NVMe device.
> It always showed "Not OPAL".
> 
> Why I got the "Not OPAL" message ?
> I'm sure that I have enabled the TCG OPAL on my NVMe device.
> 
> [Info]
> OS : Ubuntu 18.04.1
> Kernel : 5.0.0-37
> Device : PCIe NVMe 1.3 with Pyrite
> Shadowing Image : UEFI64-1.15.1.img

Are you aware that Pyrite misses a lot of OPAL features?
See: https://github.com/Drive-Trust-Alliance/sedutil/issues/310

**Comment by oom-is** [comment]
If you could please supply the actual manufacturer and part number for your "" device, that might also help with suggestions.  But fundamentally...yeah, Pyrite is a minimal subset makes no guarantees of actually supporting Features That Matter to most people.  The only thing it really guarantees AFAICT is Secure Erase (which is a useful feature in Enterprise environments, but not for most of us home/enthusiast/small-scale users).

Also as noted in the thread @Geblaat referenced, there's better Pyrite support that's been added to the FreeBSD port of SEDutil by @amotin but I'm not aware that anyone's had a chance to add that code to Windows or Linux trees and compile new binaries.

**Comment by oom-is** [comment]
Also, if you do respond, please verify what motherboard and CPU you're using.
The "vanilla" DTA SEDUtil v1.15.1 is using a very old Linux kernel that has issues with many new AMD CPUs and may have other hidden gotchas, so we want to rule those items out instead of wasting time.

**Comment by amotin** [comment]
> Also as noted in the thread @Geblaat referenced, there's better Pyrite support that's been added to the FreeBSD port of SEDutil by @amotin but I'm not aware that anyone's had a chance to add that code to Windows or Linux trees and compile new binaries.

To the best of my knowledge there is no reason why my code should not build for Linux or Windows.  It is merely a question of somebody building it, or taking care to finally upstream my changes.

**Comment by miniedwins** [comment]
Hello, I already found solution. 

1. Rebuild BIOS32 image. I used old PBA image.
2. Before loading PBA image to shadow MBR partition, I need to issue "setLockingRange".

Now I've not got "Not OPAL" message. But I'm confused about why I need to issue the setLockingRange. If I don't  have to issue the "setLockingRange", I will always get "is OPAL NOT LOCKED". And it will never to unlock my drive.

[Operation]
1. ./sedutil-cli --initialSetup [MSID password] [device]
2. ./sedutil-cli --setAdmin1Pwd [MSID password] [admin1 password] [device]
3. ./sedutil-cli -setLockingRange 0 lk  [admin1 password] [device].  
4. ./sedutil-cli --setMBRDone off [admin1 password] [device]
5. ./sedutil-cli --loadPBAimage [admin1 password] [image] [device]

**Comment by amotin** [comment]
For some weird reason sedutil behaves different for Opal and Enterprise drives. Enterprise drives are locked on initialization complete. while Opals are not.  My guess is that there was some reason behind it, like somebody would prefer to lock only some ranges (user partitions) instead of the whole drive, but any way that difference is confusing.
