### ISSUE TITLE
Samsung PM883 "Hardware based AES 256-bit" is not OPAL?

### ISSUE THREAD

**Issue by ebivan** [Drive-Trust-Alliance/sedutil#318]
Hey there, 
i was offered a good price on a Samsung PM833 Enterprise SSD, it is listed with the dubious "Hardware based AES 256-bit Encryption Engine". I suppose that does not equal OPAL 2.0, am I right?

If so, is there any way to make use of that encryption on a Linux maschine that does not support BIOS password?

**Comment by oom-is** [comment]
Short version - probably no way to make use of that encryption, as you guessed.

Longer version - you're unfortunately correct.  Piecing together info from several places on Samsung and related websites, the "PM883" is apparently the same as the "883 DCT" which is a "data center" enterprise drive.  Interestingly, Samsung does implement TCG Opal 2.0 in some of their "enterprise" drives according to documentation, although I would have expected TCG Enterprise instead.  (I only have Samsung consumer drives with which to test SEDutil.)

The best specs for the PM883/883DCT that I found are from:
https://www.samsung.com/semiconductor/global.semi.static/Data_Center_SSD.Product_Brief.pdf

Relevant quote from that product brief:

> To maximize data security, the Data Center SSD lineup also boasts AES-256 bit hardware encryption and TCG/Opal compliance.* 

The fine print taketh away:  

> *TCG/Opal supported only in 983 DCT and 983 ZET.

 So, the 883 DCT lists “Data Encryption” as “Class 0 (AES 256)”

“Samsung Dave” in a question about the 960 Pro gave the response: 

> “The 960 Pro only supports 2 types of Hardware level encryption, Class 0 (AES 256bit), and TCG/OPAL 2.0. Class 0 is enabled through the BIOS drive password feature and TCG/OPAL requires 3rd party programs to activate.”

It is very likely that unless you can acquire a MB that provides the Class 0 encryption support, you won't be able to access those features.

**Comment by ZLightning** [comment]
Note, this MAY work, but if the bios doesn't support ATA passwords, the drive will not be bootable.

http://man7.org/linux/man-pages/man8/hdparm.8.html#ATA_Security_Feature_Set
