### ISSUE TITLE
Dangerous command in instructions

### ISSUE THREAD

**Issue by prinsherbert** [Drive-Trust-Alliance/sedutil#319]
The `dd if=RESCUE64.img of=/dev/sd?` instruction is dangerous, the question mark will match any disk in terminals with bash and dd will write to it, destroying whatever's on it. Please use something else then the `?`

https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive

**Comment by dtasupport** [comment]
If you want to fix it feel free.

regards,

Bob Thibadeau, Ph.D.
c +1 412 370 1245

**Comment by prinsherbert** [comment]
I know almost nothing about sedutil, so I will not be editing it's
documentation.

**Comment by oom-is** [comment]
Bob (Dr. Thibadeau), there are several of us who are actively using Sedutil (SEDUtil?) and would love to help adjust the documentation.

The Wiki is set as only being editable by folks who are "part of the project", so AFAICT only you, Mike r0m30 and a few others might be able to fix the Wiki.

If there's a way to let us prove ourselves (I'd suggest some of the folks who've submitted useful pull requests and have attempted to help answer other issues here) then that would be great.....

**Comment by r0m30** [comment]
Changed the # to a (x), AFAIK this isn't a regex that bash recognizes.

**Comment by r0m30** [comment]
@oom-is I looked into making the wiki publicly editable but I don't have the authority, it was a long time ago when we set the repos up and I'm not even sure who has the auth to change the setting.

**Comment by r0m30** [comment]
@oom-is I lied, I was looking in the wrong place.  See if you can edit the Wiki.
