### ISSUE TITLE
Is there any emulator to test commands using sedutil CLI.?

### ISSUE THREAD

**Issue by ayushkumar024** [Drive-Trust-Alliance/sedutil#322]
I am working on opal specification 2.01. But i don't have SED hard drive. So, I am curious to know is there any emulator to test commands from sedutil CLI. Some kind of emulator or software which I install and it work as virtual drive for sedutil CLI.
Thanks in advance.

**Comment by r0m30** [comment]
AFAIK there is no emulator available.
