### ISSUE TITLE
method status code FAIL

### ISSUE THREAD

**Issue by lifeguard999** [Drive-Trust-Alliance/sedutil#325]
Hi,

When running the PSID-Revert, I get the following error:

./sedutil-cli --yesIreallywanttoERASEALLmydatausingthePSID <myPSID> /dev/sdb
method status code FAIL
Session start failed rc = 63

The disk has Opal 1:

./sedutil-cli --scan
Scanning for Opal compliant disks
/dev/sda   No  HITACHI (my HDD)
/dev/sdb   1   SAMSUNG SSD PM810 FDE 2.5" 256GB         AXM77D1Q
No more disks present ending scan

**Comment by lifeguard999** [comment]
Attaching the log generated with -vvvvv flag (as per https://github.com/Drive-Trust-Alliance/sedutil/wiki/PSID-Revert)

[revertlog.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/4571699/revertlog.txt)

**Comment by lifeguard999** [comment]
And the result of running --query...

./sedutil-cli --query /dev/sdb

/dev/sdb ATA SAMSUNG SSD PM810 FDE 2.5" 256GB         AXM77D1Q       S0S8NEAB909523
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = Y, LockingEnabled = Y, LockingSupported = Y, MBRDone = N, MBREnabled = Y, MediaEncrypt = Y
Opal V1.0 function (0x0200)
Base comID = 0x1002, comIDs = 1

TPer Properties: 
  MaxComPacketSize = 2048  MaxResponseComPacketSize = 131072
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxSessions = 4
  MaxAuthentications = 2  MaxTransactionLimit = 1
Host Properties: 

  MaxComPacketSize = 2048  MaxPacketSize = 2028  MaxIndTokenSize = 1992
  MaxPackets = 1  MaxSubpackets = 1  MaxMethods = 1

**Comment by r0m30** [comment]
The Samsung PM series are OEM drives and have different firmware options depending on who originally ordered them.  There is no way to even know what is happening on that drive.
