### ISSUE TITLE
Disabling Secure Boot for UEFI = Data breach?

### ISSUE THREAD

**Issue by DanielLausch** [Drive-Trust-Alliance/sedutil#326]
Hello,

at **https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive**
it says:
** UEFI support currently requires that Secure Boot be turned off **
Does it mean that with UEFI / non Secure Boot, i could just boot my own OS from an USB stick and dump the data from a "locked" opal drive?

Best wishes

Dan

**Comment by r0m30** [comment]
The data is encrypted. I guess if you have the compute you could try and decrypt it offline but most of the drives use aes256, that’s state actor territory. If you are trying to protect against that level of attack I am wholly unqualified to express an opinion.

**Comment by DanielLausch** [comment]
Hello r0m30,
thanks for your answer.

Im not sure if i made clear enough what i exactly want to say/ask.

OPAL devices automatically unlock (if not using extra security/password other then TPM), as they are "paired" with the TPM Chip.

So if you run a system without secure boot you can boot any bootable media / other OS, right?

Means you can access all the Data on the OPAL drive without the need of any auth/password, by just booting from another OS.

Is this true? Or does a OPAL HDD locket with/to TPM just work on (pre-)boot?

**Comment by r0m30** [comment]
There is no automatic pairing with the TPM. I suppose you could write software to do that but sedutil  doesn’t. A drive that hasn’t been activated (TAKEOWNERSHIP) is autounlocked at power on, or more accurately auto decrypted.  There is no requirement for a TPM to use OPAL.  If you boot the rescue system, you can see this. You can’t access a drive that has been setup until you unlock it with the password.

**Comment by DanielLausch** [comment]
hello,

thank you. i got this point now.

cheers

D
