### ISSUE TITLE
Brute force risk?

### ISSUE THREAD

**Issue by seven-plus** [Drive-Trust-Alliance/sedutil#33]
Hi,

I am keen to use your solution on my Samsung 850 EVO but am wondering what the risk of brute force is.

1) Does the drive's controller throttle attempts and/or requires power cycles every x failed attempts?

2) What length password would be recommended to provide decent protection in the event of theft?

Thanks a lot

**Comment by r0m30** [comment]
Yes, the EVO has a failed attempt counter and requires a power cycle after x failed authentication attempts.  A test tequires rebooting several times but if I remember correctly it is  6 attempts.  If you want to verify this you can power cycle your machine, boot from the rescue image and then issue the setlockingrange command with an incorrect password until the response changes from NOT_AUTHORIZED to AUTHORITY_LOCKED_OUT.  Of course then you will need to power cycle the machine again.

A good password is a good password no matter where it is used.  The general password recommendations apply to SEDs just like any other device you want to secure.  The longer the better and use a mixture of upper and lower case letters with a sprinkling of numbers and special characters. 

It really depends on who you are trying to protect yourself from.  A common thief is not going to have specialized brute force attack equipment.  That means that your vulnerability is based on how well your password holds up to the common password cracking tools.  It is worth noting that using "normal" equipment it takes at least 10ms, and more commonly ~25ms just to send a command to the drive and receive a response, and it takes at least three commands (start session, setlockingrange, end session) per attempt. this limits the attack speed to 35 or fewer attempts per second without specialized equipment.  A power cycle required after x attempts slows the attack down even more.

If you are expecting your equipment to be interesting to a three letter agency then you have to expect more sophisticated attacks and/or the cooperation/coercion of the drive manufacture.  At that point you are deep in the rabbit hole.

**Comment by seven-plus** [comment]
Hi r0m30,

Thanks a lot for the information.

What is the maximum password length for sedutil?

Thanks.

**Comment by r0m30** [comment]
The password can be up to 250 characters but it is hashed down to 32 bytes to conform to the size required by the drive.
