### ISSUE TITLE
Restricted characters for PBA password?

### ISSUE THREAD

**Issue by mtnsec** [Drive-Trust-Alliance/sedutil#338]
While trying to set up a new system with a new password we ran into issues when using special characters.  We know for sure that `", ., $, and !` will cause errors on the cli when setting the password.

In fact, sedutil became broken to the point we needed to PSID revert it.

So, we are trying again, but this time hopefully we can avoid issues with special characters.  Is there a definitive list of characters that can NOT be used that we need to avoid?

Thanks,

**Comment by Jip-Hop** [comment]
The same happened to me! I made an [alternative PBA](https://github.com/Jip-Hop/sedunlocksrv-pba) which doesn't have these issues. It takes a very different approach though (unlock via HTTPS), so it may not be what you're looking for. Perhaps the [rear](https://github.com/rear/rear/blob/master/doc/user-guide/13-tcg-opal-support.adoc) PBA could be a solution (I borrowed some of their code for my PBA).

**Comment by Jip-Hop** [comment]
As test, my password is now successfully set to `", ., $, and !` and I can unlock it too 🙂
