### ISSUE TITLE
bzImage IO error

### ISSUE THREAD

**Issue by crepererum** [Drive-Trust-Alliance/sedutil#34]
I've tried to get the UEFI PBA working on an USB stick (to see if it's actually working before writing it to the SSD). The UEFI recognizes it, but then the following error occurs (again and again, it's seems to loop): `loading bzImage ... failed IO error`. I don't think that the USB stick is the problem because it worked totally fine with other USB distros.

**Comment by r0m30** [comment]
I'm not exprtienbing any issues with the UEFI PBA here, have you tried to redownload it?   How are you loading it the that USB stick?
