### ISSUE TITLE
Boot process stuck on loading rootfs.cpio.xz

### ISSUE THREAD

**Issue by Justas-S** [Drive-Trust-Alliance/sedutil#345]
**SSD**: KINGSTON SUV500M
**Sedutils rescue**: RESCUE64-1.15.1.img
**Sedutils PBA**: UEFI64-1.15.1img

I have setup the drive following the instructions from the [wiki](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive).
Booting to the rescue and then executing `linuxpba` works, however if I boot directly into the pba stored on the encrypted partition everything stops at `Loading rootfs.cpio.xs`. The "OK" never appears(as opposed to #158). I have waited for < 5 minutes, but when booting from rescue it is almost instant.

I have tried setting `loglevel=9` but there is no additional output. I assume that makes sense because rootfs never loads.

**Comment by ChubbyAnt** [comment]
You can try this SEDutil fork:

https://github.com/ChubbyAnt/sedutil

Which uses an updated syslinux version that solves the problem you experienced in some computers. Note, this ChubbyAnt fork is not compatible with original SEDutil due to the implementation of enhanced password hashing (SHA512).

**Comment by Justas-S** [comment]
Thanks for the answer, however I already changed my setup to use [rear](https://github.com/rear/rear) and that PBA seems to work fine.
