### ISSUE TITLE
Failing to initialize Kingston A2000 NVME SSDs

### ISSUE THREAD

**Issue by berthans** [Drive-Trust-Alliance/sedutil#348]
Hello,

my setup is as follows:

**Mainboard**: MSI MAG Tomahawk B550 (MS-7C91)
**BIOS version**: E7C91AMS.A30 09/03/2020
**Boot**: pure UEFI, no compatibility mode or anything
**Rescue Image**: RESCUE64-1.15.1.img (I also tried the ChubbyAnt fork)
**Disks**: 2x Kingston A2000 NVMe PCIe M.2 SSD (250GB/500GB), Samsung EVO 860 SATA SSD 2TB

Exemplary command outputs working on /dev/nvme0
[scan.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/5761814/scan.txt)

```
(read/typed manually as I could not pipe the output to a file)
# sedutil-cli --scan
Scanning for Opal compliant disks
/dev/nvme0  2   KINGSTON SA2000M8250G           S5Z42105
/dev/nvme1  2   KINGSTON SA2000M8500G           S5Z42105
/dev/sda    2   Samsung SSD 860 EVO 2TB         RVT04B6Q
/dev/sdb   No
Segmentation fault
```

[initialsetup.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/5761812/initialsetup.txt)
```
# sedutil-cli --initialsetup debug /dev/nvme0
method status code NOT_AUTHORIZED
Session start failed rc = 1
One or more header fields have 0 length
EndSession Failed
takeOwnership failed
Initial setup failed - unable to take ownership
```

[initialsetup_vvvvv.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/5761803/initialsetup_vvvvv.txt)
[printdefaultpassword.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/5761816/printdefaultpassword.txt)
```
# sedutil-cli --printdefaultpassword
MSID: MSIDMSIDMSIDMSID
```

The Samsung SATA SSD works just fine; --initialsetup, installing the shadow MBR and booting into it works without problems so far (only tried with default password though).
But the Kingston drives do not work, as you can see from the above output/attached files. What did work was doing a PSID reset on one of them, but that didn't change anything.
Both drives also show up as OPAL compatible in the Kingston SSD manager under Windows 10.

Any help to make these work is much appreciated. If I can provide any more input please let me know

**Comment by berthans** [comment]
Here is some more info. I also found this:
https://www.reddit.com/r/MSI_Gaming/comments/f8rtc7/psa_msi_removed_efi_storage_security_command/
So it might be the MSI board at fault. I updated the BIOS to the latest version (12/29/2020) but to no avail.

```
# sedutil-cli --query /dev/nvme0
/dev/nvme0 NVMe KINGSTON SA2000M8250G                    S5Z42105 50026B76844B99E6    
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = N, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = Y, Alignment Granularity = 1 (512), Logical Block size = 512, Lowest Aligned LBA = 0
SingleUser function (0x0201)
    ALL = N, ANY = N, Policy = Y, Locking Objects = 9
DataStore function (0x0202)
    Max Tables = 10, Max Size Tables = 10485760, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x0888, Initial PIN = 0x0, Reverted PIN = 0x0, comIDs = 1
    Locking Admins = 4, Locking Users = 9, Range Crossing = N
**** 1 **** Unknown function codes IGNORED 

TPer Properties: 
  MaxComPacketSize = 32256  MaxResponseComPacketSize = 32256
  MaxPacketSize = 32236  MaxIndTokenSize = 32200  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxSessions = 1
  MaxAuthentications = 14  MaxTransactionLimit = 1  DefSessionTimeout = 300000
  MaxSessionTimeout = 0  MinSessionTimeout = 5000
Host Properties: 

  MaxComPacketSize = 2048  MaxPacketSize = 2028  MaxIndTokenSize = 1992
  MaxPackets = 1  MaxSubpackets = 1  MaxMethods = 1
```
[query_vvvv.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/5789364/query_vvvv.txt)

**Comment by r0m30** [comment]
Some vendors have started to ship there drives with the ADMIN SP active and need a PSID revert before you can activate OPAL.  There is a danger of data loss if the firmware is not properly coded.
