### ISSUE TITLE
Advice for compatible HD backup unit

### ISSUE THREAD

**Issue by lellis1936** [Drive-Trust-Alliance/sedutil#349]
Not really an issue with sedutil, but I am having a hard time replacing my existing external backup HD with a sedutil-compatible model.  I need more space.

Thus far, the only HD models I've been able to find currently that I *think* are compatible are the Seagate Exos enterprise models.  It looks to me as if all other Seagates no longer have TCG-Opal compliance.

Just wondering if anyone else is having luck finding TCG-Opal on conventional drives.

It looks as if the failure of many manufacturers to securely implement TCG has done some damage :(

**Comment by r0m30** [comment]
I haven't looked for a new drive in a while, so no help here.  Yes, the poor implementations have hurt acceptance.
