### ISSUE TITLE
The current state of SED security?

### ISSUE THREAD

**Issue by dardoor** [Drive-Trust-Alliance/sedutil#351]
As you probably know, a couple of years ago a report has come out that listed some SED vulnerabilities. Microsoft and others advised users to not use hardware encryption and so on. ([Example news article.](https://www.helpnetsecurity.com/2018/11/06/self-encrypting-ssds-vulnerable/))
Does anyone know if these issues were patched with firmwares and/or if they affect the common SSDs nowadays, like the Samsung 9xx drives and such?

(If this is too off-topic here I apologize and I'd appreciate if someone can point me to other resources/forums where this is being discussed.)

**Comment by r0m30** [comment]
It's not off topic but I have no knowledge of what changes drive vendors make to their firmware.  Sorry.
