### ISSUE TITLE
Not downward compatible? 1.15 -> 1.12

### ISSUE THREAD

**Issue by LudiusMaximus** [Drive-Trust-Alliance/sedutil#357]
I tried the newest version of the rescue image (RESCUE32-1.15-5ad84d8.img.gz) to remove the lock and mbr from a Samsumg 840 EVO. But I always got "AUTHORIZATION FAILED" errors, when trying -–disableLockingRange, –-setMBREnable or –-revertnoerase.

Luckily, I still had the Rescue-1.12.img I used to setup the encryption 5 years ago. Booting from a stick with this, --revertnoerase worked out of the box.

Is such a lack of downward compatibility a known issue?
If no, what have I been doing wrong?
If yes, where would people still be able to download Rescue-1.12.img?
All I could find online are the source files: https://github.com/ChubbyAnt/sedutil/releases/tag/1.12

**Comment by r0m30** [comment]
The fork created by @ChubbyAnt changed the password hashing algorithm and is incompatible with this codebase.

**Comment by LudiusMaximus** [comment]
All right. Seems like I was not able to find the executable releases for this original repo of sedutil back then. If I had used the current build found [here](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Executable-Distributions), I would not have had this issue. Somehow I must have missed that I was downloading the release from a completely different fork. :-)
