### ISSUE TITLE
Encrypting a non boot device

### ISSUE THREAD

**Issue by lburgazzoli** [Drive-Trust-Alliance/sedutil#358]
I have the following set-up:
- nvme0 Samsung 970 Evo Plus
- nvme1 WDC SN379

nvme1 is the non encrypted boot disk where the operating system (fedora) is installed and nvme0 is the disk I want to use as my user home and where I want to enable encryption.

I found out on the [ArchLinux Wiki](https://wiki.archlinux.org/index.php/Self-encrypting_drives#Encrypting_a_non-root_drive)  that enabling encryption is about running a single command but it lacks any information how to unlock the disk at boot: is that possible ?

**Comment by rustPyth** [comment]
I made a video a few weeks ago for how to use seutil , I have not edit the video yet, I might edit it this week or next week.

**Comment by valdar** [comment]
@rustPyth I'd be interested into the video as well.

**Comment by tigaente** [comment]
Are there any updates on this? I have the same setup as the original poster:
/dev/sda holding the OS including /boot
/dev/sdb holding /home

Encrypting /dev/sdb works fine when following the documentation, but of course the PBA never loads because /dev/sdb is not the boot device. Are there other ways to unlock a non-boot drive on boot?

**Comment by r0m30** [comment]
You have several options.  One you could setup the data drive per the instructions and then set it a your default boot device.  When the pba reboots the drive will be unbootable and your bios should try to the next boot device (your Linux disk.)
---or----
You could modify your init script to prompt you for the password and then execute the commands to unlock the drive before it mounts any of the filesystems on the OPAL encrypted drive.

The second option would not require a reboot and would be my choice.
