### ISSUE TITLE
Unable to PSID Revert

### ISSUE THREAD

**Issue by rspotoaz** [Drive-Trust-Alliance/sedutil#36]
Seagate ST91000642SS 1TB SED SATA HDD.

Hi, I am unable to revert a Segate SED HDD.  1st attempt produces:

- 16:21:52.253 ERR : method status code INVALID_FUNCTION

A 2nd attempt produces:

- 16:22:11.933 ERR : method status code SP_BUSY
- 16:22:11.933 ERR : Session start failed
- 16:22:11.958 ERR : One or more header fields have 0 length
- 16:22:11.958 ERR : EndSession Failed

Also, a --scan doesn't show yes or no, but "E":

/dev/sdb   E ST91000642SS     0004

--query shows:

Locking function (0x0002)
    Locked = N, LockingEnabled = Y, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y

Both verbose outputs attached.  Note that the command works fine on a Hitachi drive.

[sed-invalidfunction.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/217903/sed-invalidfunction.txt)
[sed-sp_busy.txt](https://github.com/Drive-Trust-Alliance/sedutil/files/217904/sed-sp_busy.txt)

**Comment by r0m30** [comment]
The E means that the drive is a TCG Enterprise drive, not a TCG Opal drive.  The Enterprise drives don't all support the revert command.  You can try to use the PSIDrevertAdminSP command (same syntax as the PSIDrevert command) or the revertLockingSP command (same  syntax as the revertTPer command.)

If neither of these work then you will have to see if the vendor use the Seagate utility to revert the drive.

**Comment by rspotoaz** [comment]
Thank you for the reply!  Trying --PSIDrevertAdminSP gives me an invalid command line argument.

# ./sedutil-cli --PSIDrevertAdminSP 01EUJ3KBWEQJJYPTVNW2N2MUNEYMQ967 /dev/sdc
- 17:31:55.893 ERR : Invalid command line argument --PSIDrevertAdminSP

The --revertLockingSP attempt (and the revertTPer) both give me session authenticate failures.  I've double checked the PSID as well.

# ./sedutil-cli --revertLockingSP GJP98UTF28QWJ9CLU5ZVMWRPJEBYRUQ9 /dev/sde
- 17:34:28.097 ERR : Session Authenticate failed (response = false)

Looks like I'm SOL here unless something else catches your eye.

Again, thank you for the response!

**Comment by r0m30** [comment]
Sorry about that, the code is in the repo but I haven't built a new set of executables yet.  We are doing a lot of development right now and I was waiting until that was done before doing the new release.  

Yes, you will get authentication failures because the PSID User isn't defined in the Admin SP like it is for OPAL compliant drives.

You are using Linux, the build process isn't that difficult for Linux, to build the CLI you just need to clone the repo, cd to sedutil/linux/CLI and make CONF="Release_x86_64" for a 64 bit build or make CONF="Release_i686" for a 32 bit build. If you aren't comfortable with that then you need to find a Windows machine and use the utility supplied by Seagate.

**Comment by rspotoaz** [comment]
Thank you again r0m30.  I've compiled the latest repo and the command is found now.  Different message this time :)

./sedutil-cli --PSIDrevertAdminSP 1X6VLFJQCH4U96DXX3DX1GX88QTY6J9X /dev/sdc
- 21:19:38.103 ERR : method status code INVALID_FUNCTION

Would you say I'm stuck w/ SeaTools?

**Comment by r0m30** [comment]
It looks like it, I'll send a note to the guy who contributed a lot of the enterprise support and see if he will weigh in.

**Comment by r0m30** [comment]
Daniel says:

> For the Seagate drives we use (or anything except HGST), the following works:
> sedutil-cli PSIDrevert ${PSID} ${DEVICE}
> 
> For HGST use PSIDrevertAdminSP.

So it looks like you shouldn't need SeaTools.  You may want to triple check your PSID.

**Comment by rspotoaz** [comment]
Thank you r0m30 and Daniel, I will double check my PSIDs and run some more testing w/ the latest code.  Appreciate the responses and assistance..

**Comment by epaul1967** [comment]
> Thank you r0m30 and Daniel, I will double check my PSIDs and run some more testing w/ the latest code. Appreciate the responses and assistance..

Did you solve the issue? I have same problem with enterprise drive

**Comment by r0m30** [comment]
Psi D revert is not a part of the enterprise spec. Some vendors have implemented it in their enterprise drives but documentation is sparse to nonexistent.
