### ISSUE TITLE
This peace of shit does not work

### ISSUE THREAD

**Issue by tz4678** [Drive-Trust-Alliance/sedutil#360]
Tested with EVO 980. Are there working alternatives? Thank u!

**Comment by tz4678** [comment]
sdd device: evo 980
motherboard: asus prime b450m-a
secure boot: disabled

Result:

select bootable device

**Comment by tz4678** [comment]
i wrote pba on usb stick and boot from it.

**Comment by wiccan2** [comment]
Unfortunately this version does not work with AMD processors.

I ended up using this fork instead: https://github.com/ChubbyAntlll/sedutil

This repo hasn't been updated since 2017, the one I linked is under active development and works quite well with my HP Laptop with a Ryzen CPU.

**Comment by r0m30** [comment]
I have no desire to help or communicate with you. PLEASE GO AWAY!
