### ISSUE TITLE
Is using a TPM for storing the DEK a supported scenario?

### ISSUE THREAD

**Issue by jimkoen** [Drive-Trust-Alliance/sedutil#361]
Hello,
from what I can tell, the Data Encryption Key that is used to encrypt the device is only released once there has been a succesful pre-boot authentication, **that is password based.**

As far as I know, Bitlocker uses inbuilt Trusted Platform Modules if available to store the Encryption Key, which enables a passwordless unlock of the drive.

Is that a scenario that is supported by sedutil?

**Comment by r0m30** [comment]
No, the code is specifically written to NOT require or use the TPM.  TPMs seen to be headed towards a requirement so it may be worth looking into but at this point it is very low priority.
