### ISSUE TITLE
Micron 5300  sed drive doesn't work with SedUtils

### ISSUE THREAD

**Issue by marsyang1206** [Drive-Trust-Alliance/sedutil#362]
Micron 5300 is SATA sed drive and I encountered the issue with the option "initialsetup". 
The following message is from the drive after the verbose option is enabled.

<< IF_SEND>>
1	( F2 ) Start_Name
15	( AE ) 53 65 73 73 69 6F 6E 54 69 6D 65 6F 75 74 ("SessionTimeout")
3	( 82 ) 60000 (EA60h)
1	( F3 ) End_Name
.......

<< IF_RECV >>
ComPacket.extendedComID    07FE0000
ComPacket.outstandingData  00000000
ComPacket.minTransfer      00000000
ComPacket.length           00000000
Packet.TSN                 00000000
Packet.HSN                 00000000
Packet.seqNumber           00000000
Packet.ackType             00000000
Packet.acknowledgement     00000000
Packet.length              00000000
DataSubPacket.kind         00000000
DataSubPacket.length       00000000
0000 00000000 07fe0000 00000000 00000000  ................ 
0010 00000000  

I tried to remove the property "SessionTimeout" during session startup, the modified code work for this drive.
it seems adding the "timeout" property is not compatible for SSC-E SED drives. from the comment of the code, it seems it is workaround to keep the session longer.
I am wondering if we can have the option to add the timeout property instead of applying this property for SSC-E drives.
Please advise.

thanks.

**Comment by r0m30** [comment]
The timeout parameter is in the enterprise spec.  I'm not sure what your issue is.  I seem to have misplaced my enterprise drive so I don't think I'm going to be much help.

**Comment by marsyang1206** [comment]
The timeout parameter is optional in the spec. and not all drive vendors implemented it.
Micron 5300 enterprise drive is one of the examples. 

from the current implementation, the timeout parameter w/ the fixed default value(60000) is added to Session Start commands if it is enterprise SED.
However, the drive may reject the commands or no response is sent out, like Mircon 5300. the session won't be initiated successfully.

Below is the piece of code snippet from DtaSession.cpp.
	if (d->isEprise()) {
		cmd->addToken(OPAL_TOKEN::STARTNAME);
		cmd->addToken("SessionTimeout");
		cmd->addToken(60000);
		cmd->addToken(OPAL_TOKEN::ENDNAME);
	}
The suggestion is to use the option from the command line to set up the timeout value or disable timeout parameter.
It will be more flexible to users and support more SED drives.

I have some code ready and can submit them if you think it is the good idea.

thanks.

**Comment by r0m30** [comment]
Ahh, I wasn't aware that it was optional. When the code was implemented it originally had the time out parameter for all SSC types. It failed on opal drives because it's not in the spec. ￼ The code you see is the compromise we came up with. If you submit a poll request make sure that you submit a signed contributors agreement assigning copyright to us.￼
