### ISSUE TITLE
Unable to unlock a Samsung SSD 970 EVO Plus NVMe drive

### ISSUE THREAD

**Issue by bertogg** [Drive-Trust-Alliance/sedutil#364]
I'm not sure that this is actually a problem with sedutil but I'd appreciate any suggestion.

I have a laptop with a Samsung SSD 970 EVO Plus NVMe drive.

A password for the drive was set in the BIOS and as soon as the computer is turned on it asks for it ("Samsung SSD 970 Evo Plus 500GB - Enter User password:").

I don't have the password so after failing to enter it three times the computer locks the drive. I can boot Linux from a USB stick and the drive is visible under /dev/nvme0 but any attempt to read data from it results in an I/O error.

This is the output of `sedutil-cli --query /dev/nvme0`

```
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = N, LockingSupported = Y, MBRDone = N, MBREnabled = N, MBRAbsent = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = Y, Alignment Granularity = 8 (4096), Logical Block size = 512, Lowest Aligned LBA = 0
DataStore function (0x0202)
    Max Tables = 9, Max Size Tables = 10485760, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x1004, Initial PIN = 0x00, Reverted PIN = 0x00, comIDs = 1
    Locking Admins = 4, Locking Users = 9, Range Crossing = N
Block SID Authentication function (0x0402)
    SID Blocked State = Y, SID Value State = N, Hardware Reset = Y
Namespace function (0x0403)
    Maximum Key Count = 9, Unused Key Count = 8, Maximum Ranges Per Namespace = 8

```
I tried with a PSID revert but it didn't seem to have any effect. Samsung Magician also didn't help.

**Comment by r0m30** [comment]
When the drive password was set it activated the older ATA security.  Sedutil will not help you.
