### ISSUE TITLE
Lenovo Y700 or NVMe Incompatability

### ISSUE THREAD

**Issue by adamsmd** [Drive-Trust-Alliance/sedutil#38]
I have not been able to get any parts of sedutil to work.

I have a Lenovo Y700 Touch-15ISK on which I have installed a Samsung PM951, which uses NVMe.

I am using the copy of `sedutil-cli` from `sedutil_LINUX.tgz` and `UEFI64_Release.img` from `UEFI64_Release.img.gz` that are linked from https://github.com/Drive-Trust-Alliance/sedutil/wiki/Executable-Distributions

Note that the PM951 appears as /dev/nvme0n1 in Linux and /dev/sda is a secondary HDD.

### Using `secutil-cli`
It seems `secutil-cli` is not able to talk to or detect the PM951 on `/dev/nvme0n1`.

Query fails to talk to it.
```
# I wasn't sure if 'query' wanted /dev/nvme0 or /dev/nvme0n1 so I tried both.
$ sudo ./sedutil-cli --query /dev/nvme0
NVME Security Command Error:8194
- 13:45:34.633 ERR : Invalid or unsupported disk /dev/nvme0

$ sudo ./sedutil-cli --query /dev/nvme0n1
NVME Security Command Error:8194
- 13:45:46.106 ERR : Invalid or unsupported disk /dev/nvme0n1
```

Scan fails to find it.
```
# Note that the PM951 is not found by 'scan'. Only the HDD on /dev/sda is found.
$ sudo ./sedutil-cli --scan

Scanning for Opal compliant disks
/dev/sda No  WDC WD10SPCX-24HWST1                     02.01A02
No more disks present ending scan
```

### Testing the PBA
I tried testing the PBA with the instructions at https://github.com/Drive-Trust-Alliance/sedutil/wiki/Test-the-PBA

My system is configured to boot with UEFI and I turned off Secure Boot to be able to boot the PBA.

First, I installed the PBA to a USB drive with: `sudo dd if=UEFI64_Release.img of=/dev/sdb`

When booting to that USB drive, the first password prompt appears. After entering dummy text (I used "asdf"), it immediately reboots the entire machine which then proceeds boot into Ubuntu.  The scan and second password prompt never appear (though it is possible they flash by to quickly for me to see.)

If during that reboot I have it boot to the USB drive again, the first password prompt again appears.

### System Specs
Machine: Lenovo Y700 Touch-15ISK
Model: 80NW0017US

BIOS/UEFI version: CDCN35WW (I am booting in UEFI mode.)

OS: Ubuntu 16.04 (preview)
Output of `uname -a`:
 `Linux spiritus 4.4.0-18-generic #34-Ubuntu SMP Wed Apr 6 14:01:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
Kernel boot parameters: I added `libata.allow_tpm=1` to the kernel parameters in Grub.  Without that `sedutil-cli` exits with an error about `libata.allow_tmp` not being set to `1`.

SSD (added by me):
 `Samsung PM951 512GB M.2 NGFF PCIe Gen3 x4, NVME Solid state drive SSD, OEM (2280) ( MZVLV512HCJH-00000)`
Linux Device: `/dev/nvme0n1`
Output of `lshw`:
```
        *-pci:4
             description: PCI bridge
             product: Sunrise Point-H PCI Express Root Port #9
             vendor: Intel Corporation
             physical id: 1d
             bus info: pci@0000:00:1d.0
             version: f1
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:126 ioport:3000(size=4096) memory:94000000-940fffff
           *-storage
                description: Non-Volatile memory controller
                product: Samsung Electronics Co Ltd
                vendor: Samsung Electronics Co Ltd
                physical id: 0
                bus info: pci@0000:0a:00.0
                version: 01
                width: 64 bits
                clock: 33MHz
                capabilities: storage pm msi pciexpress msix nvm_express bus_master cap_list
                configuration: driver=nvme latency=0
                resources: irq:0 memory:94000000-94003fff ioport:3000(size=256)
```

**Comment by r0m30** [comment]
I can't find anywhere in the Samsung Documentation that says the PM951 supports OPAL.  The Nvme support is contributed and I haven't yet been able to find a retail Nvme drive that supports OPAL, so I'm relying on the contributor to do the testing.  

The issue with the scan is that it loops through the /dev/sd* devices, that will need to be changed.

**Comment by adamsmd** [comment]
Affeter a  hours of investigation, I have found the following.

(1) I have also not found any documentation indicating whether the PM951 is self encrypting.

(2) However, the Nvme specification says that all Nvme devices support 'Security Discovery', so the `sedutil --query` should work even if the drive doesn't support encryption.

(3) The Nvme specification says that discovery is done with a Protocol of 0 and a security protocol (SP) Specific Field of 0.  (Section 5.14.2 of http://www.nvmexpress.org/wp-content/uploads/NVM-Express-1_1b.pdf)  However, in sedutil, `DtaDev::discovery0` calls `sendCmd` with 0x01 and 0x0001.  Maybe I am misunderstanding something, but shouldn't those be 0x00 and 0x0000?

To test this, I tried to compile sedutil with 0x00 and 0x0000, but I was unable to get it to build.  `linux/stddef.h` defines `enum { false = 0, true = 1};` which is an error in C++ since `false` is a keyword.  I tried to hack around that problem, but was unable to find a workaround to get sedutil to build.

**Comment by r0m30** [comment]
If the drive isn't OPAL why would you expect sedutil to support the drive?

The command that sedutil issues is a TCG command (Discovery 0) that asks the drive to return a blob that describes the supported TCG functionality.  If the command fails then I assume that the drive doesn't support OPAL and move on.  I make no effort to support the NVMe Discovery command.  Isn't is wonderful how the same word means something completely different depending in the spec.

I can't comment on you compile issues, it works here and the code has been packaged for RedHat and Arch.  Are you using clang and not gcc?

**Comment by adamsmd** [comment]
I was mostly trying to get the drive to report whether it did support OPAL by trying to get it to list its supported protocols.  I will tinker around with that on my own and close this ticket.

That probably makes the compile errors are probably moot at this point, but if you wanted to know, I am compiling on Ubuntu 16.04 with GCC 5.3.1.
