### ISSUE TITLE
Samsung 980 Pro: method status code NOT_AUTHORIZED

### ISSUE THREAD

**Issue by alci63** [Drive-Trust-Alliance/sedutil#387]
I'm following the procedure at https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive

sedutli-cli --scan : OK (2)
linuxpba : OK (is OPAL NOT LOCKED)
sedutil-cli --initialsetup debug /dev/nvme0 : FAILS

output says:

method status code NOT_AUTHORIZED
Session start failed rc = 1
One or more header fields have 0 length
EndSession failed
takeOwnership failed
Initial setup failed - unable to take ownership

Any idea ?

**Comment by alci63** [comment]
Ok, I fixed this by resetting the drive with PSID:

sedutil-cli --yesIreallywanttoERASEALLmydatawithPSID FFFFFFFF(very long sequence found on the disk physical albel)FFFFF /dev/nvme0

Then I restarted the whole procedure and it seems it worked.

**Comment by alexisfrjp** [comment]
I had the same problem, thanks!
