### ISSUE TITLE
Additional reboot required to boot from TCG Opal drive after PBA unlocks it

### ISSUE THREAD

**Issue by fnunez1985** [Drive-Trust-Alliance/sedutil#398]
Hi everyone,

I just wanted to ask if anybody has seen this behaviour before. I am using Samsung 850 PRO with TCG Opal support. I have followed the guide here:
https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive

I have now my system locked, PBA (UEFI64) installed, etc. All good, no issues there. I can see how my system boots to DTA Linux PBA, I enter the password and the Opal disk is unlocked fine. The problem is that after the drive is unlocked, the PBA says:
"Starting OS"
![image](https://user-images.githubusercontent.com/73228896/164704684-9b0bc79d-fa1e-49e4-8da1-0c71feb863e7.png)
But nothing happens after that. I assumed the PBA would do a reset and the system would boot normally the OS as the drive is unlocked at that stage. However the system never reboots and I have to manually force a reset to boot the unlocked drive. Is this expected? If not, can it be fixed to auto reboot after unlock?

Thanks in advance!

**Comment by JaBoMa** [comment]
Hi @fnunez1985 
Have you seen the following thread: [https://github.com/Drive-Trust-Alliance/sedutil/issues/375](url) ?
Unfortunately it is also still open issue.
ATB
J.B.M.

**Comment by fnunez1985** [comment]
Thanks @JaBoMa , using this other fork [here](https://github.com/ChubbyAnt/sedutil) worked as suggested in that other issue you referred me to. I can close this one as the other is open.
