### ISSUE TITLE
Would it be possible to get this working on a Mac OSX 10.11 El Capitan 850 EVO drive when running the sedutil command from linux?

### ISSUE THREAD

**Issue by Pseudonomy** [Drive-Trust-Alliance/sedutil#40]
Got inspiration from this post, which lacks clear steps to get it working: http://www.tonymacx86.com/mavericks-desktop-support/176366-tcg-opal-os-x-working-free-hardware-encryption-paranoid.html

I'm stuck at the step `Installing the msed PBA` in this guide: https://vxlabs.com/2015/02/11/use-the-hardware-based-full-disk-encryption-your-tcg-opal-ssd-with-msed/

What would be the equivalent option on osx El Capitan?

Is it possible to use the sedutil command from inside linux on a mac osx ssd drive (850 EVO)?

**Comment by r0m30** [comment]
Are you running a "real" Mac or a H@ck?
None of the "real' Macs have ssds that support OPAL so the only possible use of OPAL drives would be for USB attached drives.  We are currently working on getting out software working in the OSX.
I

**Comment by sdca** [comment]
The first link confirms that the PBA works on Clover/Hack installs.

On a real Mac you could try booting the sedutil Rescue image from a flash drive. Or another linux live ISO like Ubuntu with 'libata.allow_tpm=1' set on the fly in GRUB (press 'e' at startup). There's no need to install the operating system.

**Comment by Thireus** [comment]
@r0m30, any luck for USB attached drives on macOS?
