### ISSUE TITLE
Happy Path to loose your data

### ISSUE THREAD

**Issue by Zetanova** [Drive-Trust-Alliance/sedutil#405]
I am not new to sedutils-cli and using it for around 50-100 data-drives since 2017

Because my old local temp drive with 120GB got full, I bought 2 weeks ago an Samsung 870 512GB 
and full-encrypted it with the old version `sedutils-cli 1.15`
It worked as normal, but I am not so sure if I ever power-cycled the drive. 
I think I just rebooted for win10 updates.

Yesterday I had a power out and after bootup it is not possible for be to unlock the drive.
ChubbyAnt `sedutils-cli 1.15` is reporting the drive as not SED capable anymore
and the current release  `sedutils-cli 1.20` reports it as SED capable but is unable to unlock it 'NOT_AUTHORIZED'

I think that the hasing algo just changed between the versions
and now I am not able to get the old hash from ChubbyAnt `sedutils-cli 1.15' 
because it detects the drive as not capable. 

I will try change/extend the code to print out the hashed password to be able to backup it 
and/or use it with the `-n` parameter

**Comment by Zetanova** [comment]
I don't know why CaddyAnt's build could not detected the Samsung 870 as OPAL capable 

First I tried to create the sha512 version in c#, but the sedutil-cli `-n` option is flowed.
The `-n` option takes the password from the command args without any text processing
and it is impossible to pass a binary hashed password to sedutil-cli.

After I just forked and moded this repo and could until my drive
https://github.com/zetanova/sedutil/

**Comment by r0m30** [comment]
If you mix forks, you are asking for trouble. Several forks have changed the hashing algorithm in an incompatible way.

**Comment by Zetanova** [comment]
The issue is that currently its not possible to view or set hashed-password.
Two simple commands would be sufficient, one to print a given password as hashed base64 string and one that takes a already hashed binary password as base64

**Comment by Artoria2e5** [comment]
Could be a good idea to lead with *that* in your issue...
