### ISSUE TITLE
removed

### ISSUE THREAD

**Issue by sedut-pank** [Drive-Trust-Alliance/sedutil#418]
removed

**Comment by JaBoMa** [comment]
Well, the use of the characters "%" and "$" in the password, which have special functions in the command interpreter, was not very reasonable. What can I advice? Next try with double quote separated password? 

What version of the rescue system image do you use?

Anyway, before executing the disableLockingRange command, I advise you to execute the following commands:

sedutil-cli --setLockingRange 0 RW <_YourAdmin1password_> <_YourDevice_>
sedutil-cli --setMBREnable OFF <_YourAdmin1password_> <_YourDevice_>

This will help confirm if the system has a password issue.

**Comment by gohrner** [comment]
> Well, the use of the characters "%" and "$" in the password, which have special functions in the command interpreter, was not very reasonable.

If quoted with apostrophs as in the second pasted command line:

> `sedutil-cli --disableLockingRange 0 'STARS%%$$' /dev/sda`

this should not hurt - special meaning should be disabled. (The first command line will definitely fail, though - `$$` is substituted by the shell's pid number, totally changing the password of course...)

It's extremely important to actually use apostrophs for escaping, not (similarily looking) French accent characters!

Different keyboard layout might be an issue, but I think both PBA and rescure system normally use English layout?

**Comment by sedut-pank** [comment]
> Anyway, before executing the disableLockingRange command, I advise you to execute the following commands:
> 
> sedutil-cli --setLockingRange 0 RW <_YourAdmin1password_> <_YourDevice_> sedutil-cli --setMBREnable OFF <_YourAdmin1password_> <_YourDevice_>
> 
> This will help confirm if the system has a password issue.

Both commands gave an answer:
method status code NOT_AUTHORIZED
Session start failed rc = 1
EndSession Failed

Unable to set setMBRDone on
Unable to set MBRDone

Used password 'STARS%%$$'.
The terminal is in English only. 

I use RESCUE64.img.gz, I hope this is not a problem?
https://github.com/Drive-Trust-Alliance/sedutil/wiki/Executable-Distributions

**Comment by sedut-pank** [comment]
Cheers! I was able to solve the problem.

I was using the version RESCUE64-1.15-5ad84d8.img from the github repository - it had errors.

I downloaded the RESCUE64 version, the commands worked on it and I successfully booted into the system.

Can you tell me if I need to update my image to the UEFI64.img version and force opal to work with the new bios version?
sedutil-cli --loadPBAimage password pba_file drive

**Comment by gohrner** [comment]
@sedut-pank: You changed the issue description to "removed", but didn't close this issue - if it's obsolete, if would be good to close / cancel it, if you can.

**Comment by JaBoMa** [comment]
It would be better, for future searches for solutions to other users' problems, to restore the "removed" content describing the problem from this thread. If it is possible yet, of course.
