### ISSUE TITLE
Typos - / -- thus command's parameters formatting bugs on Wiki pages

### ISSUE THREAD

**Issue by gomoku** [Drive-Trust-Alliance/sedutil#42]
Hello,
as I already mentioned in the: 

https://github.com/Drive-Trust-Alliance/sedutil/issues/37

**I found another command formatting bug on Test-the-Rescue-system guide page:**

https://github.com/Drive-Trust-Alliance/sedutil/wiki/Test-the-Rescue-system

The commands:

> sedutil-cli –scan
> sedutil-cli –query /dev/sda <== chose an OPAL compliant device

throws the command formatting bug:

> ERR : Argument 1 (-scan) should be a command

as on the screnshoot:

<a href="http://s1.dodajfote.pl/2016/05/03/e8f04c240bd3a522189d57b91b14a124.jpg" target="_blank"><img src="http://s1.dodajfote.pl/2016/05/03/e8f04c240bd3a522189d57b91b14a124.jpg" alt="SCREENSHOOT" style="max-width:100%;"></a></p>

Because correctly should be "--scan" & "--query" (double minus sing) as on the screenshoot:

<a href="http://s1.dodajfote.pl/2016/05/03/a031220efe935ea85f362cf607608aa0.jpg" target="_blank"><img src="http://s1.dodajfote.pl/2016/05/03/a031220efe935ea85f362cf607608aa0.jpg" alt="SCREENSHOOT" style="max-width:100%;"></a></p>

**[Edit] I also found another formatting bugs (a little different) on PSID Revert system Wiki page:**

https://github.com/Drive-Trust-Alliance/sedutil/wiki/PSID-Revert

For example if you take a look at any of the commands there like:

> 1. sedutil-cli -–scan <- SCAN to find Opal Drive (you should a 1 or 2 next the the drive)

  you see the 

> -–

(before the "scan")

is malformed like on the screenshoot:

<a href="http://s1.dodajfote.pl/2016/05/03/d35e33ca497775166b3b6927ad77a153.png" target="_blank"><img src="http://s1.dodajfote.pl/2016/05/03/d35e33ca497775166b3b6927ad77a153.png" alt="SCREENSHOOT" style="max-width:100%;"></a></p>

(the first of the minus signs is different than the second one, the first is too short, and the second is too long) thus sometimes when copy & paste to Windows dos command prompt, one of the minus signs gets malformed, and the whole command throws the command formating error - the same like in Test-the-Rescue-system guid page case.

**Comment by r0m30** [comment]
Thanks, I've read the text so many times I can't see what is written because I "know" what it is suposed to say.

I fixed the page so that there are 2 dashes but I have no idea how to markup the text so it copies correctly into the command line.

**Comment by gomoku** [comment]
> but I have no idea how to markup the text so it copies correctly into the command line.

Hmm maybe it is malformed already on the webpage and not after copy & paste? As shouldn't be both minus signs equal length? I just checked in Opera and they are malformed too. Are they malformed for you too?

**Comment by r0m30** [comment]
Yes it's malformed on my system too, I looked a the markdown stuff here and even when I say that the command is code it's still malformed.

**Comment by gomoku** [comment]
I just checked now (after you added the missing minus signs):
https://github.com/Drive-Trust-Alliance/sedutil/wiki/Test-the-Rescue-system

and it malformed there too, but in the opposite direction (the first minus sign is the long one, and the second is the short one:

<a href="http://s1.dodajfote.pl/2016/05/09/74cb1cc4ac4318412d3892fa5bab6783.png" target="_blank"><img src="http://s1.dodajfote.pl/2016/05/09/74cb1cc4ac4318412d3892fa5bab6783.png" alt="SCREENSHOOT" style="max-width:100%;"></a></p>

The issue is some nasty glitch.

Maybe try basic repair (I suppose you did, but prefer to be sure):

> Method 1)
> 
> Edit Wiki page. 
> Remove the double-minuses. 
> Save Wiki page. 
> Then edit again, 
> type new double-minuses. 
> Save Wiki page again.
> 

or 

> Method 2)
> 
> Make backup of content of Wiki page (Copy & Paste for. ex. to Notepad + remove all the double-minuses)
> Remove Wiki page.
> Create Wiki page again.
> Copy & Paste the backup back + type new double-minuses.
> Save Wiki page.
> 

If still not working, try to repeat the both methods, but instead of typing new double-minus from keyboard, copy & paste them from "action" from there:

https://github.com/Drive-Trust-Alliance/sedutil/wiki/Command-Syntax

as double-minuses in front of "action" are not malformed there.
