### ISSUE TITLE
Solidigm P44 Pro - According to sedutil it has OPAL 2?

### ISSUE THREAD

**Issue by Utini2000** [Drive-Trust-Alliance/sedutil#447]
I have a Solidigm P44 Pro which should only support AES TCG Pyrite 2.01.
But running sedutil it seems like it also supports OPAL 2.

```
sudo sedutil-cli --scan
Scanning for Opal compliant disks
/dev/nvme0 2 SOLIDIGM SSDPFKKxxxx 001C
No more disks present ending scan 
```

So am I safe to used sedutil do encrypt this NVME?

Thanks!

**Comment by JaBoMa** [comment]
Looks not bad. For any case, try another command yet:

sudo linuxpba

and type **debug** when it asks for the pass-phrase

BR

**Comment by Utini2000** [comment]
```
Drive /dev/nvme0 SOLIDIGM SSDPFKKW020X7                   is OPAL NOT LOCKED
```

That looks good I guess?!

**Comment by JaBoMa** [comment]
Yes, it does look good. Now you can try to follow the "Encrypting your drive" instructions from the "Wiki" tab.
E.g.:

sedutil-cli --initialSetup **debug** /dev/nvme0
sedutil-cli --enableLockingRange 0 **debug** /dev/nvme0
sedutil-cli --setLockingRange 0 LK **debug** /dev/nvme0
sedutil-cli --setMBRDone OFF **debug** /dev/nvme0

   Do the two commands (below), if your disk is designed to boot the system. If not, go to **##**:

sedutil-cli --loadPBAimage **debug** <**_pba-image-path-&-file_**> /dev/nvme0
sedutil-cli --setMBRDone ON **debug** /dev/nvme0

   **##** If your disk is not designed to boot the system (don't do the command below, if your disk is to boot the system): 

sedutil-cli --setMBREnable OFF **debug** /dev/nvme0

**Note:** Try not to reboot your SSD until fulfilling the above step.

It is advised to use the simple pass-phrase, like **debug** (above) for the initial steps. Then you can change it for the real one, using the commands:

sedutil-cli --setSIDPassword **debug** **_new-pass-phrase_** /dev/nvme0
sedutil-cli --setAdmin1Pwd **debug**  **_new-pass-phrase_** /dev/nvme0

Best Regards
JBM

**Comment by Utini2000** [comment]
Thank you! I am currently using dm-crypt with LUKS2 and will first backup everything, remove the LUKS2 decryption and then try using OPAL 2.0 with sedutil. Although I also just read that dm-crypt got support for OPAL 2.0. So this might be an interesting alternative as well.

Thanks for your help so far!

**Comment by Blacklands** [comment]
So those Solidigm drives actually have OPAL support? I was looking for that on their website in the past and couldn't find anything about it, so I dismissed them. I wonder if it's just the "Pro" models? Did you find anything on their website about this? It's weird that they would have full OPAL support and not even advertise it anywhere (not even in the spec sheets)...

**Comment by Utini2000** [comment]
> So those Solidigm drives actually have OPAL support? I was looking for that on their website in the past and couldn't find anything about it, so I dismissed them. I wonder if it's just the "Pro" models? Did you find anything on their website about this? It's weird that they would have full OPAL support and not even advertise it anywhere (not even in the spec sheets)...

Some of their NVME's have official OPAL support according to their website.
But since Solidigm = previous Intel NVME (just under a new name) I could imagine that all of them support OPAL but being allowed to name this kind of support requires a paid certification or so?

Same thing applies to many thing e.g. engine oil.
Sometimes an engine oil has a higher quality but does not state the required certification for you car brand because being allowed to put that certification on the engine oil bottle requires payment from the oil brand.
Some oil brands then just buy the "highest" grade certification (lets say the Ferrari certification) but can't be bothered also buying the "lower" grade certification (e.g. VW, Ford,...). 
Maybe this applies to NVME's too? :D
