### ISSUE TITLE
What is the correct order of steps?

### ISSUE THREAD

**Issue by varnav** [Drive-Trust-Alliance/sedutil#45]
Hello!

What is the correct order of tests to be done? Do I need to test PBA first, or run --initialsetup first?
I thought it worth testing PBA first, but there is info (https://github.com/Drive-Trust-Alliance/sedutil/issues/37#issuecomment-216953287) that this cannot be done before OPAL is enabled.

If testing PBA first I experience issue exactly to this: https://github.com/Drive-Trust-Alliance/sedutil/issues/44

**Comment by r0m30** [comment]
New version and doc should resolve this.
