### ISSUE TITLE
No bootable device

### ISSUE THREAD

**Issue by varnav** [Drive-Trust-Alliance/sedutil#46]
I'm getting "No bootable device" error after completing these steps in Windows 10:

```
sedutil-cli -–initialsetup <password> <drive>
sedutil-cli –-loadPBAimage <password> <pbafilename>  <drive>
sedutil-cli –-setMBREnable on <password> <drive>
```

Samsung 850 EVO SSD with Windows 10 x64 with UEFI

Fix was easy: boot with rescue, issue:
`
sedutil-cli --revertnoerase {Admin1Password} {drive}`

**Comment by r0m30** [comment]
Have you disabled secure boot?

On Tuesday, May 10, 2016, varnav <notifications@github.com> wrote:

> I'm getting "No bootable device" error after completing these steps in
> Windows 10:
>
> sedutil-cli -–initialsetup
> sedutil-cli –-loadPBAimage
> sedutil-cli –-setMBREnable on
>
> Samsung 850 EVO SSD with Windows 10 x64 with UEFI
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Drive-Trust-Alliance/sedutil/issues/46>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ABgA8iWDSGvS0pAMv1fb8ZtAuFjLxrgxks5qANLWgaJpZM4IbZR0>
> .
>


-- 
-----
r0m30

**Comment by varnav** [comment]
Yes, but I did this after running the commands. Is that ok?

**Comment by dtasupport** [comment]
Yes, disabling secure boot after setup should be fine. You loaded the UEFI
PBA correct?  You uncompressed the image too?

On Tuesday, May 10, 2016, varnav <notifications@github.com> wrote:

> Yes, but I did this after running the commands. Is that ok?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Drive-Trust-Alliance/sedutil/issues/46#issuecomment-218263063>
>


-- 
----
Mike

**Comment by varnav** [comment]
All three commands worked without error. Anything I can do to collect diagnostic info?

**Comment by dtasupport** [comment]
Not sure what the problem might be. It's possible your bios isn't
recognizing the structure of the disk image.

The write would work even if you didn't decompress the image.

If you boot the rescue system can you access the drive?

On Tuesday, May 10, 2016, varnav <notifications@github.com> wrote:

> All three commands worked without error. Anything I can do to collect
> diagnostic info?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Drive-Trust-Alliance/sedutil/issues/46#issuecomment-218266926>
>


-- 
----
Mike

**Comment by varnav** [comment]
`fdisk -l` from rescue system lists correct GPT

**Comment by varnav** [comment]
Image was decompressed

**Comment by dtasupport** [comment]
Then it's probably a bios issue. Hard to debug remotely. Doe you hav a link
to the doc for your mobo?

On Tuesday, May 10, 2016, varnav <notifications@github.com> wrote:

> fdisk -l from rescue system lists correct GPT
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Drive-Trust-Alliance/sedutil/issues/46#issuecomment-218271973>
>


-- 
----
Mike

**Comment by varnav** [comment]
Tried everything from scratch. Same problem.

This is HP Pavilion TS Sleekbook 14

**Comment by varnav** [comment]
Anything we can do? I really need drive encryption on this laptop. ;)

**Comment by dtasupport** [comment]
Off the top of my head. Look at the structure of the existing UEFI
partition and try moving/renaming the pieces of the PBA to match that
structure

On Wednesday, May 11, 2016, varnav <notifications@github.com> wrote:

> Anything we can do? I really need drive encryption on this laptop. ;)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Drive-Trust-Alliance/sedutil/issues/46#issuecomment-218443614>
>


-- 
----
Mike

**Comment by gomoku** [comment]
I also have Samsung 850 EVO, and after I've changed my motherboard from GIGABYE GA-B75-D3V (latest bios) to ASROCK H81M (latest bios), can no longer boot from the encrypted SSD, 
because instead of the pass prompt I receive:

> Reboot and Select proper Boot device
> or Insert Boot Media in selected Boot device and press a key_

as shown on:
http://oi46.tinypic.com/35clizd.jpg

Still the same even after I've re-setuped the SSD from Windows by:

> sedutil-cli –-loadPBAimage <password> <pbafilename>  <drive>
> sedutil-cli –-setMBREnable on <password> <drive>
> sedutil-cli –-enableLockingRange 0 <password> <drive>

I temporaily workaround the issue by booting from Rescue Image from USB pendrive,
which does shows the pass promt, thus allows me to enter the pass and unlock the drive.

**Comment by kulfoon** [comment]
> gomoku: I temporaily workaround the issue by booting from UEFI64_Debug.img.gz from USB pendrive,
> which does shows the pass prompt, thus allows me to enter the pass and unlock the drive.

This hack-workaround method no longer works, it does not show the pass prompt anymore, now it shows dead black screen and need to hard reset my pc and then disable locking, yes, sedutil is completely broken on my pc, so I had to disable it.

**Comment by tz4678** [comment]
> > gomoku: I temporaily workaround the issue by booting from UEFI64_Debug.img.gz from USB pendrive,
> > which does shows the pass prompt, thus allows me to enter the pass and unlock the drive.
> 
> (Sedutil 1.12.0) This hack-workaround method no longer works, it does not show the pass prompt anymore, now it shows dead black screen and need to hard reset my pc and then disable locking, yes, sedutil is completely broken on my pc, so I had to disable it.
> 
> And the new version 1.15.1 is completely broken as well because when trying to boot it shows dead black screen with an flashing `_` at the top-left corner, and need to hard reset my pc and then disable locking, yes, sedutil 1.15.1 is completely broken on my pc as well, so I had to disable it as well.

i hate this shit
