### ISSUE TITLE
WD PC SN740 NOT_AUTHORIZED when performing initialstup 

### ISSUE THREAD

**Issue by lburgazzoli** [Drive-Trust-Alliance/sedutil#471]
I'm trying to set-ip a new laptop wich has a WD PC SN740 but when running the `initialsetup`, then I get NOT_AUTHORIZED:

```
method status code NOT_AUTHORIZED
Session start failed rc = 1
One or more header fields have 0 lenght
EndSession Failed
takeOwnership failed
Initial setup failed - unable to take ownership
```

Query reports the the following info:

```
Locking function (0x0002):
  Loked = N. LokingEnabled = N, LockingSupported = Y, MBRDone = N, MedaEncrypt = Y
```

**Comment by Blacklands** [comment]
You could try doing a PSID revert. Some manufacturers (Samsung, for example) now ship their drives in a state where you can't enable OPAL right out of the box, to protect the user from ransomware attacks. Maybe that's the case for your drive (I have no idea). If that's the case, a PSID revert would bring the drive into a state where OPAL can be set up.

**Comment by lburgazzoli** [comment]
@Blacklands yeas, that was the issue. Thx !
