### ISSUE TITLE
How to unlock with one locked disk after reboot

### ISSUE THREAD

**Issue by yizhanglinux** [Drive-Trust-Alliance/sedutil#472]
Hello

I locked my Samsung 840 SSD on linux 6.9-rc4 with[1], after the disk locked, I did dd write operation[2] on the disk, and find the dd operation could not be stopped, then I did a power cycle for the system, after the system rebooted and found the disk was locked from iDRAD and it cannot be recognized on OS, could anyone help how to unlock the disk, thanks advance.

[1]
sedutil-cli --initialsetup password /dev/sdj
sedutil-cli --listLockingranges password /dev/sdj
sedutil-cli --enableLockingRange 0 password  /dev/sdj
sedutil-cli --listLockingranges password /dev/sdj
sedutil-cli --setlockingrange 0 LK  password /dev/sdj

[1]
dd if=/dev/random of=/dev/sdj bs=1M count=10

**Comment by JaBoMa** [comment]
Try to boot from USB memory stick with the Rescue system image burned, and first use:

sedutil-cli –scan

Verify, that your disk is still recognized as /dev/sdj, then use:

sedutil-cli --setMBRDone ON password /dev/sdj
sedutil-cli --setlockingrange 0 RW password /dev/sdj

(providing that it is still /dev/sdj ; if not - adjust the above commands accordingly)

This should unlock your disk once (until next power cycle), providing,that it is not damaged yet.

My advise: read the Wiki first (How to encrypt my drive) before you start damaging what you have bought.
ATB
JBM

**Comment by yizhanglinux** [comment]
Thanks @JaBoMa
Finally I connected the disk by USB, and the disk can be recognized, and I did --disableLockingRange/--revertTPer for the disk, it can be used now.
