### ISSUE TITLE
there is an error when loadPBAimage 

### ISSUE THREAD

**Issue by liuligang** [Drive-Trust-Alliance/sedutil#48]
there is an error when loadPBAimage,the following is my step:

PS C:\Users\admin\Desktop\TCG_Copy\sedutil-master_2\windows\CLI\x64\Debug> .\sedutil-cli.exe --initialSetup 12345678 \\.\PhysicalDrive0
- 14:29:07.000 INFO: takeOwnership complete
- 14:29:08.859 INFO: Locking SP Activate Complete
- 14:29:08.625 INFO: LockingRange0 disabled
- 14:29:09.328 INFO: LockingRange0 set to RW
- 14:29:10.031 INFO: MBRDone set on
- 14:29:10.734 INFO: MBRDone set on
- 14:29:11.437 INFO: MBREnable set on
- 14:29:11.437 INFO: Initial setup of TPer complete on \\.\PhysicalDrive0
PS C:\Users\admin\Desktop\TCG_Copy\sedutil-master_2\windows\CLI\x64\Debug> .\sedutil-cli.exe --loadPBAimage 12345678 C:\Users\admin\Desktop\UEFI64_1\UEFI64_Release-1.12.img \\.\PhysicalDrive0
- 14:30:19.000 INFO: Writing PBA to \\.\PhysicalDrive0
 - [**                   ] 665600- 14:31:22.203 ERR : **Command failed on send 4**
- 14:31:22.203 ERR : **Command failed on exec 4**
PS C:\Users\admin\Desktop\TCG_Copy\sedutil-master_2\windows\CLI\x64\Debug>

It can also be written in a few days ago, but  appear the problem today.I don't know why.
Who encountered this problem???Please give directions. thank you.

My SSD disk is Samsung SSD 850 EVO on WIN 8.
.

**Comment by r0m30** [comment]
The drive is returning an error when we send the command.  This is not a TCG error code but a hardware error code.  I'll have to see if I can find a definition of these codes.

**Comment by liuligang** [comment]
oh, thank you !!!@r0m30 
If you have some ideas about the problem, please let me know.
Thank you again.

**Comment by liuligang** [comment]
Hi，@r0m30 
Sometime  the error is following：

PS C:\Users\admin\Desktop\open\sedutil-master\windows\CLI\x64\Debug> .\sedutil-cli.exe --loadPBAimage 12345678 C:\Users\admin\Desktop\PBA\UEFI64_Relea
se-1.12.img \\.\PhysicalDrive0
- 14:51:48.000 INFO: Writing PBA to \\.\PhysicalDrive0
 \ [********             ] 2575360- 14:57:12.094 ERR : **One or more header fields have 0 length**
- 14:57:12.125 ERR : **Command failed on recv1**
- 14:57:12.141 ERR : **Command failed on exec 1**
- 14:57:12.156 ERR : **EndSession Failed**
PS C:\Users\admin\Desktop\open\sedutil-master\windows\CLI\x64\Debug>

**Comment by liuligang** [comment]
Hi,@r0m30 
The problem has been resolved,I found maybe that is a question of my BIOS Settings.
Although I don't know what  problem is, but I changed to another computer won't appear similar problems.

Thank you again.

**Comment by r0m30** [comment]
Do you have the intel RST drivers installed?  If you do you might try to update them to the latest version, or if you don't need them possibly uninstall them.
