### ISSUE TITLE
UEFI PBA differs from documented testing behaviour

### ISSUE THREAD

**Issue by phizev** [Drive-Trust-Alliance/sedutil#5]
[Encrypting your drive](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive) refers to   [Test the PBA](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Test-the-PBA) as a recommended step. The UEFI PBA behaviour is not the same as the LinuxPBA, and as such differs from the documentation. Initially this caused me some alarm until recalling the project history. I do have the UEFI PBA working correctly, and the rescue image instructions ([Test the rescue system](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Test-the-Rescue-system)) worked for my initial broken set up with the UEFI PBA.

In addition, would it be possible to document the login, and password for the UEFI debug build?

**Comment by snow3461** [comment]
@phizev
Currently trying to setup my laptop whit sedutil and UEFI PBA.
Testing the PBA before sending it to my OPAL drive, behaviour is as you noticed different. What should I expect?
Currently after entering a empty/dummy password, the wholesystem just reboot...

**Comment by r0m30** [comment]
Hi,
The whole linux based PBA system needs to be better documented.
I would suggest testing with the Debug image of the PBA transferred to USB stick.  
What to expect depends on how you have your system configured.  If the drive in not setup (initialsetup) you can expect a NOT_AUTHORIZED error.  If the drive is setup and you enter the correct password you should be told the drive was unlocked.
The Debug image will exit to the command prompt allowing you to see the output from the unlock attempt and the Release image will reboot the machine.

**Comment by snow3461** [comment]
@r0m30 Thanks for your advice.

I tried the debug UEFI PBA to see. My drive is not set up yet. I took a picture of my screen for you to see if this is normal behavior and not specific to my laptop: [Picture](http://tof.canardpc.com/view/f5319cb9-6840-4a93-a0c3-6650d11bd593.jpg)

**Comment by r0m30** [comment]
If your drive is not set up that looks like it should work.  I'm a little concerned about the INVALID_PARAMETER but I think that's because the Locking SP is not active.

Have you tried running a scan from the rescue image?

**Comment by snow3461** [comment]
a scan from the rescue image gives (wrote only usefull info) : 

    /dev/sda/ Opal device 
    /dev/sdb/ Non-Opal HDD
    ERR : Identity failed Invalid argument
    /dev/sdc No
    No more discs

Will try to setup the locking range afet a backup today, will let you know.
