### ISSUE TITLE
How to add user1 authorization to unlock lockingrange0？

### ISSUE THREAD

**Issue by liuligang** [Drive-Trust-Alliance/sedutil#50]
I want to add user1 authorization to unlock lockingrange0.
Who can give me some advice, ideas, or reference documentation?
Thank you!!!

I believe the humans who used samsung hard disk may know the encryption tool-EMBASSY Security Center.  I also want to achieve to increase users like this tool .

**Comment by r0m30** [comment]
This is accomplished by modifying the ACE using the ACE.SET command.  This is not currently implemented in the tools.

**Comment by liuligang** [comment]
Oh, @r0m30 
I know the current code does not support multiple users. But I saw some  commands like  very much.
e.g-setPassword_SUM these commands which with the **_SUM** tag . 

I want to know the function of these commands.

Can you recommend me some reference documentation about add users?
Because I just contact the TCG and don't know much, I think you know more than me.
Thank you very much.

**Comment by r0m30** [comment]
The _SUM commands provide minimal support for the Single User Mode feature.

I used the TCG specifications to figure this stuff out.  The specs are here http://www.trustedcomputinggroup.org/work-groups/storage/

They are are dry as you might expect. 

There is one document that shows the command data flows if you are interested in that.  It's at http://trustedcomputinggroup.org/wp-content/uploads/TCG_Storage_Opal_SSC_Application_Note_1-00_1-00-Final.pdf
