### ISSUE TITLE
Issue Recognizing Samsung 850 Pro As Opal Device on Windows

### ISSUE THREAD

**Issue by gill984** [Drive-Trust-Alliance/sedutil#51]
I'm attempting to unlock a Samsung 850 Pro drive on Windows 7 which I locked in Ubuntu using sedutil. However, sedutil on windows does not seem to recognize my drive as being Opal compliant. When I run a scan command the "PhysicalDrive1" which I determined to be the Samsung SSD is not recognized as an Opal drive. Also when I query the drive it says that the drive is unsupported.

Even when I revert to factory defaults using the PSID command in Ubuntu, sedutil on Windows still does not recognize the drive as being an Opal device.

I also tried only running initialsetup without enabling a locking range and I still had the same issue.

I'm connecting to the drive using an external esata port on the laptop which I unplug and re-plug in to cycle power when needed. I'm attempting to log into the drive "post-boot", so I am running the commands using the sedutil-cli.exe executable.

**Comment by r0m30** [comment]
Since it works in Linux and fails in Windows my guess is that it is an issue with the windows drivers.  We don't test with esata attachments and don't have the equipment to recreate the issue.

**Comment by gill984** [comment]
You are probably right, I will have to investigate. I did find that if I connect to the laptop using a eSATA to USB 3.0 adapter sedutil works as expected. It is probably a driver issue specific to eSATA since USB works.
