### ISSUE TITLE
issues with encryption - root vs boot drive?

### ISSUE THREAD

**Issue by Zyg0te** [Drive-Trust-Alliance/sedutil#54]
So I am currently dual booting Windows and Arch Linux on my desktop system. 

/dev/sda is the drive where Linux is installed. Single partition

/dev/sdb is the drive where Windows is installed. the EFI partition is located on /dev/sdb2

I want to encrypt /dev/sda but Im having some issues. I follow the instructions on the wiki here but when I power on the system I am never asked for a password and Archlinux fails to boot and throws me to a rescue CLI prompt, indicating that it's unable to find the UUID for the root partition. 

So a couple of questions:

I've run:
```
sedutil-cli --initialsetup <password> /dev/sda
sedutil-cli --loadPBAimage <password> <pba_file> /dev/sda
sedutil-cli --setMBREnable on <password> /dev/sda

sedutil-cli --enableLockingRange 0 <password> /dev/sda
```

However, I dont really understand how the UEFI bootloader (on /dev/sdb2) can know about the encryption state of /dev/sda, or when the decryption prompt is supposed to be triggered. Do I need to do anything with /dev/sdb as well here? Or do I have to add some logic to the bootloader somehow? 

Thanks for any help!

**Comment by r0m30** [comment]
You will have to boot from /dev/sda first to unlock the drive and then when the system reboots you will need to select /sed/sdb as the boot drive after the drive (/dev/sda) is unlocked.
