### ISSUE TITLE
BiosPBA not working

### ISSUE THREAD

**Issue by erasmuswill** [Drive-Trust-Alliance/sedutil#6]
Repost of https://github.com/r0m30/msed/issues/48
The PBA image won't detect my drive.
I'm using a brand nes Samsung 850 Evo 250GB on a Dell Latitude E6500.

**Comment by r0m30** [comment]
The biospba is a lean module that accesses the HBA directly, it won't work on all systems.  If it doesn't work then you will need to use either the LInuxPBA or the UEFI64_PBA.

**Comment by erasmuswill** [comment]
Thanks :+1: , I will try LinuxPBA
