### ISSUE TITLE
how to use in livecd?

### ISSUE THREAD

**Issue by brianjmurrell** [Drive-Trust-Alliance/sedutil#61]
Let's say I boot from the Fedora LiveCD image on a USB stick and I install the Fedora packaged msed package which includes both msed and linuxpba.

How do I go about unlocking the HDD that is in the machine?

I did try `linuxpba` but that had the unfortunate side effect of rebooting the live image.  Is there a less disruptive way?

**Comment by dtasupport** [comment]
You would use sedutil-cli.  The commands to unlock the drive are:

sedutil-cli --setlockingrange 0 rw <password> <drive>
sedutil-cli --setmbrdone on <password> <drive>

This will make the global range read/write and hide the shadow MBR.

You'll also have to make sure that allow_tpm=1 when you boot.

On Wed, Jun 8, 2016 at 9:11 AM, Brian J. Murrell <notifications@github.com>
wrote:

> Let's say I boot from the Fedora LiveCD image on a USB stick and I install
> the Fedora packaged msed package which includes both msed and linuxpba.
>
> How do I go about unlocking the HDD that is in the machine?
>
> I did try linuxpba but that had the unfortunate side effect of rebooting
> the live image. Is there a less disruptive way?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Drive-Trust-Alliance/sedutil/issues/61>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/APuplFHuYEN513Z2aHU-eoVxg5RSPROOks5qJunOgaJpZM4IxIoD>
> .
>



-- 
==========
Mike
