### ISSUE TITLE
HELP cannot get MX200 to work

### ISSUE THREAD

**Issue by SvenHz** [Drive-Trust-Alliance/sedutil#63]
I am upgrading a Samsung NP900-X3C laptop (2012) with a new Crucial MX200 mSATA SSD and I wish to run OPAL.

Running the Rescue USB on an empty SSD, I am unable to get passed initialSetup.

Below are outputs from --scan, --query and --initialSetup respectively.

hdparm -I /dev/sda shows no security related information.
Samsung BIOS has an option for ATA password but it is disabled, says unsupported.
I have tried AHCI on/off and UEFI support on/off, no difference.

Any thoughts?

![2016-06-11 20 27 14](https://cloud.githubusercontent.com/assets/19877538/15986890/36a20720-3015-11e6-921e-14dea31a28ab.jpg)
![2016-06-11 20 27 28](https://cloud.githubusercontent.com/assets/19877538/15986888/369f396e-3015-11e6-9fa9-d44113240165.jpg)
![2016-06-11 20 29 10](https://cloud.githubusercontent.com/assets/19877538/15986889/36a0171c-3015-11e6-8ee5-bd9b9de5bc7a.jpg)

**Comment by r0m30** [comment]
The password has already been set on the drive, when you run initialsetup the drive is supposed to be in the default state.  The Query shows LockingEnabled =Y so ownership of the drive has been established and the MSID is no longer the SID password.
