### ISSUE TITLE
PSID reset does not work on MX200

### ISSUE THREAD

**Issue by SvenHz** [Drive-Trust-Alliance/sedutil#64]
I cannot get PSID reset to work on latest Windows sedutil binary on an MX200 (latest firmware) on Samsung NP900-X3C laptop. Here is the vvvvv output as per wiki suggestion. Any ideas?

`
- 08:02:48.000 DBG : Log level set to DBG4
- 08:02:48.000 DBG : sedutil version : 1.12
- 08:02:48.000 DBG1: Creating  DtaResponse()
- 08:02:48.000 DBG1: Creating  DtaResponse()
- 08:02:48.000 DBG1: Creating DtaDevOS::DtaDevOS() \\.\PhysicalDrive0
- 08:02:48.000 DBG1: Creating DtaDiskATA::DtaDiskATA() \\.\PhysicalDrive0
- 08:02:48.000 DBG1: Entering DtaDevOS::identify()
- 08:02:48.000 DBG1: Exiting DtaDevOS::identify()
- 08:02:48.000 DBG1: Entering DtaDiskATA::identify()
- 08:02:48.000 DBG1: Entering DtaDiskATA::sendCmd
- 08:02:48.000 DBG1: Entering DtaDev::discovery0()
- 08:02:48.000 DBG1: Entering DtaDevOS::sendCmd
- 08:02:48.000 DBG1: Exiting DtaDevOS::sendCmd
- 08:02:48.000 DBG1: Entering DtaDiskATA::sendCmd
- 08:02:48.000 DBG3: Dumping D0Response
- 08:02:48.000 DBG1: Entering hexDump
0000 000000a0 00000001 00000000 00000000  ................ 
0010 00000000 00000000 00000000 00000000  ................ 
0020 00000000 00000000 00000000 00000000  ................ 
0030 0001100c 11000000 00000000 00000000  ................ 
0040 0002100c 0b000000 00000000 00000000  ................ 
0050 0003101c 01000000 00000000 00000200  ................ 
0060 00000000 00000008 00000000 00000000  ................ 
0070 0201100c 00000010 02000000 00000000  ................ 
0080 0202100c 00000010 05a00000 00000001  ................ 
0090 02031010 10000001 00000400 10000000  ................ 
- 08:02:48.000 DBG1: Entering DtaDev::isPresent() 1
- 08:02:48.000 DBG1: Entering DtaDev::isAnySSC 1
- 08:02:48.000 DBG1: Entering DtaDev::isOpal2 1
- 08:02:48.000 DBG1: Creating  DtaResponse()
- 08:02:48.000 DBG1: Creating  DtaResponse()
- 08:02:48.000 DBG1: Creating DtaDevOS::DtaDevOS() \\.\PhysicalDrive0
- 08:02:48.000 DBG1: Creating DtaDiskATA::DtaDiskATA() \\.\PhysicalDrive0
- 08:02:48.000 DBG1: Entering DtaDevOS::identify()
- 08:02:48.000 DBG1: Exiting DtaDevOS::identify()
- 08:02:48.000 DBG1: Entering DtaDiskATA::identify()
- 08:02:48.000 DBG1: Entering DtaDiskATA::sendCmd
- 08:02:48.000 DBG1: Entering DtaDev::discovery0()
- 08:02:48.000 DBG1: Entering DtaDevOS::sendCmd
- 08:02:48.000 DBG1: Exiting DtaDevOS::sendCmd
- 08:02:48.000 DBG1: Entering DtaDiskATA::sendCmd
- 08:02:48.000 DBG3: Dumping D0Response
- 08:02:48.000 DBG1: Entering hexDump
0000 000000a0 00000001 00000000 00000000  ................ 
0010 00000000 00000000 00000000 00000000  ................ 
0020 00000000 00000000 00000000 00000000  ................ 
0030 0001100c 11000000 00000000 00000000  ................ 
0040 0002100c 0b000000 00000000 00000000  ................ 
0050 0003101c 01000000 00000000 00000200  ................ 
0060 00000000 00000008 00000000 00000000  ................ 
0070 0201100c 00000010 02000000 00000000  ................ 
0080 0202100c 00000010 05a00000 00000001  ................ 
0090 02031010 10000001 00000400 10000000  ................ 
- 08:02:48.000 DBG1: Entering DtaDevOpal::properties()
- 08:02:48.000 DBG1: Creating DtaSsession()
- 08:02:48.000 DBG1: Creating DtaCommand(ID, InvokingUid, method)
- 08:02:48.000 DBG1: Entering DtaCommand::reset(OPAL_UID, OPAL_METHOD)
- 08:02:48.000 DBG1: Entering DtaCommand::reset()
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_UID)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(const char * )
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(uint64_t)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(const char * )
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(uint64_t)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(const char * )
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(uint64_t)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(const char * )
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(uint64_t)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(const char * )
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(uint64_t)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(const char * )
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(uint64_t)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.000 DBG1: Entering DtaCommand::complete(uint8_t EOD)
- 08:02:48.000 DBG1: Entering DtaSession::sendCommand()
- 08:02:48.000 DBG1: Entering DtaCommand::setHSN()
- 08:02:48.000 DBG1: Entering DtaCommand::setTSN()
- 08:02:48.000 DBG1: Entering DtaCommand::setcomID()
- 08:02:48.000 DBG3: 
Dumping command buffer
- 08:02:48.000 DBG1: Entering hexDump
0000 00000000 10000000 00000000 00000000  ................ 
0010 000000b0 00000000 00000000 00000000  ................ 
0020 00000000 00000000 00000098 00000000  ................ 
0030 00000000 0000008c f8a80000 00000000  ................ 
0040 00ffa800 00000000 00ff01f0 f200f0f2  ................ 
0050 d0104d61 78436f6d 5061636b 65745369  ..MaxComPacketSi 
0060 7a658208 00f3f2ad 4d617850 61636b65  ze......MaxPacke 
0070 7453697a 658207ec f3f2af4d 6178496e  tSize......MaxIn 
0080 64546f6b 656e5369 7a658207 c8f3f2aa  dTokenSize...... 
0090 4d617850 61636b65 747301f3 f2ad4d61  MaxPackets....Ma 
00a0 78537562 7061636b 65747301 f3f2aa4d  xSubpackets....M 
00b0 61784d65 74686f64 7301f3f1 f3f1f9f0  axMethods....... 
00c0 000000f1                             ....
- 08:02:48.000 DBG1: Entering DtaDevOS::sendCmd
- 08:02:48.000 DBG1: Exiting DtaDevOS::sendCmd
- 08:02:48.000 DBG1: Entering DtaDiskATA::sendCmd
- 08:02:48.032 DBG1: Entering DtaDevOS::sendCmd
- 08:02:48.032 DBG1: Exiting DtaDevOS::sendCmd
- 08:02:48.032 DBG1: Entering DtaDiskATA::sendCmd
- 08:02:48.032 DBG3: 
Dumping reply buffer
- 08:02:48.032 DBG1: Entering hexDump
0000 00000000 10000000 00000000 00000000  ................ 
0010 000001b8 00000000 00000000 00000000  ................ 
0020 00000000 00000000 000001a0 00000000  ................ 
0030 00000000 00000193 f8a80000 00000000  ................ 
0040 00ffa800 00000000 00ff01f0 f0f2d010  ................ 
0050 4d617843 6f6d5061 636b6574 53697a65  MaxComPacketSize 
0060 83020000 f3f2d018 4d617852 6573706f  ........MaxRespo 
0070 6e736543 6f6d5061 636b6574 53697a65  nseComPacketSize 
0080 83020000 f3f2ad4d 61785061 636b6574  .......MaxPacket 
0090 53697a65 8301fb00 f3f2af4d 6178496e  Size.......MaxIn 
00a0 64546f6b 656e5369 7a658301 f000f3f2  dTokenSize...... 
00b0 aa4d6178 5061636b 65747301 f3f2ad4d  .MaxPackets....M 
00c0 61785375 62706163 6b657473 01f3f2aa  axSubpackets.... 
00d0 4d61784d 6574686f 647301f3 f2ab4d61  MaxMethods....Ma 
00e0 78536573 73696f6e 7301f3f2 d0124d61  xSessions.....Ma 
00f0 78417574 68656e74 69636174 696f6e73  xAuthentications 
0100 15f3f2d0 134d6178 5472616e 73616374  .....MaxTransact 
0110 696f6e4c 696d6974 01f3f2d0 11446566  ionLimit.....Def 
0120 53657373 696f6e54 696d656f 75748303  SessionTimeout.. 
0130 a980f3f1 f200f0f2 d0104d61 78436f6d  ..........MaxCom 
0140 5061636b 65745369 7a658208 00f3f2d0  PacketSize...... 
0150 184d6178 52657370 6f6e7365 436f6d50  .MaxResponseComP 
0160 61636b65 7453697a 65820800 f3f2ad4d  acketSize......M 
0170 61785061 636b6574 53697a65 8207ecf3  axPacketSize.... 
0180 f2af4d61 78496e64 546f6b65 6e53697a  ..MaxIndTokenSiz 
0190 658207c8 f3f2aa4d 61785061 636b6574  e......MaxPacket 
01a0 7301f3f2 ad4d6178 53756270 61636b65  s....MaxSubpacke 
01b0 747301f3 f2aa4d61 784d6574 686f6473  ts....MaxMethods 
01c0 01f3f1f3 f1f9f000 0000f100           ............
- 08:02:48.032 DBG1: Entering  DtaResponse::init
- 08:02:48.032 DBG1: Entering  DtaResponse::tokenIs
- 08:02:48.032 DBG1: Entering  DtaResponse::getTokenCount()
- 08:02:48.032 DBG1: Entering  DtaResponse::tokenIs
- 08:02:48.032 DBG1: Entering  DtaResponse::getTokenCount()
- 08:02:48.032 DBG1: Entering  DtaResponse::tokenIs
- 08:02:48.032 DBG1: Entering  DtaResponse::getTokenCount()
- 08:02:48.032 DBG1: Entering  DtaResponse::getUint8
- 08:02:48.032 DBG1: Entering  DtaResponse::getUint64
- 08:02:48.032 DBG1: Entering  DtaResponse::getTokenCount()
- 08:02:48.032 DBG1: Entering  DtaResponse::getUint8
- 08:02:48.032 DBG1: Entering  DtaResponse::getUint64
- 08:02:48.032 DBG1: Destroying DtaCommand
- 08:02:48.032 DBG1: Leaving DtaDevOpal::properties()
- 08:02:48.032 DBG1: Destroying DtaDevOS
- 08:02:48.032 DBG1: Destroying DtaDiskATA
- 08:02:48.032 DBG1: Destroying DtaResponse
- 08:02:48.032 DBG1: Destroying DtaResponse
- 08:02:48.032 DBG : Performing a PSID Revert on \\.\PhysicalDrive0 with password 56DD54C6-02B0-66CD-E100-000089C981F2
- 08:02:48.032 DBG1: Entering DtaDevOpal::revertTPer()
- 08:02:48.032 DBG1: Creating DtaCommand()
- 08:02:48.032 DBG1: Creating DtaSsession()
- 08:02:48.032 DBG1: Entering DtaSession::setProtocol
- 08:02:48.032 DBG1: Entering DtaSession::startSession 
- 08:02:48.032 DBG1: Entering DtaSession::startSession 
- 08:02:48.032 DBG1: Creating DtaCommand()
- 08:02:48.032 DBG1: Creating  DtaResponse()
- 08:02:48.032 DBG1: Entering DtaCommand::reset(OPAL_UID, OPAL_METHOD)
- 08:02:48.032 DBG1: Entering DtaCommand::reset()
- 08:02:48.032 DBG1: Entering DtaCommand::addToken(OPAL_UID)
- 08:02:48.032 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.032 DBG1: Entering DtaCommand::addToken(uint64_t)
- 08:02:48.032 DBG1: Entering DtaCommand::addToken(OPAL_UID)
- 08:02:48.032 DBG1: Entering DtaCommand::addToken(OPAL_TINY_ATOM)
- 08:02:48.032 DBG1: Entering DtaDev::isEprise 0
- 08:02:48.032 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.032 DBG1: Entering DtaCommand::addToken(OPAL_TINY_ATOM)
- 08:02:48.032 DBG1: Entering DtaCommand::addToken(const char * )
- 08:02:48.032 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.032 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.032 DBG1: Entering DtaCommand::addToken(OPAL_TINY_ATOM)
- 08:02:48.032 DBG1: Entering addToken(vector<uint8_t>)
- 08:02:48.032 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.032 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.032 DBG1: Entering DtaCommand::complete(uint8_t EOD)
- 08:02:48.032 DBG1: Entering DtaSession::sendCommand()
- 08:02:48.032 DBG1: Entering DtaCommand::setHSN()
- 08:02:48.032 DBG1: Entering DtaCommand::setTSN()
- 08:02:48.032 DBG1: Entering DtaCommand::setcomID()
- 08:02:48.032 DBG3: 
Dumping command buffer
- 08:02:48.032 DBG1: Entering hexDump
0000 00000000 10000000 00000000 00000000  ................ 
0010 00000080 00000000 00000000 00000000  ................ 
0020 00000000 00000000 00000068 00000000  ...........h.... 
0030 00000000 0000005c f8a80000 00000000  .......\........ 
0040 00ffa800 00000000 00ff02f0 8169a800  .............i.. 
0050 00020500 00000101 f200d024 35364444  ...........$56DD 
0060 35344336 2d303242 302d3636 43442d45  54C6-02B0-66CD-E 
0070 3130302d 30303030 38394339 38314632  100-000089C981F2 
0080 f3f203a8 00000009 0001ff01 f3f1f9f0  ................ 
0090 000000f1                             ....
- 08:02:48.032 DBG1: Entering DtaDevOS::sendCmd
- 08:02:48.032 DBG1: Exiting DtaDevOS::sendCmd
- 08:02:48.032 DBG1: Entering DtaDiskATA::sendCmd
- 08:02:48.063 DBG1: Entering DtaDevOS::sendCmd
- 08:02:48.063 DBG1: Exiting DtaDevOS::sendCmd
- 08:02:48.063 DBG1: Entering DtaDiskATA::sendCmd
- 08:02:48.063 DBG3: 
Dumping reply buffer
- 08:02:48.063 DBG1: Entering hexDump
0000 00000000 10000000 00000000 00000000  ................ 
0010 00000000                             ....
- 08:02:48.063 DBG1: Entering  DtaResponse::init
- 08:02:48.063 ERR : One or more header fields have 0 length
- 08:02:48.063 ERR : Session start failed
- 08:02:48.063 DBG1: Destroying DtaCommand
- 08:02:48.063 DBG1: Destroying DtaResponse
- 08:02:48.063 DBG1: Destroying DtaCommand
- 08:02:48.063 DBG1: Destroying DtaSession
- 08:02:48.063 DBG1: Creating  DtaResponse()
- 08:02:48.063 DBG1: Creating DtaCommand()
- 08:02:48.063 DBG1: Entering DtaCommand::reset()
- 08:02:48.063 DBG1: Entering DtaCommand::addToken(OPAL_TOKEN)
- 08:02:48.063 DBG1: Entering DtaCommand::complete(uint8_t EOD)
- 08:02:48.063 DBG1: Entering DtaSession::sendCommand()
- 08:02:48.063 DBG1: Entering DtaCommand::setHSN()
- 08:02:48.063 DBG1: Entering DtaCommand::setTSN()
- 08:02:48.063 DBG1: Entering DtaCommand::setcomID()
- 08:02:48.063 DBG3: 
Dumping command buffer
- 08:02:48.063 DBG1: Entering hexDump
0000 00000000 10000000 00000000 00000000  ................ 
0010 00000028 00000000 00000000 00000000  ...(............ 
0020 00000000 00000000 00000010 00000000  ................ 
0030 00000000 00000001 fa000000           ............
- 08:02:48.063 DBG1: Entering DtaDevOS::sendCmd
- 08:02:48.063 DBG1: Exiting DtaDevOS::sendCmd
- 08:02:48.063 DBG1: Entering DtaDiskATA::sendCmd
- 08:02:48.094 DBG1: Entering DtaDevOS::sendCmd
- 08:02:48.094 DBG1: Exiting DtaDevOS::sendCmd
- 08:02:48.094 DBG1: Entering DtaDiskATA::sendCmd
- 08:02:48.094 DBG3: 
Dumping reply buffer
- 08:02:48.094 DBG1: Entering hexDump
0000 00000000 10000000 00000000 00000000  ................ 
0010 00000000                             ....
- 08:02:48.094 DBG1: Entering  DtaResponse::init
- 08:02:48.094 ERR : One or more header fields have 0 length
- 08:02:48.094 ERR : EndSession Failed
- 08:02:48.094 DBG1: Destroying DtaCommand
- 08:02:48.094 DBG1: Destroying DtaResponse

`

**Comment by r0m30** [comment]
Take the dashes out of the PSID.
Use 56DD54C602B066CDE100000089C981F2 not 56DD54C6-02B0-66CD-E100-000089C981F2 the PSID is a 32 byte Hex number.

**Comment by SvenHz** [comment]
Thank you. It works...! Issue closed. Also solved #63 .
