### ISSUE TITLE
Unlocking disk wipes all non-default EFI bootloader entries

### ISSUE THREAD

**Issue by archpoint** [Drive-Trust-Alliance/sedutil#66]
Ok, this is a weird one. 

On my system I have refind installed as my EFI bootloader which boots into Arch Linux. After enabling sedutil encryption Im running into this odd issue where all the EFI bootloader entries I create are destroyed when I power off the system. I'm not sure if the entries are destroyed upon disk decryption or on power-off in general but I dont have this issue if I disable encryption. 

I can create multiple EFI entries using efibootmgr and they will all be gone if I shut down the system, boot up and unlock the drive. Only the system-default buit-in EFI boot loader remains.

Anyone experienced this before? I dont shut down often but it's really cumbersome having to boot into a Live CD environment to run refind-install every time nonetheless. :)

Thanks!

**Comment by r0m30** [comment]
Sedutil doesn't create or modify the EFI.  This is probably related to the EFI BIOS seeing what it thinks is a different disk drive installed (locked vs unlocked drive) and re-enumerating the system for bootable devices.

**Comment by Zyg0te** [comment]
That makes sense. However I've never seen this behavior before on my other
systems. Any idea how to get around that issue?

On Tuesday, 14 June 2016, r0m30 <notifications@github.com> wrote:

> Sedutil doesn't create or modify the EFI. This is probably related to the
> EFI BIOS seeing what it thinks is a different disk drive installed (locked
> vs unlocked drive) and re-enumerating the system for bootable devices.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Drive-Trust-Alliance/sedutil/issues/66#issuecomment-226009003>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAWZB-72MIheJrItDL9l7tEqXkEIQyxoks5qLxGHgaJpZM4I1Cx9>
> .
>


-- 
Edvard;

**Comment by Lauvergnat** [comment]
Hello Archpoint, 
Have you found the source of your issue ?
I am also using rEFInd (but on Gentoo) and I would like to avoid such an  issue...

**Comment by r0m30** [comment]
@archpoint 
Sometimes there are options in the bios that skip the enumeration but you'd need to check with your bios/mobo vendor.
