### ISSUE TITLE
About Windows/TestSuite.sh problem

### ISSUE THREAD

**Issue by AnyProblem** [Drive-Trust-Alliance/sedutil#68]
I bought a new SSD(SanDisk x400), this ssd has opal 2.0 mechanism claim on SanDisk 
Official website, but I ran TestSuite.sh it give me this report : 
Scanning for Opal compliant disks
\\.\PhysicalDrive0 No  SanDisk SD8SB8U256G1122                  X4120000

why is this result?
Thank you

**Comment by r0m30** [comment]
What type of computer, OS an attachment are you using?

**Comment by AnyProblem** [comment]
I ran this program on Windows 7 , and I have already found the problem answer that is Sandisk datasheet problem, not all Sandisk x400 have suppose TCG opal 2.0 , it divided into two parts of SKU SD8Sxxxx and SD8Txxxx, but only SD8Txxxx SKU has supposed TCG opal 2.0. thank you for your reply
