### ISSUE TITLE
Proper sequence to make locked drive available following reboot

### ISSUE THREAD

**Issue by lellis1936** [Drive-Trust-Alliance/sedutil#7]
On Windows 10, if I power up a locked non-OS drive before boot, PBA unlocks it properly.

If I power up AFTER boot, some MSED commands are required to make the drive available.  These are the ones that seem to work:

setMBRDone on ...
setLockingRange 0 RW  ...

I also have to issue a "diskpart" rescan command to properly mount the drive, else it shows up as uninitialized.

Is this the normal recommended sequence?

Also, is there anything in the MSED query results that tell me if ALL these things have been done; IOW, something that says that drive is ready to use and NOT still using a shadow partition?

Thanks.

**Comment by r0m30** [comment]
That command sequence should work fine to make the drive accessible if the drive is powered up after boot.  

If you are not using any locking ranges except the global range (LR0) then the locking function of the query command will tell you if the drive has been unlocked and unshadowed (Locked = N and MBRDone = Y) but nothing in the query will tell you if the diskpart scan has been done.

If you are using multiple licking ranges then it is possible the query command will show locked = Y if any of the other ranges are locked and you would need to use listLockingRanges to see which ranges are locked.
