### ISSUE TITLE
Unlocking second drive in biospba

### ISSUE THREAD

**Issue by nico853** [Drive-Trust-Alliance/sedutil#70]
Using sedutil 1.12 (that contains biospba 1.10):

Two drives, let's call them Phys0 and Phys1:
Phys0: Crucial MX550, Win 10, MBR, OPAL locked, biospba 1.10 installed
Phys1: Crucial MX550, Win 7, MBR, OPAL locked
Both drives locked with the same password.
BIOS set up to boot legacy only.
At power on, BIOS booting biospba from Phys0.
After entering password, I see both drives being unlocked, then it goes to chain-load, then Win 10 boots up.
When I open Win Explorer and look to my drives I see Phys1 showing the data as drive D:\.
All OK.

Use-case change:
Phys1: restore it to non-OPAL, then re-init using the same password as Phys0, write the biospba 1.10, lock drive etc (as per manual).
Shut down PC.
Restart, boot Phys0 biospba, enter password, chain-load, Win 10 is up.
Now Phys1 shows the shadow CD as drive D:\.
In order to check if Phys 1 was realy unlocked, I do a warm boot (restart in Windows), Win 10 boots normaly (drives aren't locked now), but I have access to Phys1 data (no more shadow CD).
I repeated the steps at least three times (with and without biospba on Phys1), and I had the same result each time.

I'm interested to be able to see "the other drive" data (not the boot one) unlocked even when it has the biospba installed.
This way I could boot any OS just by changing the BIOS setting or from the boot menu, and have access to the other drive data without restarting the computer.

**Comment by nico853** [comment]
Correction: both drives are Crucial M550 (not MX550)

**Comment by r0m30** [comment]
Can you give me a little more info on the PC and drive attachments?  I upgraded recently to a new machine with UEFI but when I was running the bios PBA I ran it with three drives (WIN/Data/Linux) all with the same password and they all were unlocked when I booted.

**Comment by nico853** [comment]
While preparing my answer, with screen captures and even a video, I ended up having no problem at all. For now, I’ll close the issue. There might be however a small difference in the steps I took to send biospba to my drive, and I also have now a third non-SSD non-SED drive in my laptop (Lenovo T520, BIOS 1.45 latest as far as I know, Phys0 is SATA SSD, Phys1 is mSATA SSD, Phys2 is in the ultrabay).
If having time for more details, read on:
Each time I tested before, I followed these steps, starting with both drives unlocked following a successful boot of Phys0:
Revert Phys1 to non-OPAL status
Take ownership of Phys1 (initialsetup)
Load PBA and enable shadow CD (loadPBAimage and setMBREnable on)
Enable locking (enableLockingRange 0)
Shut down computer (Power off) then restart
I have to mention here that I first noticed the unexpected behavior while Win 10 was installed on Phys0 GPT and booting UEFI only. I converted the drive to MBR and booting legacy only just to check if it goes away.
This time I hurried to load the PBA without reverting the drive to non-OPAL status. From command prompt I just did (copied from cmd window – except the password):
C:\Programs\SEDUtil>sedutil-cli --scan
Scanning for Opal compliant disks
\\.\PhysicalDrive0  2  Crucial_CT128M550SSD1                    MU02
\\.\PhysicalDrive1  2  Crucial_CT256M550SSD3                    MU02
\\.\PhysicalDrive2 No  ST9500423AS                              0004HPM1
No more disks present ending scan
C:\Programs\SEDUtil>sedutil-cli --loadPBAimage password biospba-1.10.img \\.\PhysicalDrive1
- 17:30:06.000 INFO: Writing PBA to \\.\PhysicalDrive1
 | [*********************] 1049600 bytes written
- 17:30:41.125 INFO: PBA image  biospba-1.10.img written to \\.\PhysicalDrive1
C:\Programs\SEDUtil>sedutil-cli --setMBREnable on password \\.\PhysicalDrive1
- 17:31:43.000 INFO: MBRDone set on
- 17:31:44.218 INFO: MBREnable set on
C:\Programs\SEDUtil>

Then I shut down (Power off) and started. And I found Phys1 showing data, not MSEDPBA (CD). 
Now I wanted to check booting from Phys1 (Win 7), I powered off again, then started, changed BIOS to boot Phys1, restarted, entered the password, and successfully booted Phys1, and Phys0 was showing data not CD (remember I still have biospba on Phys0).
Then I shut down (Power off) and restarted and switched BIOS boot back to Phys0 (Win 10) and it worked as expected.
As I said, I consider the issue closed, but I’ll try to reproduce the original steps and without the third drive whenever possible, and I’ll post again if I can reproduce the unexpected behavior. Maybe there is something in the drive firmware that asks for enabling locking, then unlock and write the PBA (speculation).
Thank you for answering!


Date: Wed, 22 Jun 2016 13:32:39 -0700
