### ISSUE TITLE
Unlock drive without PBA from within OS

### ISSUE THREAD

**Issue by glenntanner3** [Drive-Trust-Alliance/sedutil#71]
So I need to 'reset' a bunch of drives but cannot find a way to unlock them using the sedutil-cli so i can manage them. Linux.

**Comment by r0m30** [comment]
Do you know the SID password for the drives?  If not then you'll need to do a PSID revert.

**Comment by glenntanner3** [comment]
Yes. It's the WSID

**Comment by r0m30** [comment]
Are you trying to keep the data?

Once you take ownership of the drive the MSID is no  longer the password, have these drives ever been enabled (initialsetup)?  What is the output of the query command?

If not then you will need to do that before you can "reset" them.  Something like the testsuite without all the bit flipping, initialsetup then reverttper.
If they have you need either the password they were setup with or the PSID to reset them.

**Comment by glenntanner3** [comment]
We had to create our own SED utility before this was available so the password is set as MSID, so no initialsetup or anything like that for management. No i'm trying to wipe the drives and cannot access the protected band, which is most of the drive. I would use PSID except that is manual and it can be scripted due to MSID password. I will get you the query output tomorrow, but basically it shows: locked, lockable, lock enabled, no MBR shadow.

**Comment by r0m30** [comment]
OK,
To crypto erase and turn off OPAL on the drive try changing 
sedutil-cli -n --revertLockingSP ${MSID} ${d}
to 
sedutil-cli -n --reverttper ${MSID} ${d}

**Comment by glenntanner3** [comment]
Ok, this might have worked. That command returned 'INVALID FUNCTION', but now when I try to get the default password i get (and forgive me but this system is booted from PXE and does not have a network stack so I cannot copy): 
- 14:19:58:600 ERR : method status code SP_BUSY
- 14:19:58:600 ERR : Session start failed
- 14:19:58:600 ERR : Unable to start Unauthenticated session /dev/sdb
- 14:19:58:626 ERR : One or more header fields have 0 length
- 14:19:58:626 ERR : EndSession Failed
- 14:19:58:627 ERR : unable to retrieve MSID

DD gives me a problem after power cycling the system:
blk_update_request: critical target error, dev sdg, sector 1050624
Buffer I/O error on dev sdg, logical block 131328 (-131337), lost async page write

Lock info from /dev/sdb query since running command
Locking function (0x0002)
Locked = N, LockingEnabled = Y, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y

**Comment by glenntanner3** [comment]
As for the SP_BUSY, I just learned from the person who wrote our tool here that SED commands do not finish instantly all the time. Said he had to write in a loop to watch for a done bit in the output buffer. Other problem he faced is SATA reset can abort the SED command requiring it to be re-issued. Hope this helps with the SP_BUSY bug you refer to in the FAQ. Thanks again for the help.

**Comment by r0m30** [comment]
Are these TCG Enterprise drives?

**Comment by glenntanner3** [comment]
Yes, to my knowledge. [Seagate ST2000NM0063](http://www.seagate.com/www-content/product-content/constellation-fam/constellation-es/constellation-es-3/en-us/docs/100671510b.pdf)

**Comment by r0m30** [comment]
You will need to power cycle the drive to clear the SP_BUSY.

Enterprise was the first spec and it came before revert/psidrevert were formalized, so it's not consistent.  If both revertTPer and revertLockingSP fail then sedutil isn't going to be able to reset those drives.

**Comment by glenntanner3** [comment]
That's unfortunate to hear, but thank you for the info.

**Comment by vogelfreiheit** [comment]
What is the preferred way to unlock drives on runtime, ex. without the PBA? (and no data loss)
