### ISSUE TITLE
What caused the mistake of method status code TPER_MALFUNCTION? 

### ISSUE THREAD

**Issue by liuligang** [Drive-Trust-Alliance/sedutil#74]
I debugging and found Payload  without errors,but appear method status code TPER_MALFUNCTION.
I want to know What caused the mistake of method status code TPER_MALFUNCTION?
 Thanks.

**Comment by r0m30** [comment]
A TPER_MALFUNCTION is a firmware error.  If you have the current firmware on the drive then you need to contact the manufacturer

**Comment by liuligang** [comment]
I detailed said what I do caused by this mistake.
I add User1,User2,User3,User4 to access LockingRange0. I refer to the following content in the document.
[http://trustedcomputinggroup.org/wp-content/uploads/TCG_Storage_Opal_SSC_Application_Note_1-00_1-00-Final.pdf](url)

when I add User3,User2,User1-three users to access LockingRange0,I can use any one user(user3,user2,user1) to unlockinng range0. I can receive succeed.
**But when I add User4,User3,User2,User1-four users to access LockingRange0,I can only use any one user(user4,user3,user2) in three users to unlockinng range0 and user1 can not unlocking range0.
when I DEBUG the code of unlock the range by setting the Locked columns in the Locking table to false, 
I can receive the mistake of method status code TPER_MALFUNCTION.**

So,I do not think it is a firmware error. I doubt  my packet has a problem.
ACE_Locking_Range0_Set _RdLocked_UID.Set[Values = [BooleanExpr = [User4_UID | User3_UID | User2_UID | User1_UID] ] ]---**I doubt  it is ture or false?**

The following is my add users data packets.

     LR.push_back(OPAL_SHORT_ATOM::BYTESTRING8);
     for (int i = 0; i < 8; i++)
     {
	LR.push_back(OPALUID[OPAL_UID::OPAL_LOCKINGRANGE0_ACE_RDLOCKED][i]);
     }
      vector<uint8_t> USER1;
      USER1.push_back(OPAL_SHORT_ATOM::BYTESTRING8);
      for (int i = 0; i < 8; i++)
       {
		USER1.push_back(OPALUID[OPAL_UID::OPAL_USER1_UID][i]);
	}

	vector<uint8_t> USER2;
	USER2.push_back(OPAL_SHORT_ATOM::BYTESTRING8);
	for (int i = 0; i < 8; i++) {
		USER2.push_back(OPALUID[OPAL_UID::OPAL_USER2_UID][i]);
	}
       
        vector<uint8_t> USER3;
	USER3.push_back(OPAL_SHORT_ATOM::BYTESTRING8);
	for (int i = 0; i < 8; i++) {
		USER3.push_back(OPALUID[OPAL_UID::OPAL_USER3_UID][i]);
	}

      vector<uint8_t> USER4;
	USER4.push_back(OPAL_SHORT_ATOM::BYTESTRING8);
	for (int i = 0; i < 8; i++) {
		USER4.push_back(OPALUID[OPAL_UID::OPAL_USER4_UID][i]);
	}

	vector<uint8_t> HALF_UID_AUTHORITY;
	HALF_UID_AUTHORITY.push_back(OPAL_SHORT_ATOM::BYTESTRING4);
	for (int i = 0; i < 4; i++)
        {
		HALF_UID_AUTHORITY.push_back(OPALUID   [OPAL_UID::OPAL_HALF_UID_AUTHORITY_OBJ_REF][i]);
	}

	vector<uint8_t> HALF_UID_BOOLEAN;
	HALF_UID_BOOLEAN.push_back(OPAL_SHORT_ATOM::BYTESTRING4);
	for (int i = 0; i < 4; i++) 
        {
		HALF_UID_BOOLEAN.push_back(OPALUID[OPAL_UID::OPAL_HALF_UID_BOOLEAN_ACE][i]);
	}

	session = new DtaSession(this);
	if (NULL == session)
        {
		LOG(E) << "Unable to create session object ";
		return DTAERROR_OBJECT_CREATE_FAILED;
	}
	if ((lastRC = session->start(OPAL_UID::OPAL_LOCKINGSP_UID, password, OPAL_UID::OPAL_ADMIN1_UID)) != 0)
        {
		delete session;
		return lastRC;
	}

	DtaCommand *set_read = new DtaCommand();
	if (NULL == set_read)
       {
		LOG(E) << "Unable to create command object ";
		delete session;
		return DTAERROR_OBJECT_CREATE_FAILED;
	}
	set_read->reset(OPAL_UID::OPAL_AUTHORITY_TABLE, OPAL_METHOD::SET);
	set_read->changeInvokingUid(LR);
	set_read->addToken(OPAL_TOKEN::STARTLIST);
	set_read->addToken(OPAL_TOKEN::STARTNAME);
	set_read->addToken(OPAL_TOKEN::VALUES);
	set_read->addToken(OPAL_TOKEN::STARTLIST);
	set_read->addToken(OPAL_TOKEN::STARTNAME);
	set_read->addToken(OPAL_TOKEN::OPAL_BOOLEAN_EXPR);
	set_read->addToken(OPAL_TOKEN::STARTLIST);
	set_read->addToken(OPAL_TOKEN::STARTNAME);
	set_read->addToken(HALF_UID_AUTHORITY);
	set_read->addToken(USER4);
	set_read->addToken(OPAL_TOKEN::ENDNAME);

	set_read->addToken(OPAL_TOKEN::STARTNAME);
	set_read->addToken(HALF_UID_AUTHORITY);
	set_read->addToken(USER3);
	set_read->addToken(OPAL_TOKEN::ENDNAME);

	set_read->addToken(OPAL_TOKEN::STARTNAME);
	set_read->addToken(HALF_UID_BOOLEAN);
	set_read->addToken(UINT_01);
	set_read->addToken(OPAL_TOKEN::ENDNAME);

        set_read->addToken(OPAL_TOKEN::STARTNAME);
	set_read->addToken(HALF_UID_AUTHORITY);
	set_read->addToken(USER2);
	set_read->addToken(OPAL_TOKEN::ENDNAME);

        set_read->addToken(OPAL_TOKEN::STARTNAME);
	set_read->addToken(HALF_UID_BOOLEAN);
	set_read->addToken(UINT_01);
	set_read->addToken(OPAL_TOKEN::ENDNAME);

        set_read->addToken(OPAL_TOKEN::STARTNAME);
	set_read->addToken(HALF_UID_AUTHORITY);
	set_read->addToken(USER1);
	set_read->addToken(OPAL_TOKEN::ENDNAME);

        set_read->addToken(OPAL_TOKEN::STARTNAME);
	set_read->addToken(HALF_UID_BOOLEAN);
	set_read->addToken(UINT_01);
	set_read->addToken(OPAL_TOKEN::ENDNAME);

	set_read->addToken(OPAL_TOKEN::ENDLIST);
	set_read->addToken(OPAL_TOKEN::ENDNAME);
	set_read->addToken(OPAL_TOKEN::ENDLIST);
	set_read->addToken(OPAL_TOKEN::ENDNAME);
	set_read->addToken(OPAL_TOKEN::ENDLIST);
	set_read->complete();

**Comment by liuligang** [comment]
Hi，@r0m30 
First，Thank you！
I have found the cause of this error. It is truly my packet problem.

The code should be written in this order---User4_UID User3_UID User2_UID User1_UID | | | |.
