### ISSUE TITLE
Failure to load ldlinux.c32

### ISSUE THREAD

**Issue by corporategoth** [Drive-Trust-Alliance/sedutil#77]
I've created a custom Linux PBA image.  And I've written it to the shadow MBR and locked the drive.

When I try to boot, I am getting an error of 'Failed to load ldlinux.c32'

I uncompressed and mounted the image, and sure enough there IS a ldlinux.c32 file in the image, so extlinux did it's job (apparently).  I didn't get any errors, anyway.

![shadowmbr_boot_error](https://cloud.githubusercontent.com/assets/3732622/16691307/1cd49f98-44fa-11e6-8604-d44c97bfa705.png)

Any ideas why, since the image appears valid (it's an ext4 filesystem, 1mb offset from the beginning of the IMG).  Here are the contents of that image:

```
-rw-r--r-- 1 root root 3358464 Jul  8 03:46 bzImage
-rwxr-xr-x 1 root root     129 Jul  8 03:46 extlinux.conf
-r--r--r-- 1 root root  116888 Jul  8 03:46 ldlinux.c32
-r--r--r-- 1 root root   61952 Jul  8 03:46 ldlinux.sys
-rw-r--r-- 1 root root 4697516 Jul  8 03:46 rootfs.cpio.xz

```

I increased the image size from 8mb -> 16mb to accommodate the larger rootfs (from online docs, you can go up to 128mb).

**Comment by r0m30** [comment]
How did you create this?
I don't see anything explicitly wrong.  Did you remember to mark the partition active?  
Is your machine a BIOS or UEFI system?

**Comment by corporategoth** [comment]
It's BIOS only.

I followed the BUILDING instructions with the extra step to add the stuff I need to create the resources for unlocking using a yubikey and add them to the overlay.

So basically:
```
        cd ../LinuxPBA
        make CONF=Release
        cd ../linux/CLI
        make CONF=Release_i686
        cd ../../images
        ./getresources
        ./setupautounlock <device> <password>     (my extra step, adds to overlay)
        ./buildpbaroot
        ./buildbiosLinux Release
```

My config is:
```
#!/bin/bash
#  Setup versions for image components
#  This script should be sourced by the other scripts
TINYCORE=Core-6.4.1.iso
SYSLINUX=syslinux-6.03
TCDISTRO=http://distro.ibiblio.org/tinycorelinux/6.x/x86/
BUILDROOT=git://git.buildroot.net/buildroot
BUILDROOT_TAG=2016.05
YUBICOCROOT=https://github.com/Yubico/yubico-c.git
YUBICOCROOT_TAG=libyubikey-1.13
YUBIPERSROOT=https://github.com/Yubico/yubikey-personalization
YUBIPERSROOT_TAG=v1.17.3
```

The buildroot and kernel configs have been updated.  The former to add the utilities I need for luks (and because I updated the version of buildroot to 2016.05), the latter because I updated the kernel to the latest one supported by buildroot and to support the crypt stuff necessary for luks (and TPM, even though I've taken out the TPM stuff for this release.  I might actually combine the TPM stuff I did in another version when I finally submit a pull request).

buildpbaroot has been modified to build the yubico tools I need, and add them to the overlay.

Critically, however, buildbiosLinux has only been modified to increase the size of the image from 8mb -> 16mb, and the version of syslinux is not changed from the git repo.  So because it's not even getting to the point where it starts the kernel, OR opens my initrd, I don't think any of my modifications can/will effect it.

**Comment by pgeremia** [comment]
I am seeing the exact same issue with the buildbiosLinux using @corporategoth codebase for tpm support.

![biospbabootissue](https://cloud.githubusercontent.com/assets/12115362/16700001/885bce46-4525-11e6-9532-5c99a6821035.JPG)
.

**Comment by corporategoth** [comment]
OK, I found a fix for this.  I had to edit the buildbiosLinux to output to image/extlinux instead of image/boot/extlinux

I also converted the filesystem to ext2 for good measure (it's never going to be read/write mounted so it can't get dirty - no need for the journal!).

**Comment by pgeremia** [comment]
@corporategoth That is great news!!  I will test it out and verify TPM functionality.

**Comment by corporategoth** [comment]
@pgeremia I know it won't work, because the autounlock.sh script doesn't work in a busybox environment apparently because ash does not support arrays.  I'm modifying my version here to work around that.  Almost got the version that uses yubikey working, and I'll re-add TPM support again once that is done.  Then I'll have a version that supports using a TPM nvram slot, file on a USB flash drive or challenge-response with a yubikey to unlock :)

**Comment by pgeremia** [comment]
@corporategoth Sounds good. Thanks for letting me know.

**Comment by corporategoth** [comment]
OK, I have re-forked my repo from this.  The code here now works:
https://github.com/corporategoth/sedutil

It will add support for decrypting using a TPM (using the tpm tools from luks-tpm, not trousers), A file on a USB device, or a challenge-response using a yubikey - in any combination.  And the code works because I'm using it myself (right now the only unlock method I'm using on the computer I was developing on is yubikey, but the other unlock methods should work just fine).

It's all been built on centos 7.

**Comment by pgeremia** [comment]
@corporategoth I will test TPM on Monday.  So as far as the auto unlock setup script goes, what are the requirements to run it?  I looked at some of the calls and it looks like Trousers is required.  It would be great if we could integrate that into the Rescue image but not sure it is possible. Thanks again for all of your work.

**Comment by pgeremia** [comment]
@corporategoth So it looks like git.buildroot.net is down.  I think they had a major failure.  Are you seeing the same thing?

**Comment by pgeremia** [comment]
@corporategoth I finally got TPM auto unlock to work.  But one thing I noted.  The code that locks the nvram slot until after restart may actually lock it forever.  At least that is what I was reading about it and observed in my testing.  Any thoughts?  Ps.  I would send you messages in a different forum, but there is no way in GitHub, is there?

**Comment by corporategoth** [comment]
@pgeremia , it does not lock the TPM slot forever.  It prevents reading that slot's data until the next time you start up.  I'm not 100% sure if it is a simple reboot or a power cycle of the machine (I believe it is the former).  But this stops someone from being able to read that slot and find out the unlock password if they happen to access the computer some time after boot (ie. the screen is unlocked or they login via ssh).

It does NOT however prevent writing to that slot.  Nor does it prevent you destroying and recreating that slot.  So it's not really a barrier to being able to re-do your bootloader.

It's a security mechanism for safety's sake.  You can remove it if you like, but since I use a specific TPM slot for this kind of thing, I don't NEED to access it after boot time.

**Comment by corporategoth** [comment]
I created a pull request with my changes:
https://github.com/Drive-Trust-Alliance/sedutil/pull/86

You can discuss them there instead of in this issue.
But I'm leaving the issue because the main source code should fix the issue as I described in https://github.com/Drive-Trust-Alliance/sedutil/issues/77#issuecomment-231492794
