### ISSUE TITLE
Download the PBA can hurry up？

### ISSUE THREAD

**Issue by liuligang** [Drive-Trust-Alliance/sedutil#78]
I found use --loadPBAimage command  download PBAimage very slowly.
Generally the SSD write speed above 400 M/s and I think download PBAimage (7M) should be very quickly. By rights should be less than a second.

If I say yes, I found that the current code is to transmit the 1 k by 1 k.
The problem should be caused by it.

Am I right?What should I do make it 2k,4 k or more k transport?

**Comment by r0m30** [comment]
Yes, the PBA load is slow due to using the default 2k packet size.  You mention 1K, have you pulled the latest code?  There is a change that uses all of the 2k packet to increase the load speed by ~1.9x.  Using a larger block size requires more work, the code assumes a 2k packet, this assumption is embedded in several parts of the code, so a lot of testing will be required to make sure all of the code is fixed.

There was another issue discussing this but I can't find it.

**Comment by liuligang** [comment]
Oh,the latest code is 2k packet size to transmit .
But it is 1950 (<2k) in fact.  Why want to leave a little space here?

 It is faster than 1 k transmission,but  he still need about 7 minutes .
 I want to 4 k transmission, I did the following things.

1. blockSize = 3802;(<4k)-----I also leave some space , although I don't know why
2. if (bufferpos > 4096)-------in DtaCommand.cpp
    {
	LOG(E) << " Buffer Overrun " << bufferpos;
	exit(EXIT_FAILURE);
    }

I found that do not achieve it. I also need to do?

**Comment by r0m30** [comment]
At the very least you'll need to modify the control blocks for the IO to account for the new data transfer size.

**Comment by liuligang** [comment]
Oh, I don't know much about it.
Is it change the **bufferlen** length  in the **--sendCmd command** ?

**Comment by r0m30** [comment]
There are fields in the IO control blocks that also specify the buffer length, have you verified that those are correct?

**Comment by liuligang** [comment]
Thank you for your help.
This problem has been resolved.
 It is feasible. Now download PBAimage about 30 seconds.

**Comment by pgeremia** [comment]
Hi @liuligang !  That is fantastic news.  Have you made the code changes yet and tested?  Could I see the changes?

**Comment by liuligang** [comment]
Oh,I change the code into 40k transmission. It download PBAimage about 30 seconds.
Generally the SSD write speed above 400 M/s and I think download PBAimage (7M) should be very quickly. In theory, it need about 7/400s to  download PBAimage .

But in fact, It is likely to slow down. I think it is no problem less than 1 minutes .
 So,I only change the code into 40k transmission.
I'm afraid more than 40k will affect other data transfer.

**I only change three places:**
1.blockSize = 40862;(<40k)-----I also leave some space , although I don't know why
2.if (bufferpos > 40960)-------in DtaCommand.cpp 
3.bufferlen =  40960;----------length in the --sendCmd command

**Comment by pgeremia** [comment]
Thanks very much!!  I will try this out and let you know how it works!

**Comment by pgeremia** [comment]
@liuligang  I was able to find the exact location for item #1 which was in DtaDevOpal.cpp.  I found item #2.  But I was not sure where to make change for item #3.  I ended up changing DtaConstants.h IO_BUFFER_LENGTH.  When I tested that I got a seg fault so I assume that is wrong.  Is there any way you can just post the code change snippets you made that worked for each file?  Thank You.

**Comment by liuligang** [comment]
Oh，May I know where you went wrong.

You should change the length in the --loadPBAimage command.
**length.push_back(0xe2);
length.push_back(0x00);
length.push_back(0x9f);
length.push_back(0x9e);**
You can try again.

**Comment by pgeremia** [comment]
@liuligang That worked!!! I made those changes and writing is now very fast!  I had to make some other changes as well.   It would be great to get these changes into github at some point.  Thank You!

**Comment by liuligang** [comment]
Though it is very fast, it is still a big question that  how much fast can be achieved.
Is there a limit or affect other transmission?

  @pgeremia Do you know about increase more users?
If you know I have a little problem need your help.

**Comment by pgeremia** [comment]
@liuligang I do not know.  I am sorry.

**Comment by AnyProblem** [comment]
I think the speed is depend on your Drive you can use  --query to know Tper Properties and your packet size do not more than the Max packet size

**Comment by liuligang** [comment]
First of all thank you very much. @AnyProblem 
I do the command --query and show following:
**TPer Properties:
  MaxComPacketSize = 66048  MaxResponseComPacketSize = 66048
  MaxPacketSize = 66028  MaxIndTokenSize = 65992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxAuthentications = 5
  MaxSessions = 1  MaxTransactionLimit = 1  DefSessionTimeout = 0**

It shows that my biggest transmission size can not be exceeded  MaxPacketSize = 66028 ,is it?

**Comment by pgeremia** [comment]
@r0m30 I have tested this to some extent and I have been successfully writing PBAs to SSDs without any problem as "lightening" speed.  Would you be able to review the changes and put them into the baseline?  This really helps improve usability for development and testing.   Let me know if that is possible.

**Comment by r0m30** [comment]
I'll look into using this a the base for a more universal solution to be included in the next release.

**Comment by r0m30** [comment]
V1.15 should allow up to 30x increase in PBA load speed.
