### ISSUE TITLE
Erasing OPAL 1.0 Without PSID

### ISSUE THREAD

**Issue by memnoch2001** [Drive-Trust-Alliance/sedutil#79]
Is it possible to revert an OPAL drive without a PSID?  It was activated when McAfee Encryption was installed and I don't have a password.  I don't care about any data on it so can be wiped, just want to be able to reuse the drive.

/dev/sda ATA HGST HTS725050A7E635  OPAL               GS26B840       RC055ACB3J4D6J
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = Y, LockingEnabled = Y, LockingSupported = Y, MBRDone = N, MBREnabled = Y, MediaEncrypt = Y
Opal V1.0 function (0x0200)
Base comID = 0x0010, comIDs = 1

TPer Properties: 
  MaxComPacketSize = 65536  MaxResponseComPacketSize = 65536
  MaxPacketSize = 65516  MaxIndTokenSize = 65480  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxSessions = 1
  MaxAuthentications = 2  MaxTransactionLimit = 1  DefSessionTimeout = 0
  MinSessionTimeout = 0
Host Properties: 
  MaxComPacketSize = 2048
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1

**Comment by r0m30** [comment]
Sorry but I know of no way to revert the drive without either the SID password or the PSID.

**Comment by webdawg** [comment]
So OPAL 1.0 does not have a PSID.  I have the MSID which is on the drive and you can grab via software but I guess since the drive has been activated, and I do not know the password, it is useless now?

**Comment by r0m30** [comment]
Yes, without a PSID OPAL is very much like secure erase, no password = bricked drive.
