### ISSUE TITLE
Difference SID password vs Admin1 password

### ISSUE THREAD

**Issue by scav666** [Drive-Trust-Alliance/sedutil#80]
Hi!

Could someone explain me in simple words what is difference between Admin1 password and SID password ?

**Comment by AnyProblem** [comment]
I think Admin password is used to set AdminSP and SID password is used to set LockingSP,
so you can use SID password to login your Drive, but if you want to set state of LockingSP you need to use Admin password, AdminSP can manage all SP in your Drive

**Comment by r0m30** [comment]
Yes, they are different users in different SPs, you use the SID to manage other SPs and the Admin to manage locking.
