### ISSUE TITLE
systemd resume hooks

### ISSUE THREAD

**Issue by Cysioland** [Drive-Trust-Alliance/sedutil#81]
systemd allows us to call commands when resuming from sleep. I wonder if it can be used to unlock the drive and optionally remount it read-write without any problem.

Can the drive even be temporarily unlocked with the use of `sedutil-cli`?

**Comment by r0m30** [comment]
I doubt it, it seems very unlikely that the system would get that far without trying to access the rootfs on the encrypted drive.

Yes, you can unlock the drive with sedutil-cli.  You need to unlock the drive and turn of the shadow MBR.
--setlockingrange 0 RW {password} {drive} will unlock the drive
--setmbrdone on {password} {drive} will unshadow the drive.

**Comment by cristim** [comment]
This functionality may work but the OPAL support would need to be implemented directly in systemd, so when the system resumes from sleep, one of the first things would be decrypting the drives with whatever code was already loaded in RAM and without any disk I/O.

This wouldn't surprise me with systemd at some point, they are known to add a lot of functionality to it.

**Comment by r0m30** [comment]
Have a look at the kernel tree.  Intel has added block/sed-opal.c, I haven't had a chance to look closely at this but it looks like it IS resume from sleep (S3) support for NVMe drives directly in the kernel.  Intel contributed the original NVMe support to sedutil and they appear to be interested ensuring OPAL support for NVMe drives in Linux.  This is one of the (many) things I need to research.

**Comment by martin3000** [comment]
You can unlock a drive with a systemd unit like this:
```
[Unit]
Description=unlock encrypted SED disk
After=suspend.target

[Service]
ExecStart=/usr/bin/sedutil-cli --setlockingrange 3 rw secret1 /dev/sdd
Type=oneshot
RemainAfterExit=no

[Install]
WantedBy=multi-user.target suspend.target reboot.target
```
