### ISSUE TITLE
Can the PBA unlock all drives if the password matches?

### ISSUE THREAD

**Issue by Rivqua** [Drive-Trust-Alliance/sedutil#84]
Hi,

I would like to have all my drives protected, and unlocked at the same time, can it be done with the PBA, or can the PBA image be modified to attempt to unlock all detected drives? 

Thanks,
R

**Comment by AnyProblem** [comment]
Hi,
I tried this scenario, and it was success if your all drives Password are same.

**Comment by r0m30** [comment]
Yes, as @AnyProblem says if the drives have the same password they will all get unlocked by the PBA.
