### ISSUE TITLE
Write PBA to unencrypted boot NVME drive?

### ISSUE THREAD

**Issue by lulkipvx** [Drive-Trust-Alliance/sedutil#88]
I have a samsung 950 pro NVME drive as my OS drive. I store all my data on a samsung 850 pro. I use sedutil to encrypt the 850 pro drive. 

I want to ensure that the PBA is loaded before windows boots up. Is there any way to write the PBA to the NVME drive where windows boots from? Currently I am manually booting off the 850 pro then getting the drive unlocked and finally booting to the OS. If I accidentally forget to boot off the 850 pro then I need to do a full reboot again to unlock it.

**Comment by Lutwick** [comment]
Hm, I cannot think of a solution here. If the PBA is in the non-shaddow PBA of your boot drive, it will always be loaded if that drive is the first of your boot order. The trick with the shaddow PBA is, that it is only loaded while the drive is locked.

But if you are booting from a non-locked drive without shaddow PBA, you can maybe write an autostart script calling the respective sedutil unlocking commands for your locked data drive once the OS is starting. So you don't even need the PBA at all.

**Comment by AnyProblem** [comment]
I think if you forget to boot PBA on 850 pro, you can use sedutil command to unlock 850 pro
sedutil --scan  // To know which PhysicalDrive number is 850 pro
sedutil setMBRDone on // To unlock 850 pro

when you power off it will auto lock your drive

**Comment by Lutwick** [comment]
I think the sedutil command to unlock the drive should be:
sedutil --setLockingRange 0 rw <password> <device>

The setMBRDone command is just there to tell the drive that the MBR has been loaded into the Shadow PBA, right?

**Comment by r0m30** [comment]
Can you change your boot order or does your bios "help" you by removing boot options that it no longer sees?  I'm assuming that you data drive doesn't have a bootable image on it.

The setmbrdone command tells the drive to present the real data and not the shadow MBR you need to both unlock the drive and set mbrdone to use the drive.
