### ISSUE TITLE
Chain loading the OS after authentication fails

### ISSUE THREAD

**Issue by o1y** [Drive-Trust-Alliance/sedutil#89]
Possibly similar to https://github.com/Drive-Trust-Alliance/sedutil/issues/19, but on a 32-bit BIOS based system.

I set up my drive as a boot drive and enabled locking.

I used the Debug PBA and get the message that unlocking the drive was successful but nothing more happens. The system won't boot.

```
Please enter pass-phrase to unlock OPAL drives: ****

Scanning ...

Unlocking /dev/sda  Success_
```

With regular PBA there is not output after entering the password. The system just freezes - the cursor stops blinking after some time and no keyboard input is possible. 

With the Debug PBA command prompt I've checked the locked stated:
`LOCKED = N, LockingEnabled = Y, LockingSupported = Y, MBRDone = Y, MBREnabled = Y, MediaEncrypt = Y`

The BIOS does not have such stuff like fastboot or hdd power cycling.

HDD is Samsung SSD 850 EVO.

Any ideas?

**Comment by o1y** [comment]
**Update**: I replaced the PBA with the [small lean PBA](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Executable-Distributions) for BIOS machines and now it works. Where can we find the sources for that image?

**Comment by r0m30** [comment]
There is a seperate repo for that PBA it is the SYSLINUX repo.  That PBA is based on the syslinux boot loader.
