### ISSUE TITLE
Instructions on building

### ISSUE THREAD

**Issue by Cysioland** [Drive-Trust-Alliance/sedutil#9]
I got referred here by r0m30/msed#31, so I need either a compiled version of everything, or instructions, how to build it myself.

**Comment by r0m30** [comment]
The wiki has both instructions for building 
https://github.com/Drive-Trust-Alliance/sedutil/wiki/Building-sedutil

and 

links to compiled binaries
https://github.com/Drive-Trust-Alliance/sedutil/wiki/Executable-Distributions

**Comment by Cysioland** [comment]
Executable libraries are enough for me
