### ISSUE TITLE
Unlock non-boot drives on already-booted machine headlessly.

### ISSUE THREAD

**Issue by willglaub** [Drive-Trust-Alliance/sedutil#93]
I am interested in being able to use the SED functionality on linux servers, such that after booting from a non-SED locked drive into linux, my program can use some [unknown] library or command-line utility to unlock/relock non-boot SED drives on the system (with my program providing password/s which I retrieve over the network from an already running secure distributed system with physical intrusion-detection-system tie-ins whose details are not important to the question.)  

In other words, I am looking for **a way to lock and unlock SED drives headlessly.**  There will not be a human to enter a password in a PBA ever.  The system must be already booted, in order for my software to interact with the network and other servers comprising the distributed system in order to get the passwords from off-machine.  It would be acceptable to do a boot, run a part of my software to get passwords and initiate unlock, initiate a soft-reboot, before being able to access the SED drives on the subsequent boot, but preferably, no additional soft-boot would be required, and I could even watch for hot-swaps (with modahci enabled), check if the device had OPAL by programatically running the sedutil --scan and sedutil --query /dev/sdX on it, and then invoke this unknown method that I'm asking about, but cannot find.  The answer I'm looking for might be a command-line option for sedutil, some other command-line program, a C or other language library somewhere (perhaps something that sedutil itself uses for some operations?), a series of kernel system calls, or hooks, a series of ATA messages that could be issued and where they are documented, or it might unfortunately be "No, the lock/unlock can only be done in a pre-boot environment because..." or "No, that requires some vendor license".    Thanks very much in advance.

**Comment by webdawg** [comment]
"a way to lock and unlock SED drives headlessly"

Can't it do this now if you pass the password to it?

**Comment by willglaub** [comment]
Which command-line option would this be?  you can just run that command with the password provided to the command, and the drive is accessible and then inaccessible after hard reboot?  Reading the command syntax doc, nothing jumped out at me as being able to do that, but maybe I misread something.  Can you give me a specific command?  Some of the TCG Opal terminology may just be hindering my reading comprehension :-)  If I truly can just use an already existing command in sedutil to unlock the drive, that would be a great answer.  Thanks.

**Comment by willglaub** [comment]
is it as simple as
sedutil --setLockingRange 1 rw PASSWORD /dev/sdc   
(for example, to unlock sdc as read-write)?  
I had read that series of options a being for setting up locking ranges (along with other options), but maybe that was a mistake on my part.   Or is it a different command option? 
I think it would be helpful to folks wanting to do the same sort of thing as me to show a small series of commands with sample output for creating the locking ranges, and locking/unlocking them, in addition to the existing sample output where the scan and query were shown.  Perhaps a slight bit more explanation in the Command Syntax page's Description column might go a long way.  I appreciate you answering so quickly, btw.

**Comment by willglaub** [comment]
After reading the TCG OPAL SSC, storage application notes, etc. official documents for better understanding the specialized terminology used in the sedutils documentation, I believe that my immediately previous post is indeed the command used for locking and unlocking the ranges in a normally booted environment.  I am closing this issue.  The resolution was:  sedutil already supports this feature, as noted.  The community was very fast in responding with a comment that allowed me to quickly find my own answer.  Thanks.
