### ISSUE TITLE
PBA test does nothing

### ISSUE THREAD

**Issue by zzvara** [Drive-Trust-Alliance/sedutil#94]
Hi!

I was able to boot into UEFI PBA verifier and it asked for a passphrase, but after that quickly wrote out a few wrapped lines and the PC got rebooted normally. What should I expect here?

Thanks!

**Comment by Lutwick** [comment]
The wiki page "[Test the PBA on your machine](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Test-the-PBA)" is a little outdated, so don't expect to get a list of your OPAL disks. If you try the PBA from a USB stick and your SSD disk is still not activated for OPAL locking (as it is recommended before the PBA has been successfully tested) you will get an error message including "INVALID PARAMETER" (see [this issue](https://github.com/Drive-Trust-Alliance/sedutil/issues/73)). But this shows that the PBA is actually working and finding your disk.

**Comment by MyCookie** [comment]
I'm having the issuse, but I didn't fully understand your reply. If the test finishes and reboots my system are **all** my disks supported? The text flies too fast to be able to read anything.

**Comment by Lutwick** [comment]
Hm, I don't know what happens when the PBA finds one OPAL supporting and one non-supporting drive. Sorry.

**Comment by MyCookie** [comment]
That's OK, I'll have to manually remove the known SSD and boot the USB again. Thanks.

**Comment by zzvara** [comment]
Okay @Lutwick just to clarify, so if the PBA test tool - after booting it from an USB stick - does the following:

1. Asks for any passphrase.
2. Quickly prints out a few lines of wrapped text that is impossible to read due to it happens so fast.
3. Reboots the machine.
4. The OS loads normally.

Then the conclusion should be that my SSD supports OPAL?

Thanks!

**Comment by Lutwick** [comment]
@zzvara Not quite. The conclusion is that the PBA is working with your system, which is what this PBA test is all about. Whether or not your SSD supports OPAL you will see when you try the sedutil setup and lock commands.

`sedutil-cli.exe --scan`
etc. as described in the [wiki](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive).

**Comment by rsb00** [comment]
@Lutwick, just to confirm a point that you made near the top of the thread:  When you test the PBA off a USB stick, an error message, which includes "INVALID PARAMETER", "Session start failed", and "Unlock failed - unable to set LockingRange" is expected?  

I'm testing the UEFI PBA and after entering an arbitrary pass phrase, I get this error message.  I'm hoping to confirm that the test actually succeeded versus failed.  Thanks!

**Comment by Lutwick** [comment]
@rsb00 I'd say the PBA test has passed if you get the password prompt (and also the error messages when entering an arbitrary password for a non-setup SSD). The PBA test from USB is really just about verifying that the PBA operating system is properly booting on your individual system, which is the case when you get the password prompt.

**Comment by rsb00** [comment]
@Lutwick , thanks for the clarification.

**Comment by zzvara** [comment]
@Lutwick I've locked the drive successfully, but unfortunately the PBA was not working as you've suggested. PBA fails to unlock the drive, that's why we receive the error messages during the tests. The "test" is really bad, since no messages are readable, but those error messages indicate that it will not work. I guess the PBA uses `sedutil` commands to unlock the drive, but all the commands fail. Password was completely OK. Another guide says that the password can not be longer than 32 characters, and `hdparm` will alert that it will be invalid. My supplied password was longer than 32 characters while trying my luck with `sedutils`. Maybe this was the problem? With `hdparm` I was able to lock and unlock the drive successfully, but `sedutils` failed to unlock it. I had to `ddrescue` the whole image.

**Comment by Lutwick** [comment]
Hi @zzvara, there seems to be a lot mixed up here. hdparm is only for your disks ATA-password. That's something completely different from OPAL that is handled by sedutil (cf. e.g. https://vxlabs.com/2015/02/11/use-the-hardware-based-full-disk-encryption-your-tcg-opal-ssd-with-msed/#comment-117737).

So if you only locked your disk with hdparm (i.e. ATA password), it's completely normal that sedutil PBA cannot unlock it and gives theses (admittedly not very helpful) error messages.

Furthermore, I am confused why you had to ddrescue your disk. Because if your drive was locked/encrypted (ATA or OPAL), then also ddrescue would not have helped anything.

**Comment by zzvara** [comment]
I've dd'd my disk beforehand, to have a clean backup of everything. I did
not use hdparm mixed with sedutils. I'm just saying that I've tried hdparm
after sedutils bricked my SDD, and after I've successfully ddrescued the
disk.

In fact I've completely followed the guide on the Wiki. All the commands
were successful, but the last one, which would unlock the drive with my
password.

**Comment by Lutwick** [comment]
With sedutil you can never brick your drive. You can always reset it loosing all data (unlike hdparm where you can really brick your drive when you forget the ATA password).

Which commands did you try, of which the last one did not work?
The current wiki (https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive) suggests:

sedutil-cli  -–initialsetup <password> <drive>
sedutil-cli –-loadPBAimage <password> <pbafilename>  <drive>
sedutil-cli –-setMBREnable on <password> <drive>
sedutil-cli –-enableLockingRange 0 <password> <drive>

This sets up the password and PBA.
What did you try that did not work afterwards?

**Comment by r0m30** [comment]
This appears to be an abandoned thread, if not reopen.
