### ISSUE TITLE
Can't load PBA -> ERR : Method Status missing

### ISSUE THREAD

**Issue by Lauvergnat** [Drive-Trust-Alliance/sedutil#95]
While trying to load the UEFI PBA, I got an error : 

```
# sedutil-cli --loadPBAimage <password> UEFI64_Release.img /dev/sda
- 00:22:15.665 INFO: Writing PBA to /dev/sda
 - [************         ] 4311040- 00:24:17.656 ERR : Method Status missing
```

My SSD is a Crucial M500 120G.

Any idea ?
Thanks in advance !

**Comment by r0m30** [comment]
Nothing definite, but that's not normal.  Is the firmware current?  I use Crucial drives in my system and as test drives and have never seen this.
