### ISSUE TITLE
Few questions about using sedutil

### ISSUE THREAD

**Issue by peterek1983** [Drive-Trust-Alliance/sedutil#98]
Hello, I have few questions about using sedutil

First question, as I read sedutil do not support S3 sleep mode, so only option is to use hibernate but do I have to everytime from wake from hibernate enter the password ?

I plan to use it with Crucial MX200 250GB drive, but does it safe if something goes wrong ? no risk of bricking drive if I use for example some bad command ?

Does it 100% guarantee that this opal locking can be removed from any drive which was previously locked by sedutil ?
Can I be sure that will be no any problem with remove this opal locking from this Crucial MX200 250GB ?

Would be nice to someone write tutorial step by step how to use this on Windows.
I really don't know which files I have to download and where to use them.
I'm using Asus Z170 Deluxe motherboard with UEFI.

Thank you.

**Comment by r0m30** [comment]
There are way to many variables to guarantee that the software will work on all machines and all drives.
If you want 100% certainty then don't use the software.
