### ISSUE TITLE
Bricked my SDD

### ISSUE THREAD

**Issue by Lutwick** [Drive-Trust-Alliance/sedutil#99]
Hi,

I always assumed, it's not possible to brick your SSD with OPAL, but apparently this just happened to me:

I connected a Samsung SSD 850 PRO 256 GB via USB-to-SATA cable to my Windows 7 (32-Bit) PC.

initialSetup and enableLockingRange 0 worked fine.

Then I tried loadPBAimage, but it always failed after some amount of progress with a
**Command failed on send 2**
error message.

I tried this several times and the progress percentage at which this occured was always different.

I also tried to unplug and replug the SSD a few times and tried loadPBAimage again. But at some point it was not recoginsed as an OPAL compliant disk any more.

Now, when I do --scan, my other disks are listed at once, but then it pauses for almost one minute before showing me
\\.\PhysicalDrive2 No

So now I have an OPAL locked SSD that is not recognised as an OPAL compliant disk.
Seems pretty bricked to me... :-(

**Comment by Lutwick** [comment]
OK guys. False alarm.

I just inserted the SSD in the actual SATA slot of my laptop and booted from the sedutil rescue USB stick.

Then I was completely able to access the disk with sed-util and everything!

So I guess the lesson learned is: never use a USB-to-SATA cable when doing OPAL-relevant stuff.

**Comment by r0m30** [comment]
Some of the USB-SATA cables are flaky.  I've tried some of the really cheap ones and experienced the same thing except that a unplug/plug of the cable usually fixed the issue.

**Comment by Lutwick** [comment]
Indeed. I think that particular cable I was using was already on the brink of being completely broken. A few weeks later I could not even mount normal hdd disks with it any more.

**Comment by gomoku** [comment]
I confirm the issue with the USB-SATA cables, in my cases combined with SSD Samsung 850 EVO 120GB, the --scan & --query commands work, but some commands throw errors:

```
sedutil-cli -v --revertnoerase newPassword \\.\PhysicalDrive1
- 14:05:53.000 DBG : Log level set to DBG
- 14:05:53.000 DBG : sedutil version : 1.12
- 14:06:18.938 ERR : Command failed on send 2
- 14:06:18.938 ERR : Command failed on exec 2
- 14:06:18.938 ERR : Properties exchange failed
- 14:06:18.938 DBG : Performing revertLockingSP  keep global locking range on \\.\PhysicalDrive1
- 14:06:36.703 ERR : Command failed on send 2
- 14:06:36.703 ERR : Command failed on exec 2
- 14:06:36.703 ERR : Session start failed
- 14:06:53.391 ERR : Command failed on send 2
- 14:06:53.391 ERR : Command failed on exec 2
- 14:06:53.391 ERR : EndSession Failed

sedutil-cli -v --setSIDPassword oldPassword newPassword \\.\PhysicalDrive1
- 14:10:31.000 DBG : Log level set to DBG
- 14:10:31.000 DBG : sedutil version : 1.12
- 14:10:49.703 ERR : Command failed on send 2
- 14:10:49.703 ERR : Command failed on exec 2
- 14:10:49.703 ERR : Properties exchange failed
- 14:10:49.703 DBG : Performing setSIDPassword
- 14:11:07.469 ERR : Command failed on send 2
- 14:11:07.469 ERR : Command failed on exec 2
- 14:11:07.469 ERR : Session start failed
- 14:11:24.156 ERR : Command failed on send 2
- 14:11:24.156 ERR : Command failed on exec 2
- 14:11:24.156 ERR : EndSession Failed
```

The issue disappears after connecting the SSD directly with SATA cable in the computer.
This is my USB-SATA cable: [LINK](http://allegro.pl/ac1-kabel-adapter-usb-hdd-7-15-pin-2-5-sata-i5933513724.html?snapshot=MjAxNi0wMy0zMVQxMTo1NjoyNlo7YnV5ZXI7NTY3MzUzZDU1NWI4NTE2OTllYTRiMTA5OTc5NzNjNmExODAwNTU5MTM0NGIxZjYwMWZlNGNjNmQ4NGM0NDU5MQ==)
It costs about 3$.
